### ISSUE TITLE
The Kaaba Emoji!

### ISSUE THREAD

**Issue by AlmightySosa** [twitter/twemoji#107]
A holy site for Muslims is the Kaaba which now has an emoji. But it seems that Twemoji is on the edge of making it the way it should be. Kaaba literally means cube in Arabic and what is seen is not a cube nor a square. Please follow the other Emoji makers to make one less offensive.
(Emoji One has the best icon of the Kaaba in my opinion but would be better if they covered the top)

![kaaba](https://cloud.githubusercontent.com/assets/13771666/11911712/5681e9ea-a5e4-11e5-909d-48b362d47c71.PNG)

**Comment by rikimaru1** [comment]
"Offensive"...

Get out of here, man.

**Comment by lewisje** [comment]
:+1:

**Comment by Alinaki** [comment]
But Kaaba **has** rounded top edges.

**Comment by lewisje** [comment]
The rounding is so slight, it's hard to notice unless you look closely.

**Comment by AlmightySosa** [comment]
And even if you were going to show the rounding, the emoji is wayy too curved.
![kaaba2 1](https://cloud.githubusercontent.com/assets/13771666/14579004/03b9ac28-0360-11e6-90f4-1e69c533792b.jpg)

**Comment by bhaggs** [comment]
We've updated this emoji in our latest release. 
[Kaaba emoji](https://github.com/twitter/twemoji/blob/74809672775feade024d77cd15c20e385522a690/2/72x72/1f54b.png)
