### ISSUE TITLE
Keycap Digit URLs different

### ISSUE THREAD

**Issue by aquach** [twitter/twemoji#111]
Unicode is a little strange to me, so I could be totally off base on this, but given that the hex for keycap digit 8 is `0038 20e3`, it seems like the corresponding URL should be 

https://twemoji.maxcdn.com/svg/0038-20e3.svg

rather than

https://twemoji.maxcdn.com/svg/38-20e3.svg

as it currently stands. It might just be a matter of convention, but aren't all bytes usually expressed even if they're 0? FWIW, github's URL: https://assets-cdn.github.com/images/icons/emoji/unicode/0032-20e3.png

**Comment by WebReflection** [comment]
for some reason assets had no leading zero in their names and everything is based on current available assets. Hopefully not a big deal, or to look at the bright side, we save 2 bytes in the URL there: yaiiiii!
