### ISSUE TITLE
Unable to see 🇮🇳  flag in twemoji 

### ISSUE THREAD

**Issue by athimannil** [twitter/twemoji#112]
Unable to see 🇮🇳 flag emoji flag in twemoji 
```  
      <li>&#x1f1ee;&#x1f1f3;</li>
      <li>&#x1f1ee-1f1f3;</li>
```

**Comment by WebReflection** [comment]
can you please double check [version 2](https://github.com/twitter/twemoji#unicode-80-and-diversity) and in case it works close this bug?

Here a preview page: http://twitter.github.io/twemoji/2/test/preview.html
