### ISSUE TITLE
why not provide a emoji-cheat-sheet, just like GitHub Emoji ?

### ISSUE THREAD

**Issue by xgqfrms** [twitter/twemoji#113]
[GitHub Emoji :octocat:](https://github.com/xgqfrms/emoji-cheat-sheet.com)
It will be very useful when some newer wants to use special emoji!

**Comment by jerrygrey** [comment]
[https://twitter.github.io/twemoji/preview.html](https://twitter.github.io/twemoji/preview.html)?

**Comment by xgqfrms** [comment]
Thanks for your time!
I didn't found it!

**Comment by andersruneson** [comment]
Close this issue?

**Comment by xgqfrms** [comment]
Close this issue?
OK!
http://twitter.github.io/twemoji/preview.html
