### ISSUE TITLE
Not an active Travis CI Repository

### ISSUE THREAD

**Issue by WebReflection** [twitter/twemoji#116]
I don't know why this happened but apparently somebody made Travis CI builds inactive.

## I'd like an official statement from Twitter about this project

Because this has gone a bit too far.

Nobody is informing me about anything, people keep complaining, new assets are nowhere, and now [Travis CI has been disabled](https://travis-ci.org/twitter/twemoji)?

This is not how I was thinking to help this project.

![screenshot from 2016-02-08 12-06-21](https://cloud.githubusercontent.com/assets/85749/12885317/f01de6f8-ce5c-11e5-8eaf-ef1bcc01f1c7.png)

**Comment by mathiasbynens** [comment]
:o

**Comment by WebReflection** [comment]
OK, builds work now, yet I really would like to unedrstand what is going on with this project.

The README should also be updated because I believe I'm the only one left here actively maintaining but if not, which I hope, please let me know who would be my point of contact and **please** inform me about progress of any kind or current status.

Thank you
