### ISSUE TITLE
Best way to add a new symbol

### ISSUE THREAD

**Issue by edent** [twitter/twemoji#128]
I'd like to add http://unicodepowersymbol.com/ to the set of emoji. It's 5 symbols which are due to be published in Unicode 9.0.

The [current SVGs are monochrome](http://unicodepowersymbol.com/wp-content/uploads/2015/05/Unicode_IEC_symbol.svg), are they sufficient - or should they be colourised first?

**Comment by bhaggs** [comment]
We'll consider incorporating these once they've either been approved or added to a draft spec from Unicode.

**Comment by edent** [comment]
They have been approved and are in the v9 draft spec. 

http://www.unicode.org/charts/PDF/Unicode-9.0/U90-2300.pdf
