### ISSUE TITLE
Error while the 1st argument of twemoji.parse is undefined 

### ISSUE THREAD

**Issue by josephj** [twitter/twemoji#135]
It gets error when the 1st arg of twemoji.parse method is undefined. 

```js
var message;
try {
  twemoji.parse(message)        
} catch (e) {
  console.error(e.message);
}
```
![js_bin](https://cloud.githubusercontent.com/assets/136648/14235585/253a000a-fa46-11e5-998b-74a8badaecc1.png)

So I always need to convert the value manually to avoid the error (`message = message || ''`) which is not very convenient. 

Live Example:
http://jsbin.com/kahaca/edit?html,console

**Comment by WebReflection** [comment]
The signature expects either a string or a DOM node. Any reason you don't know you are converting something that you shouldn't?

What I mean is that this is not really a bug, rather an API expectation. It will be eventually fixed, I just don't know if it's worth bothering too much. What kind of error would you prefer instead? Or you are suggesting a silent error?

**Comment by WebReflection** [comment]
in case silent error is what you are looking for, should it be silent with anything that is not `typeof "string"` and doesn't have `childNodes`? woudl this work? Thanks

**Comment by josephj** [comment]
How about returning the original input value when it's not `String` nor `HTML Element`? #137

**Comment by josephj** [comment]
#137
