### ISSUE TITLE
Duplicate Access-Control-Allow-Origin header from CDN

### ISSUE THREAD

**Issue by AlexKasaku** [twitter/twemoji#140]
When loading the JS from the CDN (//twemoji.maxcdn.com/2/twemoji.min.js), the headers in the reponse have a duplicate **Access-Control-Allow-Origin** parameter.

As we are loading the script on demand through an AJAX call, this results in the following error within Chrome:

`XMLHttpRequest cannot load http://twemoji.maxcdn.com/2/twemoji.min.js. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://example.com' is therefore not allowed access.`

I believe this has only changed recently (within the last week) as this script was working previously.

**Comment by WebReflection** [comment]
This is a MaxCDN thing (or you updated the browser that wasn't so picky before).

I've tried to contact them, let's hope will be solved soon.
The entire Twemoji page, tests, etcetera, has this duplicated header.

Thanks for letting us know.

**Comment by jdorfman** [comment]
Looking into it!

**Comment by jdorfman** [comment]
Ok I see what is happening.  GitHub/Fastly starting adding CORS headers.  

```
$ icurl http://twitter.github.io/twemoji/2/twemoji.min.js
HTTP/1.1 200 OK
Server: GitHub.com
Access-Control-Allow-Origin: *
```

When Twemoji first launched, that wasn't the case.  I have since removed the `Access-Control-Allow-Origin` header (on the CDN) so it will not be duplicating anymore:

```
$ icurl twemoji.maxcdn.com/2/twemoji.min.js
HTTP/1.1 200 OK
Date: Fri, 15 Apr 2016 17:08:13 GMT
Content-Type: application/javascript; charset=utf-8
Content-Length: 8782
Connection: keep-alive
Last-Modified: Wed, 13 Apr 2016 13:53:22 GMT
Access-Control-Allow-Origin: *
Expires: Sun, 15 May 2016 17:08:13 GMT
Cache-Control: max-age=2592000
X-GitHub-Request-Id: C71B4F17:2087:E212983:57111FF1
Vary: Accept-Encoding
X-Fastly-Request-ID: f164d13c1f6a00a8ef86a2674f4fc6f607db1486
Server: NetDNA-cache/2.2
Powered-By: MaxCDN
X-Cache: HIT
Accept-Ranges: bytes
```

**Comment by WebReflection** [comment]
I can confirm it's all good now (I had duplicated header too and now not anymore).

Now that was quick: **thank you**!

**Comment by jdorfman** [comment]
@WebReflection you are welcome.  That's just how we roll.

**Comment by AlexKasaku** [comment]
Super fast resolution, thanks!

**Comment by jmdarts007** [comment]
Thanks for imaging
