### ISSUE TITLE
Usage in logos

### ISSUE THREAD

**Issue by thomaspaulmann** [twitter/twemoji#141]
Hey Twemojis,

First things first, this is not really an issue, it's more a legal question but I think it's the quickest way to get the correct answer. So, is it allowed to use the twemojis in custom logos? And if so, is it also allowed to recolor or reshape them? Would be awesome to here from you!

Thanks in advance ✌️

**Comment by WebReflection** [comment]
Does this paragraph answer your question?
https://github.com/twitter/twemoji#attribution-requirements

**Comment by thomaspaulmann** [comment]
Thanks @WebReflection for the fast response. I've totally overlooked the paragraph...
I'm not a lawyer, but it brings some clearness into the topic. Does I understand it correctly and as long as I reference the Twemoji project, everything is alright? 🚓

**Comment by WebReflection** [comment]
that'd be my interpretation as well ;-)

**Comment by strivesun** [comment]
nice
