### ISSUE TITLE
Add keyword search field to the preview page

### ISSUE THREAD

**Issue by dvorapa** [twitter/twemoji#143]
Add a search field to the preview page and assign keywords to each emoticon. Inspiration: http://ionicons.com/

**Comment by WebReflection** [comment]
there are no keywords mapped to unicode chars. twemoji doesn't use classes, it uses unicode chars.

You can retrieve them by clicking on any icon in the preview page.

**Comment by dvorapa** [comment]
@WebReflection I know, but if we could create a keyword map and add search field, there would be a better chance to find the icon user wants between 874 icons. I sometimes spend over 10 minutes searching for specific icon and surely I'm not alone.

**Comment by WebReflection** [comment]
mobile didn't solve it like that, it rather groups by "kind" (probably using predefined ranges)

all platforms offering emoji do that, would such approach work better?

Also consider that's just a visual test page, is not  meant to be a useful product/page.

The fact if you click an icon you can grab the emoji is already a little out of preview page scope.

**Comment by dvorapa** [comment]
I understand, but I can not add an emoji dropdown to my website (because of its purpose). And twitter.com users also has to google out twemojis, because there is not any twemoji dropdown on twitter.com page. This preview is the one many twitter.com users and users of my website use (and google for it).

I think regrouping by kind would be also useful solution.
