### ISSUE TITLE
What happened to twemoji.com?

### ISSUE THREAD

**Issue by dvorapa** [twitter/twemoji#144]
Why is this domain not working?

**Comment by DerkJanSpeelman** [comment]
https://cdnjs.cloudflare.com/ajax/libs/twemoji/2.0.5/twemoji.min.js

This link is up, but has errors with the latest smileys.
see my last added issues "WRONG LINK!" and you'll be fine

**Comment by dvorapa** [comment]
I asked about twemoji.com, where was a preview.html set previously

**Comment by WebReflection** [comment]
why do you think it should work?

AFAIK nobody here is linking, suggesting, or maintaining that domain.

**Comment by WebReflection** [comment]
the official CDN package is twemoji.maxcdn.com/2/twemoji.min.js and is written in here https://github.com/twitter/twemoji#version-2-cdn-support

**Comment by WebReflection** [comment]
also, this is always available via github pages:
http://twitter.github.io/twemoji/

**Comment by dvorapa** [comment]
The twemoji.com domain worked a year ago (with preview.html loaded as an index.html). I don't know who maintained the url, but it contained just the content of preview.html and link to this repo. I had to change all urls on my website leading to twemoji.com (to https://twitter.github.io/twemoji/preview.html)

**Comment by WebReflection** [comment]
again, I have no idea who is maintaining twemoji.com ... so I personally can't do anything about it.

You should use the latest preview page which is this one:
https://twitter.github.io/twemoji/2/test/preview.html

It has 1661 emoji, including diversity, the v1 preview page has half of them.

**Comment by dvorapa** [comment]
@WebReflection I see, I'll change link to v2, good idea, thank you.
