### ISSUE TITLE
WRONG LINK!

### ISSUE THREAD

**Issue by DerkJanSpeelman** [twitter/twemoji#145]
Hello Twemoji,

in your jquery link i replaced "//twemoji.maxcdn.com/" with "//abs.twimg.com/emoji/v2/" from twitter and set the size to 72x72 and now I dont have any errors with the latest smileys :+1:

Hope you will fix this soon! (I had errors with 🤐 the smiley with the zapper as mouth)

also... your link is down or something, so I checked cdnjs.com for the link. Found https://cdnjs.cloudflare.com/ajax/libs/twemoji/2.0.5/twemoji.min.js < this one. But it had errors as I explained before

additionally: changing the link will not be enough because the regex only checks for valid unicodes. so you need to copy the emojicons that dont work and throw it in a javascript escape or online unicode decoder or create your own.

have a nice day

**Comment by WebReflection** [comment]
which jquery link? mind to file a PR instead?
