### ISSUE TITLE
Support for Unicode 9.0

### ISSUE THREAD

**Issue by msbukkuri** [twitter/twemoji#148]
Unicode 9.0 is released on June 21, 2016 => http://emojipedia.org/unicode-9.0/

When will the TwEmoji library support this? What is the plan of action here?

**Comment by bhaggs** [comment]
We're actively working on this now and will be updating the repo with the new assets once completed.

**Comment by bhaggs** [comment]
The library is now to spec with Unicode 9.0.

**Comment by msbukkuri** [comment]
@bhaggs Thanks!
