### ISSUE TITLE
Plugin not working with strings from database

### ISSUE THREAD

**Issue by kthnxbye** [twitter/twemoji#152]
Hello m8s

Im not entirely sure if its about the plugin usage or what, but i have a filter in angularJs (1.5) like this:

`function emoji() {
        return function (text) {
            console.log(text);
            return twemoji.parse(text);
        };
    }`

the text is a from the database:

`span(ng-bind-html="vm.message.subject | emojii")`

but just wont work .. the weird thing is if i hardcode the string it comes out perfectly parsed.. 

i have the sanitise plugin installed if that matters

thank you in advance

**Comment by WebReflection** [comment]
I don't `AngularJS` but if you pass a parsed text to anything that sanitizes HTML then you won't see the emoji because that's inside an image tag. Does this answer your question?

**Comment by kthnxbye** [comment]
Yep, i understand the problem now but i just can remove the sanitise dependency, i'll look a work-around then. tyvm

**Comment by WebReflection** [comment]
I am sure you know what you are doing but if I might, be careful with removing security oriented features since I'm pretty sure if it was there, there is a reason.

**Comment by vb93** [comment]
I faced the same issue. What you are getting from database has '\\u26BD\\uD83C' because your backend is escaping back slash with double backslashes. You need to replace "\\" with "\u"
```
function unescapeUnicode(str) {
				return str.replace(/\\u([a-fA-F0-9]{4})/g, function(g, m1) {
					return String.fromCharCode(parseInt(m1, 16));
				});
			}
```

**Comment by WebReflection** [comment]
I remember problems like this like ... .with PHP4, are you in PHP? Just curious, for whoever will ask next.
