### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [twitter/twemoji#153]
I am using this (version 2) and it's not loading: 

https://twemoji.maxcdn.com/2/16x16/1f60e.png

Getting a 404 not found error basically.  

Do I wait?

**Comment by WebReflection** [comment]
16x16 is not part of v2. I think you should use 72x72 or svg.

Or ... was 16 working on v2 before? IIRC it wasn't.

**Comment by bhaggs** [comment]
Version 1 supported 16x16, 36x36, and 72x72. As part of version 2 we moved to only offering the 72x72 png version in addition to svg and Illustrator versions. As @WebReflection suggested, you should use 72x72 png or svgs instead.

**Comment by vijayaraghavanramanan** [comment]
Thanks!
