### ISSUE TITLE
U+1F683 RAILWAY CAR should not look like a tram car

### ISSUE THREAD

**Issue by salty-horse** [twitter/twemoji#154]
The graphic for U+1F683 RAILWAY CAR depicts it as a tram car, with connectors to electric wires above.

There is already a dedicated tram codepoint, U+1F68B TRAM CAR. In Twitter's representation, the only difference between the two is the color pattern.

Please make U+1F683 look like an actual railway car.

**Comment by bhaggs** [comment]
Fixed in 60607234915acbfd84bea131afb78d8032e83806
