### ISSUE TITLE
Some Emojis seem to be missing.

### ISSUE THREAD

**Issue by MarkRH** [twitter/twemoji#159]
I am actually using a Firefox add-on based on this and created an issue there: https://github.com/Rudloff/emoji-everywhere/issues/4

Seems the crab emoji for example which seems to be 1F980 is missing. 🦀 I found it here: http://emojikeyboard.org/

Twitter's website can interpret and render it but this add-on can't. I went poking around and did not see any 1f980.png files files.  I use Windows 7 Pro 64bit so would need to use something like this.

Looked at http://emojipedia.org/unicode-9.0/ and it didn't any of those 72 emojis so perhaps his add-on isn't using the latest version of this. Hmm.

**Comment by bhaggs** [comment]
You are likely looking at version 1 of Twemoji. Version 2 includes the crab emoji.

https://github.com/twitter/twemoji/blob/gh-pages/2/72x72/1f980.png
