### ISSUE TITLE
How to generate 16x16 png assets personally in Version2 ?

### ISSUE THREAD

**Issue by qiangbro** [twitter/twemoji#160]
in V2, the default PNG icon size is 72 pixels and there are no other PNG assets for 16 or 32.
Can I generate 16x16 or other resolution png assets personally?
How to do it?
How to generate 16x16 png asset  or  36x36 png asset by myself? @twitter

**Comment by Simulacrux** [comment]
Hi qiangbro, 

I'm using a 24x24 Pixel size for a Pidgin smiley theme and discoverd a easy way to convert the svg files to png files in every size wanted. Just download the Open Source Software InkScape which is capable to display and change svg files. After the Installation you could use the command line to batch convert all svg files to png.

I've written a short batch file to do it in 24x24 Pixels (in 
 

    SET svgdir=D:\Temp\twitter\svg
    SET pngdir=D:\Temp\twitter\png
    
    FOR %%i IN (%svgdir%\*.svg) DO IF NOT EXIST "%pngdir%\%%~ni.png" "D:\Tools\InkScape\inkscape.exe" -f "%%i" -e "%pngdir%\%%~ni.png" -w 24 -h 24

    pause

    SET svgdir=
    SET pngdir=

 
Best regards
Simulacrux

**Comment by qiangbro** [comment]
thanks @Simulacrux , the batch file works fine!

**Comment by WebReflection** [comment]
I assume Simulacrum solved the issue.
