### ISSUE TITLE
Gender Neutral and Specific Animals

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#164]
Some dimorphous animals are shown with male or female attributes in Twemoji although the character name or the Unicode specification say nothing about their sex. It would be nice if Twemoji’s default illustration could be as generic as possible and explicit [ZWJ sequences](http://www.unicode.org/emoji/charts-beta/emoji-zwj-sequences.html) with U+2640 &#x2640;&#xFE0F; and U+2642 &#x2642;&#xFE0F; would be supported, even though they have not yet been recognized by Unicode.
## 🐂 U+1F402 Ox/Bull vs. 🐄 U+1F404 Cow

![&#x1F402; Ox](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f402.png) ![&#x1F404; Cow](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f404.png) ![&#x1F42E; Cow Head](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f42e.png) ![&#x1F401; Aurox](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f403.png) ![&#x1F4; Goat](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f410.png)

All of the Twemoji cattle emoji ar erather generic. None has a visible udder (and neither does the Goat). Some other fonts and image sets do distninguish the sexes, though, so that may lead to minor confusion.
## 🐏 U+1F40F Ram vs. 🐑 U+1F411 Sheep/Ewe

![&#x1F4F; Ram](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f40f.png) ![&#x1F411; Sheep](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f411.png)

Sheep with horns are mostly considered male, so you actually got two rams there and no ewe.
## 🐓 U+1F413 Rooster/Cockerel vs. 🐔 U+1F414 Chicken/Hen

![&#x1F413; Rooster](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f413.png) ![&#x1F414; Chicken](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f414.png) ![&#x1F424; Chick](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f424.png) ![&#x1F425; Front-Facing Chicken](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f425.png) ![&#x1F423; Hatching Chick](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f423.png) ![&#x1F357; Poultry](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f357.png)

Both chicken look rather gender-neutral, although – like Apple – Twemoji should probably not show just a head for the second one. A hen could be shown with chick, egg or nest.
## 🐗 U+1F417 Boar

![&#x1F417; Boar](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f417.png) ![&#x1F416; Pig](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f416.png) ![&#x1F437; Pig Head](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f437.png) ![&#x1F43D; Pig Nose](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f43d.png)

For most pigs and boars, only males have large, visible tusks. Although Apple does the same, it should probably be shown with body, too.
## 🦁 U+1F981 Lion Head

![&#x1F481; Lion Head](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f981.png) ![&#x1F42F; Tiger Head](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f42f.png) ![&#x1F431; Cat Head](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f431.png) ![&#x1F405; Tiger](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f405.png) ![&#x1F406; Leopard](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f406.png) ![&#x1F408; Cat](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f408.png)

A lioness usually doesn’t have a mane, but it’s an iconic difference to other large cats.
## 🦃 U+1F983 Turkey

![&#x1F983; Turkey](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f983.png)

Sure, the male wild turkey is more iconic and colorful than the female one, but they both exist.
## 🦆 U+1F986 Duck

![&#x1F986; Duck](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f986.png)

Maybe there are species of ducks where it’s not only the drakes who have a green head, but they do for the most common variant. I think the original proposal used a yellow rubber Duck.
## 🦌 U+1F98C Deer

![&#x1F98C; Deer](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/72x72/1f98c.png)

Except for reindeers, female deers do not have antlers.

PS: I raised almost the same [issue with Emoji One](https://github.com/Ranks/emojione/issues/325).

**Comment by Crissov** [comment]
I'm neither an artist nor a skilled user of graphics editors, but, anyway, here is what I came up with by changing colors and deleting parts:

| Emoji	| _status quo_	| default	| &#x2640;&#xFE0F;	| &#x2642;&#xFE0F;	|
|-------	|--------------	|---------	|------------------	|------------------	|
| :ox: U+1F402 Ox	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f402.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f402.svg)	| [![&#x1f402;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f402.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f402.svg)	| [![&#x1f402;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f402-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f402-2640.svg)	| [![&#x1f402;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f402-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f402-2642.svg)	|
| :cow2: U+1F404 Cow	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f404.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f404.svg)	| [![&#x1f404;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f404.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f404.svg)	| [![&#x1f404;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f404-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f404-2640.svg)	| [![&#x1f404;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f404-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f404-2642.svg)	|
| :cow: U+1F42E Cow Face	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f42e.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f42e.svg)	| [![&#x1f42e;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f42e.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f42e.svg)	| [![&#x1f42e;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f42e-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f42e-2640.svg)	| [![&#x1f42e;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f42e-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f42e-2642.svg)	|
| :ram: U+1F40F Ram	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f40f.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f40f.svg)	| [![&#x1f40f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f40f.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f40f.svg)	| [![&#x1f40f;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f40f-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f40f-2640.svg)	| [![&#x1f40f;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f40f-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f40f-2642.svg)	|
| :sheep: U+1F411 Sheep	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f411.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f411.svg)	| [![&#x1f411;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f411.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f411.svg)	| [![&#x1f411;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f411-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f411-2640.svg)	| [![&#x1f411;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f411-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f411-2642.svg)	|
| :rooster: U+1F413 Rooster	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f413.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f413.svg)	| [![&#x1f413;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f413.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f413.svg)	| [![&#x1f413;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f413-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f413-2640.svg)	| [![&#x1f413;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f413-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f413-2642.svg)	|
| :chicken: U+1F414 Chicken 	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f414.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f414.svg)	| [![&#x1f414;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f414.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f414.svg)	| [![&#x1f414;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f414-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f414-2640.svg)	| [![&#x1f414;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f414-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f414-2642.svg)	|
| :boar: U+1F417 Boar 	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f417.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f417.svg)	| [![&#x1f417;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f417.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f417.svg)	| [![&#x1f417;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f417-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f417-2640.svg)	| [![&#x1f417;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f417-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f417-2642.svg)	|
| :lion: U+1F981 Lion Face 	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f981.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f981.svg)	| [![&#x1f981;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f981.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f981.svg)	| [![&#x1f981;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f981-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f981-2640.svg)	| [![&#x1f981;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f981-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f981-2642.svg)	|
| :duck: U+1F986 Duck 	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f986.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f986.svg)	| [![&#x1f986;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f986.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f986.svg)	| [![&#x1f986;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f986-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f986-2640.svg)	| [![&#x1f986;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f986-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f986-2642.svg)	|
| :deer: U+1F98C Deer	| [![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f98c.png)](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f98c.svg)	| [![&#x1f98c;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f98c.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f98c.svg)	| [![&#x1f98c;&zwj;&#x2640;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f98c-2640.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f98c-2640.svg)	| [![&#x1f98c;&zwj;&#x2642;&#xfe0f;](https://rawgit.com/Crissov/twemoji/dimorphic-animals/2/72x72/1f98c-2642.png)](https://github.com/Crissov/twemoji/blob/dimorphic-animals/2/svg/1f98c-2642.svg)	|

**Comment by bhaggs** [comment]
I would recommend submitting this as a proposal to the Unicode Emoji Subcommittee.

**Comment by Crissov** [comment]
> It would be nice if Twemoji’s default illustration could be as generic as possible
