### ISSUE TITLE
ROASTED SWEET POTATO depicts wrong variety of potato

### ISSUE THREAD

**Issue by ohmantics** [twitter/twemoji#165]
U+1F360 originally depicted やきいも (yaki imo) in the original Japanese emoji. It should depict the Satsuma (Japanese sweet potato) variety, which has a light yellow color flesh. The emoji here depicts the [significantly less tasty] Garnet variety, which is more frequently used in North American cooking.

Put another way, the emoji depicted here would be confusing to Japanese users who have already encoded meaning in content that uses this code point.

**Comment by mbodge** [comment]
I'm having this problem as well. I need the correct potato ASAP.

**Comment by mbodge** [comment]
Any updates?

**Comment by bhaggs** [comment]
FIxed in 60607234915acbfd84bea131afb78d8032e83806
