### ISSUE TITLE
Need to add a tag 2.1.2

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [twitter/twemoji#166]
Need a tag 2.1.2 here: 

https://github.com/twitter/twemoji/releases

This is apropos https://github.com/cdnjs/cdnjs/issues/8813

**Comment by bhaggs** [comment]
Done.

**Comment by vijayaraghavanramanan** [comment]
Possible to do the same for 2.1.4? Thanks.

**Comment by WebReflection** [comment]
tagged also 2.1.5
