### ISSUE TITLE
[SUGGESTION] Using Emojis on Twitter via Desktop

### ISSUE THREAD

**Issue by rtd62** [twitter/twemoji#168]
Not sure if this applies here at all - but perhaps we could use this repo to find a way to type emojis into our tweets when we use Twitter on the desktop? 
Similar to how we type emojis using Slack's or Github's library i.e `:bear:`

**Comment by bhaggs** [comment]
Definitely a useful idea, but likely out of the scope of this project as it is intended primarily for the means of rendering emoji as opposed to selecting emoji for insertion.
