### ISSUE TITLE
Question about twemoji.parse(document.body, emojiSettings)

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [twitter/twemoji#170]
A simple question. 

For non-trivial emojis such as the rainbow flag, do I need something more than 

`twemoji.parse(document.body, emojiSettings)`

in javascript?

I am not able to get it. 

Here's a demo: http://codepen.io/anon/pen/VjoBLq

**Comment by vijayaraghavanramanan** [comment]
Possibly a bug in cdnjs: https://github.com/cdnjs/cdnjs/issues/8858

**Comment by WebReflection** [comment]
`//twemoji.maxcdn.com/2/twemoji.min.js` is what you should probably include by default in your pages.
