### ISSUE TITLE
Why are JS files ignored in the Bower package?

### ISSUE THREAD

**Issue by Rudloff** [twitter/twemoji#171]
Hello,

Since https://github.com/twitter/twemoji/commit/590d7a326861867964a4c1a6f1d44505fffa302b, twemoji.js is excluded from the Bower package. As I use Bower in order to easily get JS libraries, this breaks my workflow.
Is there any particular reason these files are ignored?

**Comment by WebReflection** [comment]
files seem to be there, which change broke your build? I might double check later on (this evening)

Apologies for any inconvenience

**Comment by Rudloff** [comment]
It seems the files were meant to be ignored since 9edd9dd4a8c54533678cb04b658c305c2d1ccfaf but the syntax was wrong so 590d7a326861867964a4c1a6f1d44505fffa302b fixed it.
Having these files in the `ignore` property means Bower removes them after install (but it still downloads them).
The same thing applies to the images (16x16, etc) folders.

**Comment by WebReflection** [comment]
would ignoring everything but version 2 be OK? the main file is version 2 and bringing in all V1 assets is pointless, right?

**Comment by Rudloff** [comment]
Yes, it would be OK for me.

**Comment by WebReflection** [comment]
I will try to make it work this evening (I don't use/know bower that much so a PR would also be welcome)
