### ISSUE TITLE
THE TEA EMOJI IS GREEN

### ISSUE THREAD

**Issue by FishyFing** [twitter/twemoji#174]
🍵  <- It should be brown. Maybe add a :green_tea: emoji?

**Comment by jnievelt** [comment]
Why should it be brown?

This is U+1F375, "TEACUP WITHOUT HANDLE", the only emoji which mentions tea, which is generally represented as green tea.  U+2615, "HOT BEVERAGE", is brown: ☕

For reference: http://unicode.org/emoji/charts/full-emoji-list.html

**Comment by FishyFing** [comment]
@jnievelt because tea is generally seen as brown, and that is green tea.

also, most services dont include hot beverage in their list.

**Comment by bhaggs** [comment]
The consensus around 'teacup without handle' from Twemoji and other emoji providers is for the tea to be green, as can be seen on [Emojipedia](http://emojipedia.org/teacup-without-handle/).
