### ISSUE TITLE
Clean up folders, use Master branch

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#175]
Twemoji is currently defaulting to the `gh-pages` branch which is unusual (and unnecessary).

The subfolders in the root directory (/svg, /72x72 etc.) don’t link to the most recent version /2, but to the old /1.

**Comment by WebReflection** [comment]
The unusual and unnecessary branch is aligned 1:1 with MaxCDN and that's how it's been configured since the beginning.

**Comment by Crissov** [comment]
The folder issue is actually more severe than the branch issue.

**Comment by WebReflection** [comment]
There is **no issue**. The library uses MaxCDN, which reflect gh-pages branch, to serve to million of sites already these assets.

If you have real issues with the library or the way MaxCDN configured the CDN mirror, please file a bug, otherwise it's a won't fix.

Regards
