### ISSUE TITLE
Twemoji 2 cheat sheet

### ISSUE THREAD

**Issue by tresdin** [twitter/twemoji#177]
How can I get the complete list of supported Unicode emoji in Twemoji 2?

**Comment by autopulated** [comment]
It isn't linked from the webpage, but there's a preview for version 2 hosted on github.io similarly to the version 1 preview:

http://twitter.github.io/twemoji/2/test/preview-svg.html

**Comment by tresdin** [comment]
Thank you @autopulated .

**Comment by WebReflection** [comment]
It's actually in the index file:
http://twitter.github.io/twemoji/

But I agree maybe we should consider improving visibility of such page.

**Comment by sagive** [comment]
Can you guys copy & paste that? isn't that the definition of a cheat sheet?! 😂
