### ISSUE TITLE
MaxCDN version different

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [twitter/twemoji#178]
I compared the files at MaxCDN and Github and seems the former is not the same as 2.2

Does the MaxCDN cache need to be invalidated?

**Comment by WebReflection** [comment]
usually it does it automatically in max 30 days. If you ctrl+shift+R/F5 is it still the same?

**Comment by vijayaraghavanramanan** [comment]
Yes, tried refresh that way, no browser cache etc and seems to respond with the older version.

**Comment by WebReflection** [comment]
that's odd, will check/try to purge later on

**Comment by WebReflection** [comment]
can you please let me know if anything changed whatsoever now? thanks

**Comment by vijayaraghavanramanan** [comment]
Yes, now it's the latest js file on the CDN.

**Comment by WebReflection** [comment]
apologies for the inconvenience, I'll remember to manually purge edge cache next time.
