### ISSUE TITLE
Emoji ending in 20E3 have incomplete first byte.

### ISSUE THREAD

**Issue by calebd** [twitter/twemoji#181]
The unicode values ending in `20E3` appear in twemoji as `39-20E3` for 9️⃣ for example. The first byte should be complete: `0039-20E3` for consistency.

**Comment by WebReflection** [comment]
> appear in twemoji as ...

in the documentation? in the assets files? in the JS library? any code example? what would be solved?

**Comment by calebd** [comment]
Ah sorry. The asset names (all .ai, .svg, and .png files) and any code that references them all have incomplete first bytes. This only affects the 10 emoji ending in `20e3`.

**Comment by WebReflection** [comment]
> The asset names (all .ai, .svg, and .png files) and any code that references them all have incomplete first bytes.

that makes them all consistent, right?

what are you trying to solve? it's easier for us to ignore prefixed zeroes, as these have effectively no meaning whatsoever for our needs.
