### ISSUE TITLE
Why the emoji look not like what i see on IOS?

### ISSUE THREAD

**Issue by DanielWLam** [twitter/twemoji#185]
I am just wondering why these emoji look more like the 'Android Emoji' not the 'IOS emoji'. Is there any solution that i can get the ios emoji on the browser? please help.

**Comment by vijayaraghavanramanan** [comment]
All emoji creators (if that's the right word) have their own way of making emoji within Unicode standards. 

So may want to check how emoji render differently depending on who the creator is here: 

http://emojipedia.org/rainbow-flag/

Wordpress uses Twemoji and does feature detection for native emoji and uses Twemoji if browser doesn't support emoji for example. You might want to look at Wordpress' code.

**Comment by vijayaraghavanramanan** [comment]
Btw, IMO Twemoji emoji are closer to iOS emoji than Android emoji.

**Comment by DanielWLam** [comment]
So if there anyway i can use apple emoji rather then others?

**Comment by vijayaraghavanramanan** [comment]
You can't use Apple's emoji for every browser on all OS since Apple may have copyrighted that. Twitter on the other hand allows you to use its emoji freely anywhere. Personally I like the look of Twemoji more than others.

**Comment by DanielWLam** [comment]
Alright then, the copyright stuff is what i am worry about...Thanks!

**Comment by vijayaraghavanramanan** [comment]
You can look at how Wordpress does feature detection and will load iOS emoji on iOS devices if it has full support or else use Twemoji here: 

https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=emoji
