### ISSUE TITLE
Switzerland flag in wrong proportions

### ISSUE THREAD

**Issue by wladston** [twitter/twemoji#191]
The Switzerland flag is square, but Twemoji renders it rectangular. I've fixed it locally, but I don't know how to make a pull request for it:

[1f1e8-1f1ed.pdf](https://github.com/twitter/twemoji/files/597542/1f1e8-1f1ed.pdf)

**Comment by wladston** [comment]
By the way, Unicode recommends keeping flags' proportions: http://www.unicode.org/reports/tr51/#Flags

**Comment by bhaggs** [comment]
Unicode suggests using uniform proportions across all flags to avoid a 'ransom note' style presentation. We've opted to go that route similar to other emoji sets.

http://www.unicode.org/reports/tr51/#Flag_Presentation

**Comment by wladston** [comment]
Yes, I agree that is the best decision. Thanks for your answer :)

For people who want the square Swiss flag, let's hope a google search can land then here where they can download the modified flag.

**Comment by wladston** [comment]
Just as a reference for future readers, Twemoji fixed this issue in December 2017 with version 2.4: https://emojipedia.org/twitter/twemoji-2.4/flag-for-switzerland/
