### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by xoudini** [twitter/twemoji#193]
This is more of an announcement than anything else, and figured it could fit here.

To the point: I published [an iOS framework](https://github.com/xoudini/emojica) that makes it possible to use Twemoji in place of the standard emoji (in an application). If you'd like to add the URL for the framework to [Community Projects](https://github.com/twitter/twemoji/blob/gh-pages/README.md#community-projects) I'd appreciate it very much.

No other actions needed.

**Comment by WebReflection** [comment]
Nice project! You can create a PR that adds that change, summarizing at your best the project goal.

That description would be most likely better than mine, and it will better represent the project intent.

Would that work?

**Comment by xoudini** [comment]
Thank you!

Yes, that would absolutely work, I've submitted [#194](https://github.com/twitter/twemoji/pull/194).
