### ISSUE TITLE
How to import twemoji in Angular2 program?

### ISSUE THREAD

**Issue by xifengxx** [twitter/twemoji#196]
I use angular2 in my program, and import twemoji file in index.html, like:
> <script src="//cdn.bootcss.com/twemoji/2.1.0/twemoji.min.js"></script>

but it doesn't work in it.
for example, in my emoji.directive.ts file:
`import { Directive, ElementRef, Renderer, ViewChild, AfterViewInit } from '@angular/core';
import { EmojiService } from "./emoji.service";
@Directive({ selector: '[twEmoji]' })
export class twEmojiDirective {
	constructor(el: ElementRef, renderer: Renderer) {
		let iattrs = el.nativeElement.getAttribute("twEmoji");
		let content = twemoji.parse(iattrs);
		// renderer.setElementStyle(el.nativeElement, 'backgroundColor', 'yellow');
		setTimeout(function() {
			el.nativeElement.html(content);
		})
	}
}`
when compiled, the error is:"error TS2304: Cannot find name 'twemoji'."

how should I do for it?

**Comment by xifengxx** [comment]
in angular1, I use it successfully

**Comment by WebReflection** [comment]
maybe you want to use the `npm` module instead?

**Comment by xifengxx** [comment]
@WebReflection Thanks for your reply!
I also used npm to install twemoji module in my program.
I don't know how to use it in .ts file, when I use the method "twemoji.parse", it said "can't find name 'twemoji'"

**Comment by WebReflection** [comment]
feels like you have problem configuring TypeScript or Angular 2 and I don't think this is the place to solve such problem (or at least, I have no idea how to, I don't TypeScript and I don't Angular).

If you find a way and you'd like to help with a little "How To" PR for the README, that'd be surely more than welcome.

Sorry I couldn't help much.
Regards
