### ISSUE TITLE
Request: :3 smile

### ISSUE THREAD

**Issue by dvorapa** [twitter/twemoji#199]
This is really old and popular one, which users miss in my apps. I fixed it locally, but 

Current Facebook form (worse):
![](https://www.facebook.com/images/emoji.php/v7/e91/1/24/FACE_WITH_COLON_THREE.png)

Former Facebook form (better):
![](http://4.bp.blogspot.com/-i3GSy3WpYfs/Tv9QrweHOVI/AAAAAAAAAlQ/YBbHR7CdQb4/s400/curly%2Blips%2Bemoticon.png)

Usually means something like:
<img src="http://sd.keepcalm-o-matic.co.uk/i/mmm-mmm-mmm-mmm-donuts.png" width="150" height="175">

**Comment by WebReflection** [comment]
which unicode standard code is used for this?

**Comment by dvorapa** [comment]
@WebReflection I'm currently trying to find some Unicode reference, but unfortuately without success.

**Comment by WebReflection** [comment]
beside some quirk code manipulated for Apple legacy reasons, this project adhere to Unicode standard.

We don't have FB or BB Forum emoticons here, we have emoji. If these are not defined by the standard, we won't block any random code that might collide in the future with a different standard symbol.

It's a pity because I like your work, but if there's no official code for it, I'm afraid it won't happen.

**Comment by dvorapa** [comment]
@WebReflection I've found some webapps using U+1F924 for :3 emoticon, but I think these two should be separate. Maybe this is missing in Unicode at all

**Comment by dvorapa** [comment]
@WebReflection I'll try to fill in this request to Unicode team (after googling how to do it first)

**Comment by WebReflection** [comment]
the ml is unicode@unicode.org, good luck :-)

**Comment by WebReflection** [comment]
I'll flag it as invalid until we have a code point to use

**Comment by dvorapa** [comment]
I sent an email with proposal, but that email address is not working (none of Unicode email address is working at the moment). Emails are returned back with server error :/ unlucky today

**Comment by Crissov** [comment]
The procedure for proposing an emoji is described at [Unicode’s emoji pages](http://unicode.org/emoji/selection.html).

[Drooling Face &#x1f924;](http://emojipedia.org/drooling-face/) may be appropriate, although it’s not the meaning I would have associated with `:3` intuitively, and I would have expected a preference of either `:)'` or `:)~` for it instead. The [English Wikipedia’s list of emoticons](https://en.wikipedia.org/wiki/List_of_emoticons#Western) shows it as a variant of smiling or being happy and hence of ☺️🙂😊😀😁, but having cleaned up this article in the past I know that it’s not saying much.

**Comment by dvorapa** [comment]
@Crissov I know, you can see my proposal according to [Unicode’s emoji pages](http://unicode.org/emoji/selection.html) I tried to send to both unicode@unicode.org and docsubmit@unicode.org:

[Proposal for CURLY LIPS Emoji.pdf](https://github.com/twitter/twemoji/files/727077/Proposal.for.CURLY.LIPS.Emoji.pdf)

**Comment by Crissov** [comment]
unicode@ is a mailing list for public discussion that you need to be subscribed to – don’t send it there. [docsubmit@](http://www.unicode.org/pending/docsubmit.html) should work, assuming you followed the `Subject:` header convention: “UTC Document Submission: Proposal for Curly Lips emoji”.

Your PDF is missing some inline emojis.

**Comment by dvorapa** [comment]
@Crissov I know, I tried docsubmit first, then many more, but none of them is working. By now I communicate with Unicode staff by contact form trying to find some alternative contact solution.

**Comment by Crissov** [comment]
Okay. Note that UTC150 is this week, so they may be busy with that.

**Comment by WebReflection** [comment]
@Crissov not sure what your analysis has to do with code points. Are you mixing up emoticons with emoji or I am missing some context?

I have suggested a Mailing list, not sure what's that down vote neither.
There is indeed where I've been interacting for years now with the Unicode standard people.

I'll try to point this bug in there too, but suggesting not to subscribe? why is that? It's a welcoming ML.

Regards

**Comment by WebReflection** [comment]
Let's see how this goes.

<img width="477" alt="unicode" src="https://cloud.githubusercontent.com/assets/85749/22256918/1d0ac620-e254-11e6-9034-c762b8d3729f.png">

**Comment by dvorapa** [comment]
Finally communication through website contact form lead to finding the issue and fixing it on Unicode side and I sent my proposal once more (for sure). @WebReflection thank you for your quick action

**Comment by Crissov** [comment]
@WebReflection The thumb-down was because it sounded like you were suggesting to propose the emoji on the mailing list – that’ll just lead to pointers to /emoji/selection.html or /pending/proposals.html.

**Comment by WebReflection** [comment]
@dvorapa it looks like many raised the name issue, which is not aligned with what the rest of the world thinks about `:3` meaning.

Just as heads up

**Comment by dvorapa** [comment]
@WebReflection :+1:

**Comment by Crissov** [comment]
JFTR, in [Skype](https://github.com/Crissov/unicode-proposals/issues/253), typing a `:3` emoticon results in a sitting full-body kitty cat graphic being displayed, i.e. same result as with `(cat)`. 

[![Skype Cat 🐈](https://az705183.vo.msecnd.net/onlinesupportmedia/onlinesupport/media/skype/screenshots/fa12330/emoticons/cat_80_anim_gif.gif)](https://support.skype.com/en/faq/FA12330/what-is-the-full-list-of-emoticons "Skype emoticon reference")

[Google products](https://github.com/Crissov/unicode-proposals/issues/252) (Gmail, Hangouts, Chat) convert `:3` (as well as `:X)`, `(=^..^=)`,  `(=^.^=)` and `=^_^=`) to Smiling Cat Face :smile_cat: nowadays. Two of my sources for [Facebook emoticons](https://github.com/Crissov/unicode-proposals/issues/254) &ndash; would be glad to find an official reference &ndash; also call it &ldquo;Kitty&rdquo;, hence probably 🐱, [just one](http://www.jamfoo.com/fb-emoticons/) has it listed as &ldquo;Curly lips emoticon&rdquo;.

No major implementation seems to support the extended variant with hyphen nose, `:-3`.

**Comment by dvorapa** [comment]
I don't use Google products but it seems there is a conflict between Google+Skype's cat and Facebook's curly lips/enamored (to me two different emoticons). Recently I've got an email from Unicode, that proposed emoticon was merged into a bigger group of emoticons Unicode is working on and the whole group will be released together once it will be finished as a whole.

**Comment by dvorapa** [comment]
Finally it looks like Unicode in Emoji v11 (7th February) finally added the curly face emoji as "woozy face" with the following meaning:
- tired
- emotional
- drunk
So this could finally be solved

**Comment by jdecked** [comment]
"Woozy face" likely isn't going to be rendered as something closer to :-3, but the beauty of emoji is that you can use them in any way you prefer.
