### ISSUE TITLE
OTF (OpenType Format) / TTF (TrueType Format)

### ISSUE THREAD

**Issue by bhdicaire** [twitter/twemoji#20]
Do you plan to provide a font?

**Comment by nicholasodo** [comment]
Is it still out of the question to create a ttf? Both Apple and Google do this for their emojis and it would be pretty handy to swap out my NotoColorEmoji.ttf with Twitter's.

**Comment by wp9015362** [comment]
@WebReflection :

Can you please reopen this issue?

A font would be needed to use the Twemojis as native system Emojis in Android for example.

> @nicholasodo wrote:
> 
> Is it still out of the question to create a ttf?
> Both Apple and Google do this for their emojis and it would be
> pretty handy to swap out my NotoColorEmoji.ttf with Twitter's.

It seems like someone over at the XDA Developers Forum managed to make an Emoji system font for Android using Twemojis, see:

http://forum.xda-developers.com/showpost.php?p=58610497&postcount=94

Regards

**Comment by WebReflection** [comment]
I don't know if there are resources allocated for this.

If someone will do this, ever, this won't be a bug anyway and it will be announced. No need to keep this, as bug, open, since the current status is a won't do/fix anyway.

**Comment by wp9015362** [comment]
Looks like Google is working on it, see:

https://github.com/googlei18n/noto-emoji/issues/9

:wink:

Regards

**Comment by Crissov** [comment]
JFTR: https://github.com/eosrei/twemoji-color-font

**Comment by mavit** [comment]
I thought I’d mention that I’ve had some success using the tooling that comes with Google’s Noto Emoji to build a Twemoji TTF and package it as an RPM for Linux.  It’s not an elegant approach, but it seems to work.

https://pagure.io/twitter-twemoji-fonts/tree/master

**Comment by phseiff** [comment]
It's not an OpenType-SVG file, admittedly, but rather COLR/CPCAL, but if your only concern is having a `.ttf`-file that works on all browsers, you might also be able to use [this](https://github.com/mozilla/twemoji-colr) solution (easier to download from [here](http://mirrors.ctan.org/fonts/twemoji-colr/TwemojiMozilla.ttf), though).

According to https://www.colorfonts.wtf/, the COLR/CPCAL is already supported on Chromium & Co.:

> ![image](https://user-images.githubusercontent.com/31518703/122293170-0a4d1580-cef7-11eb-940d-b58ed4789aa1.png)

**Comment by AndroidDeveloperLB** [comment]
Can you please re-open this?
 
I tried the one of Mozilla, but it hasn't been updated for years, and it also has issues [with digits](https://github.com/mozilla/twemoji-colr/issues/56)...

How can I get the latest, yet small version of this font, that handles only emojis? I like it that it's so tiny...
