### ISSUE TITLE
404 on 1f642.png

### ISSUE THREAD

**Issue by jameson5555** [twitter/twemoji#200]
For some reason, I'm getting a 404 error for that emoji, which appears to be a standard smiley. I'm using the latest version downloaded from this repo.

**Comment by WebReflection** [comment]
https://twemoji.maxcdn.com/2/72x72/1f642.png
https://twemoji.maxcdn.com/2/svg/1f642.svg
I see them both.

**Comment by jameson5555** [comment]
Sorry, I should have provided the image URL. The path I'm getting a 404 on this path: https://twemoji.maxcdn.com/72x72/1f642.png. Looks like there is a /2/ in your examples. Maybe I'm doing something wrong? All the other paths are getting created without the /2/ in my setup and they're working.

**Comment by WebReflection** [comment]
you probably didn't update the url?

**Comment by WebReflection** [comment]
https://github.com/twitter/twemoji#breaking-changes-in-v2

**Comment by jameson5555** [comment]
Ah, that was it - I just needed to specify the folder to get the new assets. Thanks!!
