### ISSUE TITLE
Can't use NPM/Yarn for web site integration

### ISSUE THREAD

**Issue by Kal74** [twitter/twemoji#201]
The npm package (https://www.npmjs.com/package/twemoji) is cleaned and contain only the JS module.
Would it be possible to keep the other versions (twemoji.js / twemoji.amd.js) like in the bower package?

Thanks.

**Comment by WebReflection** [comment]
the bower has them all already

**Comment by Kal74** [comment]
Yes, I saw that, but we decided to replace bower by yarn especially for 2 features:
the lock file and the download cache (realy safer and faster for CI deployments). 

I'm probably not the only one who use the NPM packages for web, so it could be useful.
Regards,

**Comment by WebReflection** [comment]
My bad, I've missed completely that "_like_" in the sentence and thought you wanted them in the bower package. There is another issue with one asset, once resolved will put other entries in the package.

**Comment by Kal74** [comment]
Thanks.

**Comment by WebReflection** [comment]
2.2.4 should have all the js files included
