### ISSUE TITLE
hocho emoji isn't looks like japanese hocho

### ISSUE THREAD

**Issue by katabame** [twitter/twemoji#204]
I know there are a lot of different kinds of hocho.
but most japanese hocho's lower side is not curved.

straight lower side(but isn't completely straighted) and curve upper side is more like real japanese hocho I think.

here is google emoji for good sample:
![](http://emojipedia-us.s3.amazonaws.com/cache/17/b0/17b09ad7c19dc5e8c04e941d97fbfe1a.png)

and another sample photo:
![](http://www.ehamono.com/houtyou/mizuno/img/daidokoro180ao-1l.jpg)

**Comment by Liggliluff** [comment]
The Emoji name for this is now "Kitchen Knife", in addition to the Unicode name "Hocho".
Google has changed it's design in Android O:
![image](https://user-images.githubusercontent.com/822352/27516527-09739cd8-59bc-11e7-99f1-466d80e42e49.png)

**Comment by jdecked** [comment]
As mentioned above, [the CLDR short name for this in English](https://unicode.org/emoji/charts/full-emoji-list.html#1f52a) is "kitchen knife", not specifically "hocho".
