### ISSUE TITLE
Emojis don't display on Google Chrome in Windows

### ISSUE THREAD

**Issue by OmarZV** [twitter/twemoji#205]
Hey guys,

Thank you so much for this github - its amazing. I ran into an issue though my emojis are displaying perfectly on my apple computer using chrome. But, on my windows 7 using chrome it comes as black and white or sometimes just an empty box was wondering if anyone has a solution for this. Thank you so much!
![emojiwindows7](https://cloud.githubusercontent.com/assets/16312270/23512816/f43775f6-ff2f-11e6-82df-04f5c2985430.PNG)

**Comment by WebReflection** [comment]
what do you see [here](http://twitter.github.io/twemoji/2/test/preview.html)?

**Comment by OmarZV** [comment]
Here they all look perfect :) how can I do this on my end?

**Comment by WebReflection** [comment]
by `&#127880` you meant `&#1F388;`, right ? with a semicolon after and a number that is HEX one, right?

**Comment by WebReflection** [comment]
or better .. check this source code out:
https://github.com/twitter/twemoji/blob/gh-pages/2/test/preview.html

it's the page you say that it looks perfect.

**Comment by OmarZV** [comment]
Thank you so much mate!! This was amazing :smile:

**Comment by WebReflection** [comment]
glad to help, too bad GitHub doesn't use twemoji 😉 

![screenshot from 2017-03-03 01-09-00](https://cloud.githubusercontent.com/assets/85749/23534196/1bad5136-ffae-11e6-83dd-c6ac8ea873fa.png)

**Comment by DeepakM02** [comment]
How did you solve emojis issue on windows ?
