### ISSUE TITLE
Please add missing face emoji

### ISSUE THREAD

**Issue by martymcwizard** [twitter/twemoji#210]
When composing a tweet using Chrome on MacOS I can see the following emoji  which are not included in the repository:  1f643-44, 1f910-17, 2639, 1f920, 922, 923, 925, 927.  Are these available as .SVG?

**Comment by Crissov** [comment]
![](https://rawgit.com/twitter/twemoji/gh-pages/2/72x72/1f3c2.png)

**Comment by WebReflection** [comment]
> The legacy folder structure of this repository is not very helpful.

But it's legacy and we don't want to break that.

**Comment by WebReflection** [comment]
https://github.com/twitter/twemoji#breaking-changes-in-v2
