### ISSUE TITLE
emojies support

### ISSUE THREAD

**Issue by gaut7** [twitter/twemoji#212]
![notsupportedemojies](https://cloud.githubusercontent.com/assets/7018940/24643582/890b9f02-192c-11e7-8320-b0f102f3ce96.png)
![original](https://cloud.githubusercontent.com/assets/7018940/24643584/895c3a16-192c-11e7-878a-7b6a26ab7a91.PNG)

I am working on a project where I need emoji support. However I am facing some problem as many of emojies are not supported. I got those emojies as input from iPhone device. I have added two images where "original.png" is the actual emoji and second pic ("notsupportedemojies.png") contain emoji after parsing using twemoji. 
   Any pointers or help regarding it will be appreciated.

**Comment by WebReflection** [comment]
I'm sure you're using the version 2 of the emoji library, which points at version 2 of the emoij, right?

That would deliver 2422 emoji, including those shown in this post:
http://twitter.github.io/twemoji/2/test/preview.html

**Comment by gaut7** [comment]
Yes, I am using version 2 emoji library only. even I tried to parse one of Unicode which is "\ue04f" but here also I didn't get its correct emoji.

<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Demo</title>
   <script type="text/javascript" src="js/vendor/jquery.js"></script>
   <script type="text/javascript" src="js/vendor/jquery.emoji.js"></script>
   <script src="//twemoji.maxcdn.com/2/twemoji.min.js?2.4"></script> 
</head>
<body>

<script>
var div = document.createElement('div');
div.textContent = 'I \ue04f emoji!';
document.body.appendChild(div);
 twemoji.parse(document.body);
var img = div.querySelector('img');
</script>
</body>
</html>

**Comment by Crissov** [comment]
U+E04F is a PUA character, not a proper Unicode emoji. Some other libraries support the lookup of such legacy codes, e.g. [iamcal/emoji-data](/iamcal/emoji-data).
