### ISSUE TITLE
Add Slightly (Smil|Frown)ing Face PNGs

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#213]
In https://github.com/twitter/twemoji/commit/d0e45fee1b7d2b5828de9d4e5c01acb84ef4a116 and https://github.com/twitter/twemoji/commit/b3d9b74ced05b6ec93b73c7aa1214f057212450a the AI and SVG files for Slightly Frowning/Smiling Face emojis U+1F641/2 have been added to Twemoji v1, but there are still no PNGs of them in the repo.

**Comment by bhaggs** [comment]
v1 of Twemoji is deprecated. Pleaes referring to v2 for current assets.

**Comment by Crissov** [comment]
I know that it's deprecated, but some people are still using it, maybe just for comparison, and it makes no sense that the SVG files are available but the PNG files are not.
