### ISSUE TITLE
U.S. flag

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [twitter/twemoji#214]
The U.S. flag is supposed to have 50 stars according to this: 

https://en.wikipedia.org/wiki/Flag_of_the_United_States

but Twemoji https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f1fa-1f1f8.svg has only 18!

**Comment by Crissov** [comment]
It's one of these cases where less accuracy in lower resolutions improves usability. That being said, reduced accuracy makes sense in fixed-size PNGs, less so for scalable vector graphics. The designers *could* use Media Queries within CSS within SVG to omit some details, like stars, depending on actual resolution.

**Comment by bhaggs** [comment]
We take a fair amount of liberties in our creation of each flag to ensure better legibility as @Crissov has mentioned.

**Comment by vijayaraghavanramanan** [comment]
Don't think it should affect quality much. This page has the images of the flag from others (Facebook, Mozilla etc) and they seem to be fine: 

http://emojipedia.org/flag-for-united-states/

**Comment by Crissov** [comment]
Emojipedia shows rather large images. Emojis are mostly used at text size, i.e. around 16px.

Google Noto and Emojione do not show 50 stars either.

- https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f1fa_1f1f8.svg
- https://github.com/Ranks/emojione/blob/master/assets/svg/1f1fa-1f1f8.svg

**Comment by vijayaraghavanramanan** [comment]
That emojione is a round emoji, so! 

For svg, it isn't that problematic. The UN flag has a large size in Twemoji itself. 

I can easily resize the Facebook emoji to 16px and the file size also falls. Plus the version 2 emoji is 72x72 minimum. 

The argument of taking liberty is fine but I don't think resolution or the size is any constraint here.

**Comment by WebReflection** [comment]
> the version 2 emoji is 72x72 minimum

That's to simplify maintenance and preserve good quality on 3X+ HiDPI screens without needing to use SVG which are overall heavier, specially on Mobile.

> The argument of taking liberty is fine

Good, and since this has been closed already, I hope we can all move on.
