### ISSUE TITLE
Is there a machine readable list of emojis with name and keywords?

### ISSUE THREAD

**Issue by JustinDrake** [twitter/twemoji#217]
I am looking to build a list of emojis from the [official list on unicode.org](http://www.unicode.org/emoji/charts/emoji-list.html). The problem is that this is an HTML which is not easily machine readable.

Is there an equivalent list (e.g. in XML or JSON) which contains names and keywords?

**Comment by WebReflection** [comment]
Something like this?
http://www.unicode.org/Public/emoji/5.0/emoji-test.txt

**Comment by marianoguerra** [comment]
I found this: https://github.com/iamcal/emoji-data there are two json files at the root

**Comment by denniskim** [comment]
Check out https://github.com/milesj/emojibase

**Comment by supertiger1234** [comment]
they are missing a lot of twemojis tho
