### ISSUE TITLE
Return the emoji name

### ISSUE THREAD

**Issue by armandofreire** [twitter/twemoji#222]
Hello guys.

When I parse a string using twemoji it returns a string with the `<img />` emoji, like this:

```
twemoji.parse('I \u2764\uFE0F emoji!');

"I <img class="emoji" draggable="false" alt="❤️" src="https://twemoji.maxcdn.com/2/72x72/2764.png"> emoji!"
```

Is there any way to return the emoji name as specified in [unicode.org](http://unicode.org/emoji/charts/full-emoji-list.html#2764)? For the example above, something like "red_heart" on alt or even a function to return it?

Thanks!

**Comment by WebReflection** [comment]
Nope, unicode to names would be already a huge library a part that would increase consistently the weight of this one.

There are many alternative projects specialized in just that part, here there's just the first example I could find in npm.
https://github.com/IonicaBizau/emoji-unicode-map#readme
