### ISSUE TITLE
The flag for Nepal incorrectly has a white background.

### ISSUE THREAD

**Issue by Starmann** [twitter/twemoji#223]
The flag of Nepal is famously pendant shaped. Instructions for constructing it Mathematically are in Nepal's [1990 constitution](http://www.servat.unibe.ch/icl/np01000_.html). Twemoji, however, pastes it onto a white background. This can be easily fixed by simply removing the background from the source file.

**Comment by bhaggs** [comment]
Refer to comments on #225 .
