### ISSUE TITLE
how can i make \ud83d\ude09 to become img?

### ISSUE THREAD

**Issue by hahazexia** [twitter/twemoji#224]
\ud83d\ude07\ud83d\ude09

then i call the twemoji.convert.toCodePoint(), it return like this:

5c-75-64-38-33-64-5c-75-64-65-30-37-5c-75-64-38-33-64-5c-75-64-65-30-39

what to do to make this right?

**Comment by WebReflection** [comment]
`twemoji.parse('\ud83d\ude07\ud83d\ude09')` ?

**Comment by hahazexia** [comment]
but in VUE this is not working

**Comment by WebReflection** [comment]
not enough details to help in any way, sorry.

Please provide **as many details, code, examples, as possible** or I cannot help.
