### ISSUE TITLE
twemoji.parse() just not working

### ISSUE THREAD

**Issue by hahazexia** [twitter/twemoji#226]
why?
i don't understand

let name = twemoji.parse('iiffdgfgfg\ud83d\ude07\ud83d\ude09dfgdfg');
 //解析字符串，成功，succeed
let name1 = twemoji.parse(String(response.body.ReturnData[i].nickname));
//解析接口返的数据，失败，failed，why??? 

response.body.ReturnData[i].nickname === 'iiffdgfgfg\ud83d\ude07\ud83d\ude09dfgdfg'

**Comment by WebReflection** [comment]
it's simple, the last comparison is false, otherwise it would return the same result since twemoji.parse with string is pure: same input, same output.

As summary, you are not passing twice the same string, something is different with the nickname.
