### ISSUE TITLE
'👁' fails to parse

### ISSUE THREAD

**Issue by suprMax** [twitter/twemoji#230]
It looks like some characters fail to get matched by the parser. Perhaps there is some issue with the regexp. assuming node CLI and `t = require('./twemoji.npm')`

```
> t.parse('👁')
'👁'
> t.test('👁')
false
> t.convert.toCodePoint('👁')
'1f441'
> UTF16toJSON('👁')
'\\ud83d\\udc41'
```

I checked and `\\ud83d\\udc41` is within the regex, but somehow doesn't get to be picked up?

This sequence of characters glitches out: '👁🖕🏿👍🏽👨🏿🚀👶🏿'

```
> t.parse('👁🖕🏿👍🏽👨🏿🚀👶🏿')
'👁🖕🏿<img class="emoji" draggable="false" alt="👍" src="//twemoji.maxcdn.com/36x36/1f44d.png">🏽<img class="emoji" draggable="false" alt="👨" src="//twemoji.maxcdn.com/36x36/1f468.png">🏿<img class="emoji" draggable="false" alt="🚀" src="//twemoji.maxcdn.com/36x36/1f680.png"><img class="emoji" draggable="false" alt="👶" src="//twemoji.maxcdn.com/36x36/1f476.png">🏿'
>
```

This is tested with latest master. Any ideas how to fix?

**Comment by WebReflection** [comment]
I think these are two different bugs, if any, am I correct?

> I checked and \\ud83d\\udc41 is within the regex, but somehow doesn't get to be picked up?

if there's no asset for it, it's possible the result is expected

> This sequence of characters glitches out: ':eye:🖕🏿👍🏽👨🏿:rocket:👶🏿'

it looks fine to me

'👁🖕🏿
<img class="emoji" draggable="false" alt="👍" src="//twemoji.maxcdn.com/36x36/1f44d.png">
🏽
<img class="emoji" draggable="false" alt="👨" src="//twemoji.maxcdn.com/36x36/1f468.png">
🏿
<img class="emoji" draggable="false" alt="🚀" src="//twemoji.maxcdn.com/36x36/1f680.png">
<img class="emoji" draggable="false" alt="👶" src="//twemoji.maxcdn.com/36x36/1f476.png">
🏿'


Are you using V2/latest assets? Which version of twemoji are you using? 

Please provide more information, thanks.

**Comment by suprMax** [comment]
Ah indeed there are no assets for these `👁🖕🏿`. I was trying to make it work with images from emojione and made a mistake somewhere with generating the regex.

My bad, will close this.
