### ISSUE TITLE
How do you make the PNG folders? (72x72, 36x36, 16x16)

### ISSUE THREAD

**Issue by 01AutoMonkey** [twitter/twemoji#231]
How can I gain insight into how you generate the 72x72, 36x36, and 16x16 folders? E.g. from what source do you get the twitter emoji graphics? How do you decide on/generate the file names? Where is the code that converts the source graphics to the png graphics? Or are the folders just a copy/paste from somewhere? Etc.

I'm asking because I'm wondering how difficult it would be to switch out the twitter emojis with [Noto Color Emoji](https://github.com/googlei18n/noto-emoji/) (Google/Android).

**Edit**

On closer inspection Noto Color Emoji also has a PNG folder with the same string names, so it should be rather easy: <https://github.com/googlei18n/noto-emoji/tree/master/png/128>

**Comment by WebReflection** [comment]
the folder with original assets is here:
https://github.com/twitter/twemoji/tree/gh-pages/2

you can find the 72x72 PNGs folder there and also the SVG one.

The way I was creating SVGs from AI files is through this file
https://github.com/twitter/twemoji/blob/gh-pages/svg.sh

within the folder `./2/` and on GNOME / Linux via Inkscape

**However** latest assets are directly provided by Twitter so AFAIK there is no official way in here to automatically generate those files 'cause those are probably out directly from AI.

**Comment by 01AutoMonkey** [comment]
Too switch out Twitter Emoji for Noto Emoji all one has to do is:

```js
var to_noto = true;
if (!to_noto) {
  twemoji.parse(document.body);
} else {
  twemoji.convert.toCodePoint = function (unicodeSurrogates, sep) {
    var
      r = [],
      c = 0,
      p = 0,
      i = 0;
    while (i < unicodeSurrogates.length) {
      c = unicodeSurrogates.charCodeAt(i++);
      if (p) {
        r.push((0x10000 + ((p - 0xD800) << 10) + (c - 0xDC00)).toString(16));
        p = 0;
      } else if (0xD800 <= c && c <= 0xDBFF) {
        p = c;
      } else {
        r.push(c.toString(16));
      }
    }
    return r.join(sep || '_');
  }
  twemoji.parse(document.body, {
    callback: function (icon, options) {
      return ''.concat(options.base, options.size, '/', "emoji_u", icon, options.ext);
    },
    base: "https://01automonkey.github.io/NotoEmoji/",
    size: 128
  });
}
```

**Comment by WebReflection** [comment]
Oh ... I see, apologies I completely misunderstood your question then.

Yes, that's one way to go as specified in the README:
https://github.com/twitter/twemoji#callback

You have all possible options in here:
https://github.com/twitter/twemoji#object-as-parameter
