### ISSUE TITLE
Unsupported emojis

### ISSUE THREAD

**Issue by gthvidsten** [twitter/twemoji#232]
[This tweet](https://twitter.com/alo_oficial/status/877922488776138752) contains emojis not caught by the regex to find emojis: `\ud83c\udffb`.

Might be because it is posted from Instagram that may support additional emojis?

**Comment by gthvidsten** [comment]
Additional missing emojis in [this tweet](https://twitter.com/ValtteriBottas/status/882636368962351104):

The mountain emoji is not caught by the regex in `twmoji.js`.
The person emoji is caught, but on twitter.com this emoji consists of four unicode characters, but twemoji only uses the two first unicode characters, which leaves something else behind it.
The Austrian flag also consists of four unicode characters, and the regex catches these as two separate emojis (one saying "A", another saying "T").

**Comment by andypiper** [comment]
Take a look at the updated version [here](https://github.com/twitter/twemoji/tree/gh-pages/2) and let us know how you get on.

**Comment by gthvidsten** [comment]
That regex works much better than the one from two years ago! 👍
Might want to consider cleaning up the source code, though, to prevent others from falling into the same trap as I did :)

**Comment by andypiper** [comment]
Sure thing, I'll ask the folks maintaining how best we can resolve for future. Thanks for your patience!

**Comment by WebReflection** [comment]
> Might want to consider cleaning up the source code

@gthvidsten unfortunately everything in this repository is mirrored through the CDN so no "clean-up" is possible without breaking previous users.

However, literally the first link to the CDN in the README is the right one and the second header is about breaking  changes: https://github.com/twitter/twemoji#twitter-emoji-twemoji-

As you can see, we tried to put the ABC on the top of the README but if you have any hint on how we can improve here, considering constrains we can't just change files in this repo, please share.

Thank you!

**Comment by gthvidsten** [comment]
I can see, now, that the CDN link contains "2" in the path. However, it is obviously easy to overlook when you don't know the project well enough.

How about something along these lines (placed somewhere nice and emphasized for visibility):

> The files in the root folder in this project are deprecated and listed for CDN and historical reasons. Please use the files for the current version (2) instead.

**Comment by WebReflection** [comment]
@gthvidsten out of curiosity, did you write the CDN url by hand?

**Comment by gthvidsten** [comment]
@WebReflection I didn't even write the CDN url. I just saw a `twemoji.js` file in the root folder and assumed that would be the correct file. I know, I know... never assume... but it's just so easy :)

**Comment by WebReflection** [comment]
Then you'd probably agree, writing whatever you think should be written in the README would be pointless regardless, if nobody actually reads it, isn't it? :smile:

I don't see improvements in changing it as it is and we cannot remove that file.

Developers gotta read those first two paragraphs anyway.

**Comment by gthvidsten** [comment]
I may have phrased this the wrong way. I did of course read the README. That's the first thing I do with repos. However, when I got to the CDN paragraph I just skimmed it because I wasn't going to use twemoji from a CDN. I just needed the regex in the code. So after reading the README I found the twemoji.js file at the root level and started using that.

**Comment by WebReflection** [comment]
I see. I have added your suggested text:
https://github.com/twitter/twemoji#twitter-emoji-twemoji-

**Comment by gthvidsten** [comment]
👍
