### ISSUE TITLE
T-Rex pose not scientifically accurate

### ISSUE THREAD

**Issue by salty-horse** [twitter/twemoji#237]
The Twitter image for U+1F996 T-REX depicts it standing upright. While this is a popular and recognizable look for the dinosaur, it does not reflect current scientific understanding. "Canonizing" it in an emoji will help perpetuate the myth.

For more info:
https://en.wikipedia.org/wiki/Tyrannosaurus#Posture
http://news.cornell.edu/stories/2013/02/blame-barney-students-perception-t-rex-outdated

**Comment by cooperkernan** [comment]
Seen here: https://emojipedia.org/t-rex/ is the google version ok? Or emojidex? Could probably swap out the emoji with another one, I'm not exactly sure how to create or edit it as is, though.

**Comment by salty-horse** [comment]
One vendor can't flat-out copy another vendor's emoji. Not sure what you're suggesting by "swap out".

I'm not an expert on dinosaurs, but the emojidex one seems fine (if not overly-detailed). Not sure about the Google one. I reported a separate bug in EmojiOne.

**Comment by jdecked** [comment]
We're looking into repositioning the head and changing the color of the emoji here to better align with other vendors.

**Comment by jdecked** [comment]
This has been fixed in [v13.0.2](https://github.com/twitter/twemoji/releases/tag/v13.0.2).

**Comment by oliverpool** [comment]
![image](https://user-images.githubusercontent.com/3864879/111026225-7a746880-83e9-11eb-9750-332fdc7b264b.png)


I have the feeling that the previous representation was more accurate.

> Modern representations in museums, art, and film show T. rex with its body approximately parallel to the ground with the tail extended behind the body to balance the head.

https://en.wikipedia.org/wiki/Tyrannosaurus#Posture

**Comment by oliverpool** [comment]
@jdecked is there any plan to fix this?

**Comment by jdecked** [comment]
@oliverpool We don't have a plan for these specific edits right now. As with anything Twemoji, we may change the artwork in the future, but there are no current plans for these specific edits.

**Comment by Crissov** [comment]
Also, where are the feathers?

**Comment by oliverpool** [comment]
@jdecked alright. Would you mind re-opening the issue? (even if there is no current plan, the "T-Rex pose is not scientifically accurate")

**Comment by jdecked** [comment]
@oliverpool No, sorry. I periodically close issues we don't intend to change so as to keep things neat.
