### ISSUE TITLE
A suggestion to include Somaliland flag emoji

### ISSUE THREAD

**Issue by jamal-yusuf** [twitter/twemoji#238]
Hey Guys
Not too sure if this is the appropriate method for raising emoji suggestions.

Anyway, we have a large active Somaliland community. However, we do not have our flag available from the emoji options on Twitter. 

We currently use a red & green heart emoji with a white circle in the middle to represent our flag on twitter feeds.  (example https://twitter.com/RealistRedDevil/status/894248411221950464)

Was wondering if it was possible to have an emoji version of our flag?  https://en.wikipedia.org/wiki/Flag_of_Somaliland

Thanks,
Jamal

**Comment by paularmstrong** [comment]
@jamal-yusuf The character needs to be first proposed to the Unicode Consortium. Instructions here http://unicode.org/emoji/selection.html

**Comment by Crissov** [comment]
If you can get something like `SO-SL` added to [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-2%3ASO), you could ask for the respective Emoji Tag Sequence to be supported by Twemoji, but until then ❤️⚪💚 is as good as it gets.

**Comment by jamal-yusuf** [comment]
Thank you very much for the directions. I will definitely follow up with the unicode orginisation. 

Thanks again,
Jamal
