### ISSUE TITLE
New Flag of Mauritania

### ISSUE THREAD

**Issue by FlamingObsidian** [twitter/twemoji#239]
As Mauritania has a new flag, a new version of the emoji is needed. See [here](
https://www.pmnewsnigeria.com/2017/08/07/mauritania-abolish-senate-change-flag/) and [here](https://en.wikipedia.org/wiki/Flag_of_Mauritania#2017_modification_proposal). New flag:
![image](https://user-images.githubusercontent.com/18519894/29031286-5b75fea0-7b53-11e7-9118-7fcc33040c0e.png)

**Comment by bhaggs** [comment]
Resolved as part of the 2.4 release.
