### ISSUE TITLE
Rendering in Safari vs Chrome

### ISSUE THREAD

**Issue by fvcproductions** [twitter/twemoji#240]
So I've been using Twemoji for a bit on my web projects but recently I noticed that it will render a ️️️️🖾 right next to the rendered emoji itself on Safari (mobile & desktop) and Chrome (mobile only).
️️️
I've created a CodePen (see screenshots below) to attempt to isolate the issue so that if you [open this CodePen](https://codepen.io/fvcproductions/pen/qXrmbq) in Safari or on the Chrome iOS app, you'll be able to see the lines I'm talking about.

I'm using Twemoji version 2.3 ([`https://twemoji.maxcdn.com/2/twemoji.min.js?2.3.0`](https://twemoji.maxcdn.com/2/twemoji.min.js?2.3.0)).

**To note**, this only happens with certain emoji (top ones in this case) but I just wanted to see if there was a workaround around this or if this is just a visual change just happens with specific emoji. 

I'm sure it's been mentioned before but sifting through a couple of the closed issues didn't really lead to any clear conclusions.

Any insight into the issue would be appreciated.

---

## In Chrome (Version 60.0.3112.90 - latest), there are no issues.

![chrome](https://user-images.githubusercontent.com/4284691/29057407-04c48bc8-7bbf-11e7-8412-f15c854fbfaf.png)

## In Chrome (iOS), the boxes start to appear. Not sure why.

![fullsizeoutput_c8](https://user-images.githubusercontent.com/4284691/29057667-fdab6ab2-7bc0-11e7-9ea0-fe6c5094db43.jpeg)

## In Safari (Version 10.1.2 - latest), the boxes appear.

![safari](https://user-images.githubusercontent.com/4284691/29057408-04d42880-7bbf-11e7-8dee-84b10250620f.png)

## In Safari (iOS), the boxes also appear.

![fullsizeoutput_c9](https://user-images.githubusercontent.com/4284691/29057677-05db3ba4-7bc1-11e7-84ec-15edff2c83bd.jpeg)

---

> Just to clarify the boxes, this is how it looks like on Safari with no styling.

<img width="370" alt="screenshot 2017-08-07 22 48 26" src="https://user-images.githubusercontent.com/4284691/29057965-a3ce8338-7bc2-11e7-9caf-d5313289efa8.png">

**Comment by WebReflection** [comment]
It's so weird we didn't catch this before.

Version `v2.5.0` fixes it (it'll take a little while to be available on the cdn though)

The new link, once purged, will be the following one:
https://twemoji.maxcdn.com/2/twemoji.js?2.5.0

A basic test page with this fix is being published here:
http://twitter.github.io/twemoji/2/test/base.html

**Comment by fvcproductions** [comment]
Thanks for the fix - much appreciated! :smile:
