### ISSUE TITLE
No HTTP/2 on twemoji.maxcdn.com

### ISSUE THREAD

**Issue by Nektro** [twitter/twemoji#241]
Especially on pages with a lot of emoji it would help load times with H2 enabled on the MaxCDN mirror.

**Comment by WebReflection** [comment]
Not sure who to ping about this ... @bhaggs any idea?

**Comment by paularmstrong** [comment]
HTTP/2 is available on MaxCDN if you're using HTTPS: https://www.maxcdn.com/one/tutorial/enable-http2/

**Comment by WebReflection** [comment]
`https` is also the default since quite a while. @Nektro please double check you are using latest with folder `/2/`

**Comment by Nektro** [comment]
![devtools twemoji](https://user-images.githubusercontent.com/5464072/29142214-36b209ba-7d1f-11e7-943c-070e9bd681ce.png)

**Comment by WebReflection** [comment]
That says, protocol **http/1.1**

Are you including latest library?

**Comment by WebReflection** [comment]
Scratch that, actually I see http/1.1 too even on latest.

Reopening until proof it's on http2 when in https

**Comment by WebReflection** [comment]
So ... AFAIK I've just enabled it. Will double check tomorrow if that's the case but there's nothing else I can do in MaxCDN settings (beside enabling it)

Maybe just a propagation/cache issue, I'm sure by tomorrow it'll be fine.

**Comment by Nektro** [comment]
All good on my end 👍👍
