### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by wottpal** [twitter/twemoji#242]
If I want to use an emoji as my favicon, what kind of attribution is required for that?

<img width="655" alt="bildschirmfoto 2017-08-11 um 18 11 52" src="https://user-images.githubusercontent.com/3930150/29221869-a509cb4e-7ec0-11e7-90cb-30c5c52bd6a1.png">

**Comment by ardaozkal** [comment]
IANAL but I believe it's CC-BY 4.0 that applies.

**Comment by El-Mahbub** [comment]
With two license on this project. Can we use twemoji for our web, if our web like twitter or facebook ?
