### ISSUE TITLE
Download Twemoji 

### ISSUE THREAD

**Issue by jmgconesa** [twitter/twemoji#245]
Hi guys,

Someone could say me where could I download the latest version of twemoji? I have found this page (https://twitter.github.io/twemoji/2/test/preview.html) but I just can download them in a PNG format, and I would like to have them in a JPNG format with a bigger size too.

Thank you very much for your help,

Jose.

**Comment by WebReflection** [comment]
if you clone this repository you'll have the entirety of the `2/assets` or `2/svg` folder
https://github.com/twitter/twemoji/tree/gh-pages/2

**Comment by jmgconesa** [comment]
Excuse me,

What do you mean by clone? There is any youtube video which teaches me how to do it?

I do not want the emojis in my keyboard, I want them in a jpng format to print them.

Thank you very much for all your help,

Jose.

**Comment by WebReflection** [comment]
https://youtu.be/zrdIilpU2OI

**Comment by WebReflection** [comment]
that's the video ... this is the documentation
https://help.github.com/articles/cloning-a-repository/

**Comment by Crissov** [comment]
You could attach zip files containing only all SVGs and PNGs respectively to each release, though.

**Comment by WebReflection** [comment]
There are folders with all SVGs and PNGs respectively and everyone can get them at any time.

This is how GitHub works.
