### ISSUE TITLE
How to render 3-code tone emojis correctly?

### ISSUE THREAD

**Issue by manniL** [twitter/twemoji#247]
I'm asking myself how I can render emojis with tones "correctly". When I use basic emojis, like ok_hand, it works fine. But for things like "female detective with dark tone", I don't manage to render it correctly.

Here is what I tried:

twemoji.parse("🕵🏿‍♀")
![image](https://user-images.githubusercontent.com/640208/29928422-4207c98e-8e69-11e7-9e89-561be43d9390.png)

twemoji.parse("🕵♀🏿‍")
![image](https://user-images.githubusercontent.com/640208/29928456-5a6e863e-8e69-11e7-9d87-349560132707.png)

**Comment by manniL** [comment]
Worked it out! It has to do with the placement of the Zero Width Joiner and Variation tokens.

**Comment by maniacally** [comment]
Mind sharing how you solved this?  In the same boat here

**Comment by manniL** [comment]
@maniacally Phew, good question. I'll check later if I still have that project somewhere

**Comment by JoshyPHP** [comment]
You can read about canonical ZWJ sequences on Unicode's website: https://unicode.org/Public/emoji/11.0/emoji-zwj-sequences.txt

```js
twemoji.parse("\uD83D\uDD75\uD83C\uDFFD\u200D\u2640\uFE0F")
```
```html
<img class="emoji" draggable="false" alt="🕵🏽‍♀️" src="https://twemoji.maxcdn.com/2/72x72/1f575-1f3fd-200d-2640-fe0f.png"/>
````
