### ISSUE TITLE
bottle of champagne

### ISSUE THREAD

**Issue by jmgconesa** [twitter/twemoji#249]
Can anyone tell me the name of the bottle of champagne? I can´t see it when I download the emojis, maybe should I try an earlier version? Did twitter removed this emoji from the last version?

Thank you!

**Comment by WebReflection** [comment]
https://twemoji.maxcdn.com/2/72x72/1f37e.png ?

**Comment by jmgconesa** [comment]
Thank you very much,
How could I get it in .ai format?

**Comment by WebReflection** [comment]
https://github.com/twitter/twemoji/blob/gh-pages/2/assets/1f37e.ai ?

**Comment by jmgconesa** [comment]
thank you very much
