### ISSUE TITLE
Get wrong result twemoji with textarea

### ISSUE THREAD

**Issue by El-Mahbub** [twitter/twemoji#251]
![textarea twemoji](https://user-images.githubusercontent.com/20553210/30564511-54ba31d6-9cef-11e7-8753-73b3758ffd9b.png)
![twemoji db](https://user-images.githubusercontent.com/20553210/30564502-51e5187c-9cef-11e7-9642-77a3cc0b4f38.png)

I got wrong result twemoji with textarea when i want save to database, as you can see on image above.
Here is my codes : 

```
<div class="tab-content">
					    <div id="smiley_emoji" class="tab-pane fade in active" style="display: block">
					    <ul class="list-inline" id="emoji-status">
<li>&#x1F642;</li>
<li>&#x1F641;</li>
<li>&#x1F600;</li>
<li>&#x1F618;</li>
<li>&#x1F632;</li>
<li>&#x1F633;</li>
<li>&#x1F616;</li>
<li>&#x1F617;</li>
<li>&#x1F607;</li>
<li>&#x1F608;</li>
<li>&#x1F609;</li>
<li>&#x1F60A;</li>
<li>&#x1F60B;</li>
<li>&#x1F61D;</li>
<li>&#x1F61E;</li>
<li>&#x1F62C;</li>
<li>&#x1F62D;</li>
<li>&#x1F601;</li>
<li>&#x1F602;</li>
<li>&#x1F603;</li>
<li>&#x1F60C;</li>
<li>&#x1F60D;</li>
<li>&#x1F60E;</li>
<li>&#x1F60F;</li>
<li>&#x1F610;</li>
<li>&#x1F611;</li>
<li>&#x1F612;</li>
<li>&#x1F613;</li>
<li>&#x1F614;</li>
<li>&#x1F615;</li>
<li>&#x1F619;</li>
<li>&#x1F61A;</li>
<li>&#x1F61B;</li>
<li>&#x1F61C;</li>
<li>&#x1F621;</li>
<li>&#x1F622;</li>
<li>&#x1F623;</li>
<li>&#x1F624;</li>
<li>&#x1F625;</li>
<li>&#x1F626;</li>
<li>&#x1F627;</li>
<li>&#x1F628;</li>
<li>&#x1F629;</li>
<li>&#x1F631;</li>
<li>&#x1F62A;</li>
<li>&#x1F62B;</li>
<li>&#x1F604;</li>
<li>&#x1F61F;</li>
<li>&#x1F620;</li>
<li>&#x1F605;</li>
<li>&#x1F606;</li>
<li>&#x1F62E;</li>
<li>&#x1F62F;</li>
<li>&#x1F630;</li>
<li>&#x1F634;</li>
<li>&#x1F635;</li>
<li>&#x1F636;</li>
<li>&#x1F637;</li>
					    </ul>
				</div>
				</div>
			    <script>
			    	$('#emoji-status').css({
			    		margin: '10px',
			    		maxHeight: '100px'
			    	}).overscroll().find('li').each(function(index, el) {
			    	   $(this).css({
			    	   	fontSize: '24px',
			    	   	cursor: 'pointer'
			    	   }).click(function(event) {
			    	   	var y = $("#textAreaStatusProfil").val();
			    	   	var x = $(this).text();
  						$("#textAreaStatusProfil").val(y+" "+x+" ");
			    	   });;
			    	});
			    	$('#emot-status-tabs').overscroll();
			    </script> 
```

**Comment by WebReflection** [comment]
please provide an online test page. It's impossible to understand what you are doing, there's not a single call to the twemoji in the whole text you pasted here.

Thanks

**Comment by El-Mahbub** [comment]
Sorry, i am use twemoji codes with view source at here https://twitter.github.io/twemoji/2/test/preview.html . I know there is not single call to twemoji correspond on documentation, but that is encrypted codes from twemoji. What i want is  : 
1. List codes icons from twemoji like that url without to download all images. Can i do this ?
2.  Or i am using encrypted codes above and can support all browser and can store to database.
Hope your answer :)

**Comment by WebReflection** [comment]
I don't understand what is your issue, in case you have one. There's nothing encrypted and you can already store in database whatever you want, emojis are just code points (plain text).

The twemoji library is capable or replacing such code-points with images either through text or directly via DOM.

Closing this until there is a bug to solve.
