### ISSUE TITLE
[Request] Add variations of men and women wrestling

### ISSUE THREAD

**Issue by manniL** [twitter/twemoji#252]
Greetings!

As you described in the README, Twemoji should support the Emoji 5.0 draft.
Currently, no Emoji images for the fitzpatrick variations of `women_wrestling` or `men_wrestling` can be found, though they were added already in Emoji 4.0 ([source](https://emojipedia.org/women-wrestling-type-6/))

Could you add them to Twemoji? ☺️

**Comment by Crissov** [comment]
They have been removed from Emoji 5 (released in May), because both wrestlers have the same skin color with current rules.

**Comment by manniL** [comment]
Oh well, I didn't know that! Thanks a lot @Crissov
