### ISSUE TITLE
Consistency in files naming

### ISSUE THREAD

**Issue by romligCH** [twitter/twemoji#253]
Why are some files named after the non fully qualified emoji sequence while some are named after the fully qualified sequence?

To be precise, out of the 2623 emojis listed in the [reference file for Emoji 5.0](http://unicode.org/Public/emoji/5.0/emoji-test.txt) ([JSON version](https://gist.github.com/romligCH/a483ff1487b4627a7bc5238ae436d3ef)):
- 2406 are named after the fully qualified code
- 217 are named after the non fully qualified code (see the list [here](https://gist.github.com/romligCH/18457c09cd7c6e6b8de6fab79b47185e))
- 535 non fully qualified codes correspond to a symbol with a file named after a fully qualified code
- 2 non fully qualified codes correspond to with a file named after a symbol with another non fully qualified code (1f441-fe0f-200d-1f5e8 and 1f441-fe0f-200d-1f5e8, eye in a speech bubble, file is 1f441-200d-1f5e8, should be 1f441-fe0f-200d-1f5e8-fe0f)

**Comment by WebReflection** [comment]
having `fe0f` everywhere looked a bit redundant, hence we used the implicit fe0f version

**Comment by Crissov** [comment]
All file names should be without both, `fe0f` (VS16) and `200d` (ZWJ). Those are technical details from a very different level.

**Comment by WebReflection** [comment]
yeah so, we have also non standard emoji for older iOS devices.

I'd like to understand what is the actual issue here, 'cause I don't see any?

**Comment by romligCH** [comment]
The problem is that `fe0f` appears in the filename for all the 520 others emojis which use them. My problem is that I could not find the rule for having it or not. Is is some kind of whilelist?

Also`200d` does appear in the filenames. Incidentally the 520 files with `fe0f` in the name also contains `200d` (there are 182 others files with `200d`)

**Comment by WebReflection** [comment]
so, in this page: http://twitter.github.io/twemoji/2/test/preview.html
2661 emoji are parsed and transformed into file names, which is what this JS library does.
We change file names, we need to change the JS library which is already deployed through million sites.

What would anyone gain from doing that?

**Comment by romligCH** [comment]
The goal was never to break a widely-deployed library. It was mostly to understand why it was done this way (hence the _Why_ in the first sentence).

In his current implementation just strips the `fe0f` char when they are not needed using a long regex. So there's the explanation. I have to admit I was surprised when I see the filenames didn't match the real symbol codes...

And that works in most cases (but for the fully qualified version of eye-in-a-speech-bubble, but that may be totally unrelated), so there's no need to change that.

```js
twemoji.parse("\ud83d\udc41\ufe0f\u200d\ud83d\udde8\ufe0f", 72)
'<img class="emoji" draggable="false" alt="👁️" src="https://twemoji.maxcdn.com/2/72x72/1f441.png"/>‍<img class="emoji" draggable="false" alt="🗨️" src="https://twemoji.maxcdn.com/2/72x72/1f5e8.png"/>'
```
