### ISSUE TITLE
Star and Crescent is broken on Linux/Firefox

### ISSUE THREAD

**Issue by NerosTie** [twitter/twemoji#254]
I have 1 broken emoji on Linux (Arch, with aur/ttf-twemoji-color) with Firefox (57 Beta) which is Star and Crescent. It appears white for some reason…

https://emojipedia.org/star-and-crescent/

![screenshot_20171020_055008](https://user-images.githubusercontent.com/4572452/31804573-886ab702-b55a-11e7-99cd-13fff26138ee.png)

**Comment by gusbemacbe** [comment]
Due to the disappearance of most recent Twenoji released packages caused by one of developers, your emojis, including mine, have disappeared. Flags, new flags, new emojis have disappeared and been broken. Switch to EmojiOne while Twitter developers will fix the fail.

**Comment by NerosTie** [comment]
Fixed.
