### ISSUE TITLE
the "middle finger" emoji (0x1F595) is missing

### ISSUE THREAD

**Issue by bkad** [twitter/twemoji#255]

**Comment by edent** [comment]
It is available - see:

* https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f595.svg
* https://github.com/twitter/twemoji/blob/gh-pages/2/72x72/1f595.png

**Comment by bkad** [comment]
I see, I was looking in the wrong directory (https://github.com/twitter/twemoji/tree/gh-pages/svg).
