### ISSUE TITLE
SVG Simplification. Any interest?

### ISSUE THREAD

**Issue by edent** [twitter/twemoji#257]
`1f534` is large red circle.

The current SVG is

`<defs id="defs6"><clipPath id="clipPath16" clipPathUnits="userSpaceOnUse"><path id="path18" d="M 0,36 36,36 36,0 0,0 0,36 Z"/></clipPath></defs><g transform="matrix(1.25,0,0,-1.25,0,45)" id="g10"><g id="g12"><g clip-path="url(#clipPath16)" id="g14"><g transform="translate(35,18)" id="g20"><path id="path22" style="fill:#dd2e44;fill-opacity:1;fill-rule:nonzero;stroke:none" d="m 0,0 c 0,-9.389 -7.611,-17 -17,-17 -9.389,0 -17,7.611 -17,17 0,9.389 7.611,17 17,17 C -7.611,17 0,9.389 0,0"/></g></g></g></g>`

This could be replaced by

`<circle cx="22.5" cy="22.5" r="21" fill="#dd2e44"/>`

Simpler to edit, smaller file size, possibly quicker to render.

* Is there a specific reason for the complexity that I don't understand?
* If not - would there be any interest in simplifying the SVGs?

**Comment by bhaggs** [comment]
We're cleaning up a number of these SVGs to be made simpler. Will include in our next update.

**Comment by TheEssemCraft** [comment]
I'm all for this. The current SVGs need some fixing up.

**Comment by TheEssemCraft** [comment]
@bhaggs Might I ask, what settings are you using to export SVGs in Illustrator?

**Comment by TheEssemCraft** [comment]
The latest update doesn't fix the original problem that @edent had. It just changes the emoji designs and doesn't really simplify/minify the SVGs.

**Comment by bhaggs** [comment]
We cleaned up all the SVGs in 2.5.
