### ISSUE TITLE
2.4 and 2.5 tags have disappeared from repo

### ISSUE THREAD

**Issue by autopulated** [twitter/twemoji#258]
See attached screenshot - the tags were there until a few days ago! Needless to say this broke some builds.

![screen shot 2017-10-31 at 12 52 00](https://user-images.githubusercontent.com/3456211/32224675-5b5a8c72-be3a-11e7-8f14-6c695a3d616e.png)

**Comment by WebReflection** [comment]
cc @bhaggs

**Comment by Vampire** [comment]
I guess Bryan Haggerty didn't like that Andrea Giammarchi incresed the version. He removed those tags, on 2017-10-30, made a new commit on top of the former 2.5.0 and made this version 2.3.1 and couple of days ago made another commit and made that version 2.4.0.

**Comment by WebReflection** [comment]
I've followed semver, not sure what happened with 2.5 to 2.3.1 ... it wasn't needed, IMO, but I'm sure there was some reason behind I'm not aware of.

Not doing anything since I don't want to cause extra-issues. Maybe @bhaggs knows what's the best thing to do here.

**Comment by Vampire** [comment]
Ah, you are Andrea, I see. Didn't see this from the username, just have seen in the mail notification. :-)

**Comment by WebReflection** [comment]
Hello Vampire, nice to meet you.

**Comment by lpellegr** [comment]
What a crazy idea to have erased released versions. NPM version is no longer aligned:

https://www.npmjs.com/package/twemoji

Upon a simple redownload of the dependency, people (I included) are getting new emoji styles even if they do not want...

**Comment by tedmiston** [comment]
Yeah, definitely not a fan of removing published version tags... 

I'm pulling in twemoji from cdnjs.  Overwriting versions means the lib author is choosing to chang some people's builds that should have been deterministic.  On the other hand, I use the integrity attribute with a sha256 hash on the script meaning that this would block the library from loading as if it were tampered with since the author chose to overwrite a published version.

I understand if the process is limited to one person cutting releases, but removing published releases, especially silently, is reckless.  Just my 2¢.

**Comment by tedmiston** [comment]
<img width="1616" alt="screen shot 2017-12-31 at 11 12 49 pm" src="https://user-images.githubusercontent.com/366688/34465584-5ae50e9a-ee80-11e7-821a-0a7e5daa4217.png">

This also means the 2.4.0 version on Cloudflare points to what's not "2.4.0" as of the re-release (last-modified = Nov 14, 2017 whereas the new 2.4.0 was cut on Dec 8, 2017).

@bhaggs It would be nice to re-release the new 2.4.0 as e.g., 2.4.1 to fix this issue on the CDN where the re-released 2.4.0 is currently not accessible.

**Comment by bhaggs** [comment]
We're prepping an update which will be tagged as version 2.4.1, so that should hopefully address that.

**Comment by neverthemachineforever** [comment]
2.4.1 is gone now too? I'm quite confused now which version I should be using..

**Comment by bhaggs** [comment]
v2.5.0 is the most current tag/release
