### ISSUE TITLE
Is the design of U+1F646 emoji correct?

### ISSUE THREAD

**Issue by yantene** [twitter/twemoji#259]
I have an opinion for 🙆 (U+1F646) emoji.

https://unicode.org/emoji/charts/full-emoji-list.html#1f646

This emoji means making a circle with both arms.
So the back of the hand should be facing upward.
For example, Google's U+1F646 emoji looks like that.
However the palm of the twemoji's one is facing upward.

I think it is hard for a reader to understand the meaning of this emoji.
What do you think?

Sorry if it's hard to understand my English. Thank you.

**Comment by bhaggs** [comment]
That's a good catch. We're reviewing a number of existing emojis now and cleaning them up. We'll include this in the list.

**Comment by bhaggs** [comment]
Resolved in the 2.4 release.

**Comment by yantene** [comment]
Thank you for your work.

By the way, in the process of fix, the following emojis' cuffs and hair layers have been swapped.

- 1f646-200d-2642-fe0f
- 1f646-1f3fb-200d-2642-fe0f
- 1f646-1f3fc-200d-2642-fe0f
- 1f646-1f3fd-200d-2642-fe0f
- 1f646-1f3fe-200d-2642-fe0f
- 1f646-1f3ff-200d-2642-fe0f

Should I make a new issue?
