### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by nguyenha1121** [twitter/twemoji#261]
How to import it to angular 4+ ?

**Comment by WebReflection** [comment]
would CommonJS work there?
https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.npm.js

**Comment by smartm0use** [comment]
What do you mean?
I did install library with `npm i twemoji` and I imported it in `angular.json` file:

```
"scripts": [
    "node_modules/twemoji/2/twemoji.min.js"
]
```

Now, how to use it in my Angular web app?

**Comment by jfcere** [comment]
I've created a StackBlitz example to show how I integrated twemoji library in my Angular application:  
https://stackblitz.com/edit/angular-twemoji

### Things to notice...

1. The example uses CDN in `index.html` but this should be the same as adding `twemoji.min.js` file to `angular.json` scripts section.

```json
"scripts": [
    "node_modules/twemoji/dist/twemoji.min.js"
]
```

2. I've declared a variable for the global `twemoji` object definition in `global.d.ts` so TypeScript stop complaining as there is currently no definition types available (I've only added definition of used method): 

```typescript
declare var twemoji: {
  parse(str: string): string;
}
```

3. As per their documentation, I've added global CSS so the emoji image scales to font size of the surrounding text in `styles.css`:

```css
img.emoji {
  height: 1em;
  width: 1em;
  margin: 0 .05em 0 .1em;
  vertical-align: -0.1em;
}
```
