### ISSUE TITLE
Changes for v2

### ISSUE THREAD

**Issue by john2014** [twitter/twemoji#263]
Here are three changes for v2:

1. In the readme file, the link for maxcdn, assets, etc still point to v1. Example: <img src="https://twemoji.maxcdn.com/36x36/2764.png"/. All these links should be changed to point to /2 folder.

2. Version 2 currently only has 72x72 size image. Each image is 1 KB. For 1500+ images, it would be downloading 1.5MB data. Could you also add a 36x36 size image. This smaller size will be helpful especially when deploying to countries with slow internet connections. 

3. For attribution, it would be helpful to add the exact text (or suggestions) in Readme page that twitter would like users to use. This way they wont have to guess what is appropriate (and not worry if they have violated the cc license). Thank you.

**Comment by WebReflection** [comment]
> 1. why not a PR for that? ;-)

> 2. nobody should download all images, that's why there is Max-CDN behind, so that's not a real-world concern

> 3. what kind of suggestions could be added? AFAIK the CC already has rules to follow. How can we improve?

**Comment by john2014** [comment]
1. I am not very familiar with PR. In addition, twitter has made some breaking changes to v2. Hence you guys would be the best source to update the links.

2. Today, when you go to twitter.com and click on the emoji icon (when composing tweet), it downloads all 1500 images. Other sites which provide similar emoji functions would also do the same. Even facebook downloads all 1500 images when we click on emoji icon.

3. Something that would satisfy twitter legal department. Something similar to: emoji are provided by twitter and images have CC license.
