### ISSUE TITLE
Some modified Twemoji v2.4 emojis not yet replaced at MaxCDN ?!

### ISSUE THREAD

**Issue by djrocher** [twitter/twemoji#264]
Thanks for the latest Twemoji update :-)

I'm using the latest script (twemoji.maxcdn.com/2/twemoji.min.js?2.4), but it seems that some of the modified emojis aren't yet replaced at MaxCDN? Some examples (I didn't check them all):

The "Exploding head" shows still the old version:
https://twemoji.maxcdn.com/2/72x72/1f92f.png

or the "Birthday cake":
https://twemoji.maxcdn.com/2/72x72/1f382.png

or the "Snow capped mountain":
https://twemoji.maxcdn.com/2/72x72/1f3d4.png

The "Mountain" or the "Volcano", for instance, are already depicting the new versions:
https://twemoji.maxcdn.com/2/72x72/26f0.png
https://twemoji.maxcdn.com/2/72x72/1f30b.png

Will the modified v2.4 Twemojis soon be replaced at MaxCDN?

**Comment by djrocher** [comment]
Are they gradually replacing the emojis? Today, December 11, the "Exploding head" shows the new version, the "Birthday cake" still the old one at the time of writing.

**Comment by WebReflection** [comment]
the cache will be gradually pruned, every new asset will eventually be delivered

**Comment by bhaggs** [comment]
We've manually flushed some of the assets, others will automatically be pruned over time.
