### ISSUE TITLE
Emoji missing for two unicodes

### ISSUE THREAD

**Issue by john2014** [twitter/twemoji#267]
Twitter emoji is missing images for following two emoji unicode standard:

1. Title: 00a9,
     Emoji Code: ©
     Emoji Name: Copyright

2. Title: 00ae,
     Emoji Code: ®
     Emoji Name: Registered

**Comment by bhaggs** [comment]
Are you referring to Twitter.com or Twemoji? The Twemoji includes these emoji graphics and the parser supports the image replacement for those codepoints as seen on http://twitter.github.io/twemoji/2/test/preview.html.

Twitter.com renders these emojis as text even if the emoji modifier fe0f is present for visual formatting reasons. For Twemoji we didn't want to impose that decision on others and adhered to the emoji spec.

**Comment by john2014** [comment]
Hi Bryan, thanks for the links. I actually meant the Twemoji (since emojis on twitter.com would probably be considered out of scope for this library).

I looked at the preview url and it seems the CDN link

1. For Copyright is:
Actual: https://twemoji.maxcdn.com/2/72x72/a9.png
Expected: https://twemoji.maxcdn.com/2/72x72/00a9.png

2. For Trademark is:
Actual: https://twemoji.maxcdn.com/2/72x72/ae.png
Expected: https://twemoji.maxcdn.com/2/72x72/00ae.png

All other CDN links for emojis are atleast four digits. For some reason these two are only two digits (a9 and ae - instead of 00a9 and 00ae). Is it possible to change them to four digits so as to to match the rest of 2600+ emojis? Thank you 😄

**Comment by n8downs** [comment]
We don't plan to pad the codepoint values in asset urls with leading zeros, sorry!
