### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dheerajjaiswal08** [twitter/twemoji#269]
Hello sir/ma'am,

When I want to parse the unicode directly it works 
means,
twemoji.parse("\ud83d\ude0d\ud83d\ude0a\ud83d\ude04\ud83d\ude14");

but when i get the value form my data base and then pass it to the function it not works
var test = getValuefromdb();
twemoji.parse(test);

Sir/ma'am Please Help
Thank you

**Comment by WebReflection** [comment]
that means your database does not return the same unicode string.

Without a dump of that `test` variable there's not much we can do to help.

**Comment by Mindbowser** [comment]
Same issue, any luck? When we print values coming from backend it seems they are correct, any idea?

**Comment by Mindbowser** [comment]
seems like duplicate of https://github.com/twitter/twemoji/issues/206

**Comment by WebReflection** [comment]
> seems like duplicate of #206 

also no answers in ages so I am closing this as there's nothing to do here.
