### ISSUE TITLE
Some emojis' cuffs and hair layers have been swapped

### ISSUE THREAD

**Issue by yantene** [twitter/twemoji#270]
- 1f646-200d-2642-fe0f
- 1f646-1f3fb-200d-2642-fe0f
- 1f646-1f3fc-200d-2642-fe0f
- 1f646-1f3fd-200d-2642-fe0f
- 1f646-1f3fe-200d-2642-fe0f
- 1f646-1f3ff-200d-2642-fe0f

**Comment by bhaggs** [comment]
Fixed in 2.5.
