### ISSUE TITLE
question about graphic license for commercial purpose

### ISSUE THREAD

**Issue by suzukineet** [twitter/twemoji#273]
hi,my name is suzuki from japan and wanna ask about license of "twemoji". 
now we are trying publish one book for commercial purposes and would like to use some graphics in "twemoji".

i found twemoji hold by "CC-by" license here.
https://github.com/twitter/twemoji  
so i think we can use these for commercial purpose if only we put the sourcethe authority next to images,right?

*for example like this
images(graphics) by twitter/twemoji (https://github.com/twitter/twemoji ) are licensed under CC BY 4.0
( https://creativecommons.org/licenses/by/4.0/deed.ja )

**Comment by TheEssemCraft** [comment]
Yes, that is correct. You can use the images freely as long as you give credit.

**Comment by bhaggs** [comment]
If only using the Twemoji graphics, the proper attribution would be:

> Copyright 2018 Twitter, Inc and other contributors
> Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by Crissov** [comment]
I’m pretty sure the copyright statement is unnecessary.

**Comment by TheEssemCraft** [comment]
@Crissov Quote from https://creativecommons.org/licenses/by/4.0/deed:

> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

**Comment by Crissov** [comment]
My point is that “copyright 2018” is unnecessary or even misleading.

> Twemoji graphics made by Twitter and other contributors, licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by bobbytvg** [comment]
I have a similar question.  We produce commercial graphics/video generation software that is currently used for television broadcasts, streaming, and post-production video.  One of the features of our software is the ability to display social media content (via graphic/text), however, we can't necessarily control what the graphics contain as we only provide the software.

We would like to include support for emojis using the twemoji project, but it is unclear exactly where or how the attribution should work.  Obviously, we could/would place a notice in the software (Help > About) with the appropriate attribution, but our concern is whether that covers the usage for the end-user of the software as well, or if they would have to do something on their end as well.

Thanks.

**Comment by TheEssemCraft** [comment]
@bobbytvg Yeah, that should cover it.

**Comment by MsGarnerAETENLLC** [comment]
So if I'm doing a TV documentary on social media and use Twemoji? I just use the attribution in the end credits? or a special thanks? 

Copyright 2019 Twitter, Inc and other contributors Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/
