### ISSUE TITLE
Trailing U+FE0F remained and shown

### ISSUE THREAD

**Issue by tanakahisateru** [twitter/twemoji#275]
Some kind of fully-qualified emojis are converted to not-fully-qualified version with trailing U+FE0F. Then such standalone U+FE0F might be displayed.
![trailing-fe0f](https://user-images.githubusercontent.com/403893/35904514-b7830c42-0c26-11e8-8ec3-93a0e8e52148.png)
(iOS Safari screenshot)

```js
twemoji.replace("❄️", (x)=>{ return '*'; });
// => "*️"                                     It Looks fine but ...
twemoji.replace("❄️", (x)=>{ return '*'; }).split('');
// => Array [ "*", "️" ]                  There is an invisible string
twemoji.replace("❄️", (x)=>{ return '*'; }).split('').map((c)=>{ return c.charCodeAt(0); });
// => Array [ 42, 65039 ]          65039 === "\ufe0f".charCodeAt(0)
```

This behavior is not for all trailing fe0f.
```js
twemoji.replace("⛱", (x)=>{ return '*'; }).split('').map((c)=>{ return c.charCodeAt(0); });
// => Array [ 42 ]                       ⛱ = U+26F1 U+FE0F  good
twemoji.replace("☂️", (x)=>{ return '*'; }).split('').map((c)=>{ return c.charCodeAt(0); });
// => Array [ 42, 65039 ]          ☂️ = U+2602 U+FE0F bad
```

❄️ and ☂️ have older version glyph but ⛱ doesn't.
<img width="664" alt="2018-02-07 17 09 08" src="https://user-images.githubusercontent.com/403893/35905410-5b34e1b4-0c2a-11e8-9657-d50ce5ff2707.png">

I think, these emojis are handled as special case and categorized to a different group that does not have possibly trailing fe0f.

**Comment by tanakahisateru** [comment]
⛱ was single U+26F1 by my Mac keyboard. Difference between ☂️ and ⛱ comes from Apple implementation, not Twemoji's RegExp. Apple randomly choose fully/non-fully sequence, so that other OSes also do same, I guess.

**Comment by denniskim** [comment]
This issue is also causing a bug where code such as:
```
element.innerHTML = twemoji.parse('😐️😐️😐️');
```
results in a text node containing the non-printing variation character being appended to the img tag, which can cause layout issues in webapps.

See fiddle: https://jsfiddle.net/djkim_blz/o87xmgc7/

This happens with the following emoji:
😐️👽️👪️💣️🎓️🐕️🐈️🐦️🐟️🍸️🌏️🌎️🌍️🏠️🏭️🎭️🚇️🚍️🚑️🚔️🚘️🚲️⏳️🕛️🕧️🕐️🕜️🕑️🕝️🕒️🕞️🕓️🕔️🕟️🕠️🕕️🕡️🕖️🕢️🕗️🕣️🕘️🕤️🕙️🕥️🕚️🕦️🌕️🌜️🏆️🎮️🔈️🎧️📻️📟️💻️💿️🎬️📺️📷️📹️🔍️📚️💰️💳️📤️📥️📦️📫️📪️📬️📭️📋️🔒️🔓️🚹️🚺️🚼️🚭️⏩️⏪️♀️♂️⚕️❓️

**Comment by zhulinpinyu** [comment]
♨️🔞

**Comment by n8downs** [comment]
Should be addressed by https://github.com/twitter/twemoji/commit/c9a665abb2f2bbea66013df9c545b387e64b2217
