### ISSUE TITLE
 Pleading Face emoji [Unicode 11] 

### ISSUE THREAD

**Issue by ArmeF97** [twitter/twemoji#276]
I made this emoji, and it will be encoded
https://emojipedia.org/face-with-pleading-eyes/

I friend of mine designed the emoji for me, and I can use it however I want. I want everyone to use it however they want, so you can have it for your font
https://github.com/ArmeF97/Files/issues/1

**Comment by bhaggs** [comment]
Such a great emoji to be included in the spec. Thanks for sharing. We already work within an existing emoji style and will be making a version based on that.
