### ISSUE TITLE
Twemoji now included as a TTF in Fedora

### ISSUE THREAD

**Issue by mavit** [twitter/twemoji#278]
This isn't really an issue as such, so feel free to close it immediately, but I just wanted to let you know that Twemoji is now is now [packaged as a part of Fedora 27](https://apps.fedoraproject.org/packages/twitter-twemoji-fonts), in TTF form, so that it can be used throughout the user interface.

Thanks.

**Comment by decause** [comment]
:100: :100: :100:

**Comment by polarathene** [comment]
Used the Fedora package on Arch via the AUR package `[ttf-twemoji](https://aur.archlinux.org/packages/ttf-twemoji)`. It seems based on comments and trying the font out, that Twemoji recently shrunk the glyphs(noticeable compared to Firefox's bundled version). 

There is a lot of padding with the glyphs, especially vertically(line-height). Is this a change Fedora has made for their usage, or a change this project itself has done?

**Comment by mavit** [comment]
> There is a lot of padding with the glyphs, especially vertically(line-height). Is this a change Fedora has made for their usage, or a change this project itself has done?

It's a bug.  I picked up the patch at https://src.fedoraproject.org/rpms/google-noto-emoji-fonts/blob/58a1f9a48265daf3dfd1d095a1a9f4154ee56a02/f/noto-emoji-use-gm.patch#_11 (to make it easier to apply a subsequent patch for porting to Python 3), and didn't notice that it had hard-coded the dimensions to an incorrect size.

**Comment by jdecked** [comment]
Woohoo! 🎉

**Comment by AndroidDeveloperLB** [comment]
Any way to fetch it without installing Fedora?

**Comment by mavit** [comment]
> Any way to fetch it without installing Fedora?

You could download the Fedora package (from a mirror, via https://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/t/), then extract the file from it using your favourite archive tool (e.g., 7-Zip).

**Comment by AndroidDeveloperLB** [comment]
@mavit At first I didn't know where to look at your link. Thousands of files...
Then I just searched for "twe", and found some files there that contain fonts:

texlive-twemoji-colr-svn75301-2.fc44.noarch.rpm , twitter-twemoji-fonts-14.0.2-10.fc44.noarch.rpm

Weird thing is that they are different font files.

Attached here.

[Twemoji.zip](https://github.com/user-attachments/files/25011210/Twemoji.zip)

It seems your link is of quite new files, so I was hoping it also means the fonts are new. To me, what makes the font better than what we have today is:

1. Be able to show crisp content. That probably occurs when it's actually vector-based. Of course, it could be nice to have a fallback for OSs that can't handle it.
2. Remove non-emoji glyphs. Currently all the Twemoji fonts I've found have a weird issue with digits, as shown [here](https://github.com/mozilla/twemoji-colr/issues/56). It can be solved though, by a command to subset the font to remove the non-emoji glyphs. I'm not an expert at this, but I think Gemini AI can do it. I succeeded for example to subset (using Gemini AI help) to just flags, using this command: `python -m fontTools.subset Twemoji.Mozilla.ttf --unicodes="U+0000,U+1F1E6-1F1FF" --layout-features="*" --glyph-names --output-file=flags_only.ttf` .
3. Be able to handle the latest emojis ([here](https://emojipedia.org/emoji-versions), so I took from [here](https://emojipedia.org/emoji-15.1)) and also have the recent changes ([here](https://github.com/twitter/twemoji/pull/1454/changes), which included the [Iranian flag replaced](https://blog.emojipedia.org/x-expected-to-update-its-iranian-flag-emoji-design/))
4. No new issues.

The one called "Twemoji.ttf" can't have a preview on my IDE, but the other with the name of "TwemojiMozilla.ttf" has a preview fine. 
I tested on Android device too, and checked about possible issues, trying to show this string: "Ab c 12.3 🇮🇷🇺🇸 🐦‍🔥🙂‍↔️️🍄‍🟫🍋‍🟩" (testing letters, space, digits, Iranian flag that should get an update next to US flag, and relatively new emojis).

Below is a screenshot of what I got, where the top is the default font of Google, then TwemojiMozilla.ttf , and then Twemoji.ttf:

<img width="879" height="783" alt="Image" src="https://github.com/user-attachments/assets/dab7399c-f261-44ca-9d65-44bbe4b788e1" />

Sadly, this means there are still issues...

Digits still appear as spaces. The Twemoji.ttf font shows more spaces, both don't support new emojis and both don't have the flags updated.

However, I've noticed that the TwemojiMozilla.ttf file is vector-based (crisp content) and the Twemoji.ttf font isn't (things are blurry the larger the font is). 

Do you know perhaps of a newer version of this TTF font file, and a place to check for it, too?

The only one I've found is here:
https://mirror.whynothugo.nl/twemoji.ttf/

But it has the same issues as the Twemoji.ttf file...
