### ISSUE TITLE
is there any twemoji picker?

### ISSUE THREAD

**Issue by deepinder10** [twitter/twemoji#279]
I want to implement twemoji on my site, but i am not able to find a emoji picker for this.

**Comment by katguzmann** [comment]
@deepinder10 you can use https://github.com/afeld/emoji-css/

**Comment by bhaggs** [comment]
Within the Twemoji project there is not a picker. But there are other community projects which have created pickers using the Twemoji set like EmojiPanel. https://github.com/danbovey/EmojiPanel

**Comment by kevinfaguiar** [comment]
For anyone that happens to read this issue, I've a implementation of emoji picker with Twemojis here (for the framework Vue): https://github.com/kevinfaguiar/vue-twemoji-picker

**Comment by deepinder10** [comment]
Well, I created one by myself using SVG sprites
https://medium.com/iamdeepinder/creating-a-twitter-like-emoji-picker-in-react-twemoji-with-svg-sprites-beb446a35ab8
