### ISSUE TITLE
Coffin emoji (U+26B0) uses strokes on the handles instead of fills

### ISSUE THREAD

**Issue by TheEssemCraft** [twitter/twemoji#280]
I was informed that v2.5 replaced many unnecessary strokes with fills, as well as some other things. However, it seems that the coffin emoji was overlooked, as the handles on it are strokes:

![image](https://user-images.githubusercontent.com/21112968/36690431-e6be87f4-1af7-11e8-929d-725323ff13e9.png)

This is annoying because a project I'm working on that uses Twemoji makes it look like this:

![image](https://user-images.githubusercontent.com/21112968/36690581-541fe81a-1af8-11e8-83c3-a1c646c538f6.png)

I suppose this could be fixed in a similar manner to how the hot dog emoji (U+1F32D) was fixed? I tried fixing it using Illustrator/svgo, but the diff between the SVG and the version generated by my project came out like this:

![image](https://user-images.githubusercontent.com/21112968/36729897-4cde5ca6-1b8b-11e8-8536-0206291e8318.png)

It's OK if you guys wait for a new version to fully release the fix, but I really need it ASAP, as it's the only thing holding my project back right now, and I can easily override the current SVG with the fixed one in the project.

**Comment by bhaggs** [comment]
Fixed in 2.5.1.
