### ISSUE TITLE
I created new flag and I applied UTF-16 to Twenoji's JS, but it doesn't load the icon. 

### ISSUE THREAD

**Issue by gusbemacbe** [twitter/twemoji#282]
1. I created a new flag of Spanish region of Catalonia icon (unavailable in the emoji fonts) and renamed it to 1f1e8-1f1f9, which came from the two letters 🇨and 🇹.
2. I converted 1f1e8-1f1f9 to `\ud83c\udde6\ud83c\uddf9` in UTF-16.
3. I added it to `'re'` from `twemoji` and also to, inside JavaScript script:

```javascript
twemoji.convert.fromCodePoint('1f1e8-1f1f9');
twemoji.convert.toCodePoint('\ud83c\udde6\ud83c\uddf9');
```
But it doesn't work and load the icon of new flag. 

Any solution?

**Comment by Kanjilearner817** [comment]
It isn't even an official ISO 3166-1 alpha-2 code. That may be why the icon didn't load.

**Comment by jmontane** [comment]
Hi, @gusbemacbe 

Unfortunately, Catalonia hasn't an own ISO 3166-1 code. In such cases, an [Emoji tag sequence](http://unicode.org/reports/tr51/#Sample_Valid_Emoji_Tag_Sequences) for country subdivisions can be used.

Following TR51, properly encoding for flag of Catalonia is: <U+1F3F4, U+E0065,󠁳 U+E0073,󠁣 U+E0063,󠁴 U+E0074, U+E007F>.

With [this commit](https://github.com/twitter/twemoji/commit/55443d4b393cfe8e5a8dfc967663f1e899f9c3f6#diff-ce40d9a4e0d264b94fe9f8bac66f9f96), 3 subdivision flags were added: England, Scotland, and Walles. See files:
- 1f3f4-e0067-e0062-e0065-e006e-e0067-e007f.png
- 1f3f4-e0067-e0062-e0073-e0063-e0074-e007f.png
- 1f3f4-e0067-e0062-e0077-e006c-e0073-e007f.png

See related WIP issue #233 also

Please, I want Catalan flag added in Twemoji. If I can help with anything, ask it. Thanks

**Comment by gusbemacbe** [comment]
Too bad, I wanted to add it to translate my Brazilian project into Catalan.

What @Liggliluff did is very nice.

**Comment by gusbemacbe** [comment]
@jmontane 

Herw is molt bones notícies!

In spite of not having Calan flag in the fonts...

I converted `1f3f4-e0065-e0073-e0063-e0074-e007f` to UTF-16: `\uD83C\uDFF4\uDB40\uDC65\uDB40\uDC73\uDB40\uDC63\uDB40\uDC74\uDB40\uDC7F` and added it to `'re'` from `twemoji.js` and I added the glyphs  🏴󠁥󠁳󠁣󠁴󠁿     to HTML. Finally it loaded the Catalan flah. Here's the result:

![screen shot 2018-03-09 at 05 32 58](https://user-images.githubusercontent.com/2257024/37198167-28fa4fd8-235c-11e8-949a-14efc913b768.png)

In the code source editor:

`twemoji.js`:

![screen shot 2018-03-09 at 05 39 44](https://user-images.githubusercontent.com/2257024/37198220-5d3cbd30-235c-11e8-8f1a-ac08031351ad.png)

`HTML`:

![screen shot 2018-03-09 at 05 39 31](https://user-images.githubusercontent.com/2257024/37198266-842878a8-235c-11e8-9adc-b88605e2847d.png)

Converting from HEX to UTF-16:

![screen shot 2018-03-09 at 05 42 25](https://user-images.githubusercontent.com/2257024/37198320-b1a835f2-235c-11e8-95d5-1e91f0989231.png)

Splitting two four letters in UTF-16:

![screen shot 2018-03-09 at 05 44 50](https://user-images.githubusercontent.com/2257024/37198433-08ca44e2-235d-11e8-8ea5-a662e4202289.png)

**Comment by jmontane** [comment]
Great!

Can you create a PR to Twemoji, please? 

I hope that flag from Catalonia will be part of Twemoji, like flag from Scotland.

**Comment by gusbemacbe** [comment]
@jmontane 

Yes, I can, but the problem is that the language and regional flags still aren't supported in the current Unicode or in the current emoji fonts, but as I am a typo-designer and programmer, I'll figure how they applied Great Britain countries to former Unicode firstly.

**Comment by jmontane** [comment]
Well, mixing languages and flags is an common use, but discouraged.

Said that, subdivision flags are fully supported by Unicode (see [Emojipedia post](https://blog.emojipedia.org/regional-flag-support-for-unicode-in-2017/) ). Only 3 subdivision flags are recommended by Unicode for now (England, Scotland, and Walles), but vendors can provide more flags following Unicode schema. So Twemoji can add any subdivision flag

**Comment by gusbemacbe** [comment]
Bon dia, @jmontane,

I read again and it makes sense what Unicode has suggested. 

I have just figured how they applied the British countries and understood now. I'll test with BirdFont.

**Comment by gusbemacbe** [comment]
@jmontane, altres molt bones notícies!

Finally the Catalan flag worked on an OTF (Glyphs.app) font, after testing four glyphs together (

🏴󠁥󠁳󠁣󠁴󠁿                

) with Firefox and with Unicode Checker, but not on a TTF font (BirdFont). I tried to export a colour emoji font in BirdFont, but it doesn't work because it doesn't know these glyphs. I'll report to @johanmattssonm.

**Comment by gusbemacbe** [comment]
The secret of these British flags are the ligature.

For any regional flag to work, you must use ligature.

For one colour emoji font to work on Google and as a web font, you need to use BirdFont.
For one colour emoji font to work on Apple, as an alternative to Apple Colour Emoji and on Windows, you need to use Glyphs. 
For one colour emoji font to work on Windows, you need to use FontCreator and Fontself. 

The example is EmojiOne which compiled its font to four type of color emoji font – Android, Apple, Windows and web font. EmojiOne is able to overwrite the original Apple Color Emoji.

**Comment by gusbemacbe** [comment]
You can try to test. Use Firefox. 

It comes with Glyphs and Birdfont files.

[CatalanEmoji.zip](https://github.com/twitter/twemoji/files/1796914/CatalanEmoji.zip)

**Comment by Jolg42** [comment]
Thanks for mentioning Fontself @gusbemacbe!

Just to make it clearer for the formats used,

Fontself for Illustrator is using:
- Regular OpenType CFF (outlines) for regular fonts & as a fallback if color fonts are not supported
- OpenType-SVG for color fonts

Fontself for Photoshop is using:
- Regular OpenType CFF (outlines) for regular fonts
- OpenType-SVG & Apple's sbix for color bitmap font.

So you can actually create a color bitmap font with Fontself and it will work on Apple's devices and also where OpenType-SVG is supported 😉

**Comment by gusbemacbe** [comment]
Salut, @Jolg42, how to set correctly the ligatures? And using glyph HEX codes? I tried to do in all forms.

**Comment by Alzavio** [comment]
Would this be possible to implement into the Tweomji repo, now that Wales has been supported since Sept. 2018?  Seems like @gusbemacbe  already did some of the work
