### ISSUE TITLE
Your Nepalese flag emoji is incorrect.

### ISSUE THREAD

**Issue by BlueNexus** [twitter/twemoji#287]
You're currently using this, apparently:
![](https://i.imgur.com/6RSJ29S.png)

The flag doesn't actually have that white there. It's just the coloured part.

![](https://www.theflagshop.co.uk/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/n/e/nepal-flag-std.jpg)

**Comment by TheEssemCraft** [comment]
Fixed as of version 2.4. I'm pretty sure that Discord uses an older version of Twemoji, so the fixes aren't in there yet.

**Comment by bhaggs** [comment]
Yup, fixed in 2.4 as @TheEssemCraft mentioned. Could also be that you're looking at Twemoji v1.0 assets as opposed to the v2 set.
