### ISSUE TITLE
This is unacceptable (:turtle:)

### ISSUE THREAD

**Issue by someponyy** [twitter/twemoji#288]
Tortoises live on land
Turtles live in water
WHY is the emoji :turtle: called "turtle" ? You can clearly see that the emoji represents the land type, so it's actually a TORTOISE and not a TURTLE. I hope you'll change the name of this emoji because it is terribly confusing.

**Comment by bhaggs** [comment]
Twemoji simply provides emoji artwork based on the Unicode emoji spec. Unicode defines the name, description, and keywords for an emoji. Your request would need to be taken up with the Unicode emoji subcommittee. 

From an artwork perspective, there seems to be broad consensus amongst emoji vendors of representing this emoji visually as a tortoise, so changing the artwork to represent a turtle instead could create cross platform inconsistencies. https://emojipedia.org/turtle/
