### ISSUE TITLE
Change the bomb emoji to a water baloon

### ISSUE THREAD

**Issue by CyberJeeb** [twitter/twemoji#289]
It needs to happen. The gun is now a water gun, what about the bomb!?

**Comment by Lubieerror** [comment]
And maybe fire (because you can "burn" someone) with... idk, maybe water? ;)

Meh, I never thought I'll ever be involved into politics basically when I open my keyboard.

**Comment by AIGRIND-LLC** [comment]
🍴🏹🔧🔨⚒🛠⛏🔪💣🔫🗡⚔️🚬💉✂️📍📌 - all this stuff need to be revised!

**Comment by cmakh** [comment]
While we're at it lets change the fork to a spork
