### ISSUE TITLE
Overwrite standard emoji in HTML?

### ISSUE THREAD

**Issue by xadz** [twitter/twemoji#294]
Hi, is there a way to overwrite standard Emojis in HTML with Twemoji for a consistent and nicer look?

Like EmojiOne can here: https://demos.emojione.com/latest/class-convert.html

For example emojis inserted in to HTML like this...

![screen shot 2018-06-08 at 16 19 14](https://user-images.githubusercontent.com/6561655/41166265-c29b045c-6b37-11e8-8e7e-5201b142fcbe.png)

I understand it won't change them in dev console but on the front-end!

Many thanks.

**Comment by WebReflection** [comment]
If I understand correctly what you are looking for, it's a bit like the ABC of this library since about ever 
https://github.com/twitter/twemoji#dom-parsing

```js
document.querySelectorAll('.convert-emoji').forEach(el => {
  twemoji.parse(el);
});
```
