### ISSUE TITLE
generate emoji regex from Twitter internal

### ISSUE THREAD

**Issue by sijad** [twitter/twemoji#295]
I've noticed you've switched to use a regex that generated in twitter internal c6611fd74ca57f8bc5eb937df4fd045241cd22ca, can you please provide the source code that we can be able to regenerate it?
I need to regenerate this regex for pcre which does not support `\uxxxx`.

**Comment by bhaggs** [comment]
@n8downs could you take a look into this?

**Comment by jdecked** [comment]
The regex generator was open-sourced in https://github.com/twitter/twemoji-parser/commit/66059e5da13a0407a49bdbe4b1980e00fcc92b62.
