### ISSUE TITLE
Where is the .svg file for the Tumbler Glass emoji?

### ISSUE THREAD

**Issue by jpmgoncalves** [twitter/twemoji#298]
I have downloaded the whole project and I haven't been able to find the .svg file for that specific twemoji.

**Comment by n8downs** [comment]
This one? https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f943.svg

**Comment by jpmgoncalves** [comment]
Oh, wow, I downloaded it and went through the folder twice myself and asked friends to confirm if it was there or not and no one was able to find the .svg file for it. 😅  Still, it would be great if twemojis related with a specific theme like jobs, or food, drinks, whatever, could be closer to each other.

Thanks!

**Comment by Crissov** [comment]
Do you realize the file names are based on the hexadecimal positions in Unicode? They are standardized and can be looked up rather easily, e.g. on Emojipedia.
