### ISSUE TITLE
Monochrome emoji?

### ISSUE THREAD

**Issue by speeditor** [twitter/twemoji#299]
A **monochrome emoji set** would be very nice for text-only emoji/fonts/iconography! (And maybe for web designers in other projects?)

Also, if these fit a custom grey palette of your own, that would be :100:

**Comment by youdly** [comment]
If you need it, I converted svg of v11.2 to b&w (using this [script](https://github.com/eosrei/twemoji-color-font/blob/master/Makefile#L106)). https://github.com/youdly/twemoji-color-font/tree/v11-release/assets/builds/svg-bw

**Comment by nektro** [comment]
```css
svg {
	filter: grayscale(100%);
}
```

**Comment by jdecked** [comment]
Sorry, but we won't be adding monochrome emoji. Feel free to do this via CSS as suggested above.
