### ISSUE TITLE
The emoji of Chinese flag(1f1e8-1f1f3) is wrong

### ISSUE THREAD

**Issue by hhhizzz** [twitter/twemoji#301]
this is Twemoji
![](https://emojipedia-us.s3.amazonaws.com/thumbs/120/twitter/141/flag-for-china_1f1e8-1f1f3.png)
This is apple emoji
![](https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/129/flag-for-china_1f1e8-1f1f3.png)
This is the Pic on the wiki
![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/900px-Flag_of_the_People%27s_Republic_of_China.svg.png)
The rotation of the small stars is wrong, according to the [WIki](https://en.wikipedia.org/wiki/Flag_of_China) 

>  Each of the top points of the 4 smaller stars are rotated such that they point towards the center point of the larger star.

**Comment by AlmightySosa** [comment]
+1 Good catch

**Comment by bhaggs** [comment]
Good find. We'll add it to our list for the next round of updates.

**Comment by bhaggs** [comment]
Fixed in the 11.1 release.
