### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by manib4u** [twitter/twemoji#302]
Hi! 

Can twemoji's be used as commercial game assets? Can these be remodeled, be it changing colors or add/delete features of individual emojis for more specific use? 

I did read the licensing terms, so attribution would be provided in the game description and also on screen before the game starts. 

Appreciate a brief response. Thank you! :)

**Comment by bhaggs** [comment]
As long as the proper attribution is provided in a publicly accessible way you should be all good.
