### ISSUE TITLE
Add support for ES6 browser import

### ISSUE THREAD

**Issue by lpellegr** [twitter/twemoji#303]
```
import './twemoji/2/twemoji.js';
import {twemoji} from './twemoji/2/twemoji.js';
```

**Comment by WebReflection** [comment]
those are not valid identifier for ESM

**Comment by lpellegr** [comment]
@WebReflection Thanks for raising the issue. I have updated the samples to make them ESM compliant (`./` was missing):

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by WebReflection** [comment]
In theory, once the CDN is purged with latest commit, you should be able to:

```js
import twemoji from 'https://twemoji.maxcdn.com/2/esm.js';
```

If this is good enough for everyone, I will ask to publish a new `package.json` with the `module` field pointing at `2/esm.js` so that you should be able to `import twemoji from "twemioji"` directly via package.json.

Please let me know how it goes once the CDN import works.

**Comment by lpellegr** [comment]
@WebReflection The import with your default export syntax works on my side. It would be great to have a package released on npmjs to simplify the integration with existing build processes.

**Comment by WebReflection** [comment]
so, everything seems to work fine. At this point, with latest non-breaking changes, whenever @n8downs would like to bump the library version (patch is fine) you should be able to `import twemoji from 'twemoji';` via the `npm` package.

**Comment by lpellegr** [comment]
@n8downs Any ideas when the package will be available on npmjs?

**Comment by fabiofcferreira** [comment]
Any updates so far. It's very annoying that you have to import this via HTML.

**Comment by WebReflection** [comment]
@fabiofcferreira which part is annoying? everything has been done in 2018 already, I just forgot to close this.

There are various ways to import twemoji described in this very same issue.
