### ISSUE TITLE
Add flags for the four countries that make up the UK.

### ISSUE THREAD

**Issue by squaredspekz** [twitter/twemoji#304]
I would like to be able to put the proper flags in chat, not just the Union Flag.

Wales, England, Scotland and Northern Ireland.

**Comment by n8downs** [comment]
These all exist in Twemoji
- https://emojipedia.org/flag-for-england/
- https://emojipedia.org/flag-for-wales/
- https://emojipedia.org/flag-for-scotland/

... you can find them in the assets by their codepoint sequences.

https://emojipedia.org/flag-for-northern-ireland-gbnir/ hasn't yet been recognized by Unicode (officially, Northern Ireland uses the Union Flag: https://en.wikipedia.org/wiki/Flag_of_Northern_Ireland), so it's not included in the Twemoji set.
