### ISSUE TITLE
Swap some of the smile emoji's around

### ISSUE THREAD

**Issue by refractionpcsx2** [twitter/twemoji#306]
Hey guys, 

I actually originally messaged the Discord people about this, asking if they could swap some of the smileys around as they don't seem to make sense to the smiles you make. They told me if I want them swapped around I need to contact you guys??

Ok here was the original message I sent to discord:

"Why does : ) point to : smiley : ? It looks FAR too happy for the original smile, it would be better having it point to : slight_smile : that is more fitting. : smiley : looks more like : D (also the : D smiley looks like it should be for xD also)
Would love you if you changed it <3"

I hope you guys will consider this, it looks like I'm being way too enthusiastic when doing : ) on discord lol

**Comment by bhaggs** [comment]
I think this actually may be a Discord issue, as they seem to be implementing a service which maps emoticons (e.g., :? ) to emojis. The Twemoji project provides 2 things, emoji artwork which corresponds to the Unicode emoji characters and a javascript library for replacing emoji character codepoints with those from the Twemoji set.

I'm not sure if Discord wrote their own tool for that mapping or their using some other open source library to do. But that would be up to them to change their mapping of an emoticon to a different emoji.

**Comment by refractionpcsx2** [comment]
OK no problem, thank you for the response, I'll go back to them :)
