### ISSUE TITLE
Add the orange_heart

### ISSUE THREAD

**Issue by SuperFola** [twitter/twemoji#308]
Since it's already available on Twitter, I think it would be great to add the orange_heart (I'm a discord user, and they are using Twemoji but the corresponding emoji isn't available).

Thank you for your work !

**Comment by raulriera** [comment]
The Orange heart is available, sounds like discord hasn't updated in a long time

**Comment by SuperFola** [comment]
Oh OK, I didn't find it, mea culpa c:
