### ISSUE TITLE
Lobster Image Leg Corrections

### ISSUE THREAD

**Issue by ancillaryallocation** [twitter/twemoji#309]
Hello: Two suggested changes to the image for the Lobster [(U+1F99E):](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f99e.svg)

1. Add another pair of legs in order to be anatomically correct. Lobsters have 10 legs (counting the claws, but not counting the antennae: [Wikipedia](https://en.wikipedia.org/wiki/Lobster)).
     a. Emojipedia [corrected their original image](https://blog.emojipedia.org/skateboard-dna-and-lobster-updated) to account for this
     b. Apple’s [preview ](https://blog.emojipedia.org/world-emoji-day-2018-first-look-at-apples-new-emojis)has 10 legs 
     c. Microsoft’s [preview](https://twitter.com/JenMsft/status/1022229747298754560/photo/1?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1022229747298754560) has 10 legs 
     d. Android’s [preview ](https://www.engadget.com/2018/06/06/google-android-p-beta-2-new-emoji/ )has 10 legs

2. Add a rounded end to the second leg on the right side. It appears to be the only leg that is squared off at the end, so I assume this was unintentional.

**Comment by bhaggs** [comment]
Yup, we've got both those items on our list and we've already made the updates. Will be included in our next batch of updates.

**Comment by ancillaryallocation** [comment]
Excellent. Thank you, @bhaggs.

**Comment by bhaggs** [comment]
Fixed in the 11.1 release.
