### ISSUE TITLE
Emojis missing?

### ISSUE THREAD

**Issue by chriswill0w** [twitter/twemoji#314]
are theses emojis missing?

1F9B0                                      ; fully-qualified     # 🦰 red-haired
1F9B1                                      ; fully-qualified     # 🦱 curly-haired
1F9B2                                      ; fully-qualified     # 🦲 bald
1F9B3                                      ; fully-qualified     # 🦳 white-haired

They are included in Unicode 11.0 as standalone emojis but seem to be missing from twemoji.

**Comment by bhaggs** [comment]
Added the missing hair component assets in the latest release.
https://github.com/twitter/twemoji/commit/6f3545b9649bba68ead0660328f318777c8a9416
