### ISSUE TITLE
Version numbers aligned with UTS#51

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#316]
Twemoji jumped from v2.*something* to v11.0 in order to align with the respective Unicode standard, UTS#51, which itself jumped from v5.0 to v11.0, aligning it with the version number of the main Unicode standard.

One problem with this is that there are now Twemoji releases v11.1 and v11.2, while there is no UTS#51 v11.1 nor v11.2, but there _could be_ such a dot release, e.g. for adding new ZWJ sequences without a need to wait for new code points being assigned. There actually will be a Unicode v11.1, probably, but no Emoji v11.1.

**Comment by bhaggs** [comment]
Given Unicode's generally annual release of new emojis, we felt that it would be best to align our main version number (11.x) with each annual Emoji release. This is primarily meant to be a quick shorthand to gauge what emoji support level is included in a major Twemoji release, and not specifically tied in lockstep with Unicode's more minor release numbers.

For reference on how we version Twemoji:
X.0: Major yearly release (typically new emojis added)
X.x: Visual changes to existing emojis supported
X.x.x: Minor bug fixes to code or assets
