### ISSUE TITLE
MaxCDN urls timing out

### ISSUE THREAD

**Issue by coryosborn** [twitter/twemoji#317]
Anyone else having issues with the maxcdn urls?  They all just started timing out for me in the last couple of hours.  I'm browsing from Seattle and I also get timeouts from my AWS servers in US-WEST-2 (Oregon).

```
xxxxxx@ip-x-x-x-xx ~ $ wget https://twemoji.maxcdn.com/twemoji.min.js
--2018-09-26 23:47:26--  https://twemoji.maxcdn.com/twemoji.min.js
Resolving twemoji.maxcdn.com (twemoji.maxcdn.com)... 151.139.237.197
Connecting to twemoji.maxcdn.com (twemoji.maxcdn.com)|151.139.237.197|:443... failed: Connection timed out.
Retrying.
```

**Comment by hunton** [comment]
Running into the same issue right now. I'm also browsing from Seattle, with others on my team in SF having similar problems. A coworker in New Zealand is loading just fine.

**Comment by virtue3** [comment]
Having an issue here with it in SF as well.  Seems to be ok via mobile networks tho.

**Comment by firebait** [comment]
Having the same problem.
