### ISSUE TITLE
Sizes 16x16 and 36x36 not available

### ISSUE THREAD

**Issue by maebert** [twitter/twemoji#32]
Even the size you use in your examples, https://abs.twimg.com/emoji/v1/36x36/2764.png, yields a broken image. However, https://abs.twimg.com/emoji/v1/72x72/2764.png works perfectly fine.

**Comment by t1gor** [comment]
I'm also having problem with flag emojis in sizes of 16x16 and 32x32. 

```javascript
/** Parse flag emojis for the country-list npm package */
const flag = twemoji.parse(countries[ISO].emoji, { size: '16x16'});
```

```html
<!-- Resulting HTML -->
<img class="emoji" draggable="false" alt="🇷🇸" src="https://twemoji.maxcdn.com/v/12.1.5/16x16/1f1f7-1f1f8.png"/>
```

And a call to [https://twemoji.maxcdn.com/v/12.1.5/16x16/1f1f7-1f1f8.png](https://twemoji.maxcdn.com/v/12.1.5/16x16/1f1f7-1f1f8.png) results in a 404. Is that expected?

**Comment by MithileshHinge** [comment]
Same issue as t1gor here.
