### ISSUE TITLE
Commercial goods?

### ISSUE THREAD

**Issue by hobbytechno** [twitter/twemoji#321]
Hi,
First my english is bad,

I want to know if I can use Twemoji for commercial goods (physical) or it's only for online?

If I can use it, I understand I need to write an attribution in an 'About' section. I checked example of CC but it look like if it's only for image use. If I made a product for Twemoji image can I write an attribution like this?: 

(1)-*My products name*, designs by Twemoji, graphics are licensed under the CC-BY 4.0-
(2)-This work, *my products names*, is a derivative of "Twemoji designs", used under CC-BY 4.0.-

If my right, which one is the best? And if im not right can you help me with the mention.

Thanks!

**Comment by Jagjeet** [comment]
Similarly, is it sufficient to place the attribution in the product description where a product is sold? I am curious for things like stickers, t-shirts, etc which may feature the images prominently but do not have a good location for attribution. 

If not, is it possible to license the images in a different manner for those types of uses?

**Comment by youdly** [comment]
@Jagjeet 
For clothing, I would imagine the attribution to be on the tag/care label. Even then, not all clothing has care label.

If I see a product with twemoji and it doesn't mention "Twitter" at all, I know it's not an official product of Twitter. Almost all products have a web page nowadays. Personally, if I'm a creator, I would request the user to at least print the product's URL (shorten if needed) on the product. The page would shows the product description and the necessary attribution.

**Comment by Jagjeet** [comment]
Thanks! Yeah, I am trying to do some hoodies and t-shirts printed on demand with a design using a few emojis. On the t-shirts, the print companies make it is pretty easy to do an inner label for that where adding attribution or a URL is easy enough. Legally in the US at least to my understanding, you have to do a care/sizing label as well, but it should be quick enough to design. For the hoodies, the print on demand options for inner labels seems more limited. That said, still evaluating if it would just be easier to design my own emoji-ish svgs for the few that I need to save on costs in the long term.

**Comment by vmasto** [comment]
Hi @youdly further question on licensing, in the hypothetical scenario where we want to use an emoji on a physical (purchased) postcard created via a mobile app (imagine a postcard template within an app where the user can write text which could contain emoji) would the attribution be sufficient in the app under the postcard template itself or would you require it on the printed material as well? Asking mainly because the Postcard is full-paper/print and quite inflexible so trying to understand options.

Thank you very much for your input in advance.
