### ISSUE TITLE
HTTP/2 on twemoji.maxcdn.com

### ISSUE THREAD

**Issue by neosilky** [twitter/twemoji#326]
According to #241, HTTP/2 should be enabled on MaxCDN but my tests say only HTTP/1.1 is showing up.

Would love it to be re-enabled.

![image](https://user-images.githubusercontent.com/964245/50720112-777ae080-10d9-11e9-9835-0a8cc7397645.png)

**Comment by neosilky** [comment]
Ping @WebReflection

**Comment by WebReflection** [comment]
not sure I even have access anymore there ...

**Comment by neosilky** [comment]
@WebReflection Do you know anyone who does? It'd be really great to get it fixed.

**Comment by Jetroid** [comment]
@WebReflection It'd be great to get this resolved - maxcdn is really hurting my website performance because of the 6 parallel connection limit and lack of connection multiplexing.

**Comment by neosilky** [comment]
(cc. @bhaggs)

**Comment by Fja1975** [comment]
Yea

**Comment by bhaggs** [comment]
Just enabled HTTP/2 on MaxCDN. @n8downs (engineering) and myself (design) are the current contributors from Twitter on this repo.
