### ISSUE TITLE
Emoji ZWJ Sequences for UTS #51 Support

### ISSUE THREAD

**Issue by doggy8088** [twitter/twemoji#327]
There is a [Emoji ZWJ Sequence](https://unicode.org/Public/emoji/11.0/emoji-zwj-sequences.txt) defined in Unicode.  Is **twemoji** going to support this?

**Comment by bhaggs** [comment]
Could you provide more specifics as to which ZWJ is in question?

**Comment by doggy8088** [comment]
Here are some examples:

1. 👨‍👩  
   ![image](https://user-images.githubusercontent.com/88981/52607413-16e97b00-2eb1-11e9-94eb-be3120094b37.png)

    ```js
    var man = '👨';
    var women = '👩';

    var zwj = '\u200D';

    console.log(man + zwj + women);
    ```

2. 👨‍👩‍👦
   ![image](https://user-images.githubusercontent.com/88981/52607439-2bc60e80-2eb1-11e9-8121-843493d46677.png)

    ```js
    var man = '👨';
    var women = '👩';
    var child = '👦';

    var zwj = '\u200D';

    console.log(man + zwj + women + zwj + child);
    ```

3. 👨‍👩‍👧
   ![image](https://user-images.githubusercontent.com/88981/52607447-31235900-2eb1-11e9-9a86-ca86b2730dd4.png)

    ```js
    var man = '👨';
    var women = '👩';
    var child = '👧';

    var zwj = '\u200D';

    console.log(man + zwj + women + zwj + child);
    ```

4. 👨‍👩‍👦‍👧
   ![image](https://user-images.githubusercontent.com/88981/52607455-384a6700-2eb1-11e9-8d4b-dbb55c106aa0.png)

    ```js
    var all = ['👨', '👩', '👦', '👧'];
    var zwj = '\u200D';
    console.log(all.join(zwj));
    ```

5. 👨‍👨‍👦‍👧
   ![image](https://user-images.githubusercontent.com/88981/52607476-3f717500-2eb1-11e9-96dc-c2831eb3c29d.png)

    ```js
    var all = ['👨', '👨', '👦', '👧'];
    var zwj = '\u200D';
    console.log(all.join(zwj));
    ```js

6. 👩‍👩‍👦‍👧
   ![image](https://user-images.githubusercontent.com/88981/52607485-44cebf80-2eb1-11e9-8ffc-0fed6ee7843f.png)

    ```js
    var all = ['👩', '👩', '👦', '👧'];
    var zwj = '\u200D';
    console.log(all.join(zwj));
    ```

7. 👨🏻‍👩🏿‍👦‍👧
   ![image](https://user-images.githubusercontent.com/88981/52607495-4a2c0a00-2eb1-11e9-98f9-78e82f0d90a0.png)

    ```js
    var fitz1 = '\uD83C\uDFFB';
    var fitz6 = '\uD83C\uDFFF';

    var all = ['👨'+fitz1, '👩'+fitz6, '👦', '👧'];
    var zwj = '\u200D';
    console.log(all.join(zwj));
    ```

**Comment by jdecked** [comment]
We recently updated to support all sequences laid out by UTS 51.

**Comment by doggy8088** [comment]
Hi @jdecked , this is a case that is not working. https://codepen.io/willh/pen/Baoxbxx
