### ISSUE TITLE
how to convert an image into emojis ?

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [twitter/twemoji#333]
Is it possible to convert my image into emoji and use it for twitter emoji marketing purposes ?

**Comment by n8downs** [comment]
To create a new emoji, you'll need to have it accepted by the Unicode Consortium: http://unicode.org/emoji/proposals.html

If you're referring to the images that sometimes follow hashtags on Twitter, you should go through https://business.twitter.com

**Comment by ZaheerAbbasAghani** [comment]
Thanks
