### ISSUE TITLE
Skin tones missing for Handshake and some other emojis?

### ISSUE THREAD

**Issue by djrocher** [twitter/twemoji#334]
Hello Twemoji staff,

thanks for your great and continuous work! I'm using Twemoji v11.3 and noticed that some skin tones are missing (referring to the .png files in twemoji/2/72x72/, without checking the .svg files). This also was the case in versions prior to v11.3.

Example: 

Handshake: 1f91d.png (neutral skin tone) = available

Handshake, Type-1-2 (light skin tone) = not available, although Emojipedia shows the Twemoji version (https://emojipedia.org/handshake-type-1-2/).

The same accounts for: 
Handshake, Type-3 (https://emojipedia.org/handshake-type-3/)
Handshake, Type-4 (https://emojipedia.org/handshake-type-4/)
Handshake, Type-5 (https://emojipedia.org/handshake-type-5/)
Handshake, Type-6 (https://emojipedia.org/handshake-type-6/)

Another emoji is Men Wrestling: the neutral skin tone is available (1f93c.png and 1f93c-200d-2642-fe0f.png), the skin tones are missing.

Are they really missing or simply not provided for these emojis?

**Comment by Crissov** [comment]
see #192

Unicode has still not agreed upon a solution for this. <http://www.unicode.org/review/pri392/>

**Comment by bhaggs** [comment]
Yup, until we get some better guidance from Unicode we'll keep it as is.
