### ISSUE TITLE
How should I support Typescript?

### ISSUE THREAD

**Issue by Teeoo** [twitter/twemoji#340]
`
Could not find a declaration file for module 'twemoji'. '/Users/lee/Desktop/graphql/node_modules/twemoji/2/twemoji.npm.js' implicitly has an 'any' type.
  Try `npm install @types/twemoji` if it exists or add a new declaration (.d.ts) file containing `declare module 'twemoji';`
`

**Comment by WebReflection** [comment]
> How should I support Typescript?

You could file a PR that adds an `emoji.d.ts` file that shows all informations already available as JSDoc in the source code https://github.com/twitter/twemoji/blob/gh-pages/2/twemoji.js
