### ISSUE TITLE
how to convert :heart: to heart emoji?

### ISSUE THREAD

**Issue by supertiger1234** [twitter/twemoji#342]

**Comment by Teeoo** [comment]
```javascript
twemoji.parse(":heart:");
```

**Comment by supertiger1234** [comment]
Tried that, doesn't work. It just returns :heart: back.

**Comment by supertiger1234** [comment]
> ```js
> twemoji.parse(":heart:");
> ```

Tried that, doesn't work. It just returns ":heart:"

**Comment by supertiger1234** [comment]
> > > ```js
> > > twemoji.parse(":heart:");
> > > ```
> > 
> > 
> > Tried that, doesn't work. It just returns `":heart:"`
> 
> Returned heart Is it a picture or a string? You can find the emoji you need [here](https://twitter.github.io/twemoji/preview.html).

Well, I want it to happen dynamically  in a text area (just like discord)

**Comment by nektro** [comment]
Use this to replace names with unicode: https://github.com/muan/emojilib/blob/master/emojis.json

Then use twemoji to replace unicode with pictures.

**Comment by supertiger1234** [comment]
Thanks! But I already figure it out ages ago. I should've closed the issue, sorry!
