### ISSUE TITLE
Licensing and Copyrighting 

### ISSUE THREAD

**Issue by MsGarnerAETENLLC** [twitter/twemoji#348]
So if I'm doing a TV documentary on social media and use Twemoji? I just use the attribution in the end credits? or a special thanks?

Copyright 2019 Twitter, Inc and other contributors Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by bhaggs** [comment]
The end credits would be an appropriate place to include attribution.
