### ISSUE TITLE
Add a persistent Github logo on website navbar

### ISSUE THREAD

**Issue by co16353sidak** [twitter/twemoji#350]
I really like the concept of this library and what it provides to developers, the website too looks lovely.
I feel that the website nabber though looks quite empty at the top, on the right side there could be an addition of a GitHub logo or a link that redirects to the main GitHub repo.
I know it might sound redundant because there are links present in the middle sections when you scroll down the page, but it is sometimes very helpful if there is a quick navigation link present in the navbar itself.
<img width="1276" alt="Screenshot 2019-04-14 at 10 06 35 PM" src="https://user-images.githubusercontent.com/35738138/56096115-94595800-5f01-11e9-9e05-1b9bb2877255.png">
Would be an amazing new addition to the otherwise very nice and clean website.
(Also if you guys agree to this, I would to contribute on this as my first issue here 🥇)

**Comment by bhaggs** [comment]
Thanks for the feedback. Agreed that would be useful. Unfortunately that site is built using a pre-defined theme for Twitter's marketing sites which doesn't allow for one-off adjustments to the navigation structure.

**Comment by co16353sidak** [comment]
@bhaggs  Really interested what the the theme is? maybe I could work on this issue there ?
