### ISSUE TITLE
Preview.html is missing

### ISSUE THREAD

**Issue by DavidLibeau** [twitter/twemoji#366]
6e153daedcfe60ca2438adb642ffbd2403a762a9 removed `preview-svg.html` and `preview.html` : http://twitter.github.io/twemoji/2/test/preview.html

**Comment by n8downs** [comment]
Ah good catch, thank you! That was not intentional. I've restored the files: https://github.com/twitter/twemoji/commit/b14bab860ae3a91f8e1ef0a23942794060d6cc11
