### ISSUE TITLE
Calendar Emoji User Expectation Mismatch

### ISSUE THREAD

**Issue by JHerculesTwitter** [twitter/twemoji#368]
On Apple Emoji pickers (both in collapsed view and the Character Viewer) the calendar emoji (📅and 📆) display an arbitrarily-chosen date (the 17th day of the month). When selecting this emoji and inputting it into the Rweb composer, the calendar emoji displayed shows a different number (the 21st day of the month).

<img width="688" alt="Screen Shot 2019-07-17 at 1 07 38 PM" src="https://user-images.githubusercontent.com/53020203/61409564-5de00000-a897-11e9-9dd3-25383f0a69ab.png">

A user expecting to compose a tweet expecting the number 17 or the calendar emoji with a 17 in it will not expect the change to 21. While Twitter [has its reasons](https://emojipedia.org/calendar/) for this easter egg, and while it is not the only platform that changes the number within the emoji, the reasoning for this change is similarly arbitrary to a user, and breaks the expectation that the user's intended input will match Twitter's output.

Issue originally raised by:
https://twitter.com/ikasliwal/status/1151554010282725377
https://twitter.com/ikasliwal/status/1151548939234996225

**Comment by nektro** [comment]
The calendar is always on world emoji day.

![image](https://user-images.githubusercontent.com/5464072/80540917-36ff4000-8978-11ea-830b-d6ff897d408b.png)

**Comment by jdecked** [comment]
We're looking into changing this, especially as Google has adopted July 17th as their calendar date too.

**Comment by jdecked** [comment]
Resolved in v13.0.1.
