### ISSUE TITLE
Transgender Flag emoji is in Twemoji, but not other Unicode 13.0 Draft Candidates?

### ISSUE THREAD

**Issue by MudkipLegend** [twitter/twemoji#379]
Hi, I noticed that the Unicode 13.0 draft candidate for the Transgender Flag emoji (U+1F3F3 FE0F 200D 26A7 FE0F) has been in Twemoji for a few months now, but the other draft candidates have not yet been added. Can someone artistically-savvy please add the other Unicode 13.0 draft emojis to Twemoji? Thanks!

For reference:

All Unicode 13.0 Emoji Draft Candidates: https://unicode.org/emoji/future/emoji-candidates.html 

Unicode 13.0 Character Database: https://unicode.org/Public/13.0.0/ucd/ 

Unicode 13.0 Emoji Data: https://unicode.org/Public/13.0.0/ucd/emoji/ 

Emoji character pipeline: https://unicode.org/alloc/Pipeline.html

**Comment by n8downs** [comment]
Yeah, we added the trans flag and trans symbol to Twemoji ahead of their approval to celebrate Pride month this year.

We'll be working on the rest of the new emojis once 13.0 gets closer to approval, and usually have them out shortly after they become official. Stay tuned!
