### ISSUE TITLE
Cricket emoji is brown and unreadable.

### ISSUE THREAD

**Issue by JeremyGDiamond** [twitter/twemoji#381]
The cricket emoji is a dark brown color instead of the archetypal green. This makes it hard to read on small screens and easily mistaken for other emoji like the poop. These issues are compounded by the use of dark mode. Can the svg files be edited to change the color pallet?

**Comment by jdecked** [comment]
Thanks for bringing this up. We're looking into revising the colors here.

**Comment by pbeart** [comment]
![image](https://user-images.githubusercontent.com/8270128/89056353-cd664780-d353-11ea-9725-63796c66ed57.png)![image](https://user-images.githubusercontent.com/8270128/89056377-d5be8280-d353-11ea-8c73-9e03592a6d36.png)
(Current cricket emoji displayed on light and dark background for reference). I'd agree that the colours make it hard to interpret.

**Comment by Mennaruuk** [comment]
I agree. Kinda hard to see.

**Comment by jdecked** [comment]
This has been fixed in [v13.0.2](https://github.com/twitter/twemoji/releases/tag/v13.0.2).
