### ISSUE TITLE
:heart: showing up as grey 

### ISSUE THREAD

**Issue by DracoClaw** [twitter/twemoji#383]
So, a rep at Discord said that my issue of the heart emoji being grey and not red is through you. Im trying to have a set of hearts, but the first on just shows up grey. ❤🧡💛💚💙💜
![Capture](https://user-images.githubusercontent.com/34274162/67887998-010e0a00-fb55-11e9-8132-965f65445524.PNG)

**Comment by bhaggs** [comment]
While Discord does use Twemoji (though it's a much older version), based on your screenshot it looks like you're seeing Microsoft's emojis. 

https://emojipedia.org/microsoft/
