### ISSUE TITLE
12.2 release?

### ISSUE THREAD

**Issue by birarda** [twitter/twemoji#385]
We just updated to 12.1.3 but were disappointed at the lack of gender inclusive emoji where gender is not specified. It looks like that is the focus of 12.2, which is great to see!

https://emojipedia.org/twitter/twemoji-12.2/

I was surprised to see that come up only on Emojipedia. Should we expect to see 12.2 released here shortly?

**Comment by bhaggs** [comment]
Yup, we are working on them and will have them up soon.

**Comment by birarda** [comment]
12.1.4 just came out and addresses this. Thanks!
