### ISSUE TITLE
Nepali flag  wrong emoji

### ISSUE THREAD

**Issue by Pratap2019** [twitter/twemoji#386]
🇳🇵 ,This is still wrong Nepali emoji we use, everywhere. Is it impossible to make proper Nepali Flag in emoji ,its quite challenging for developers, but we don't wanted to use it . Our flag have tri angles not rectangular in shape.

**Comment by n8downs** [comment]
The most recent version of the Nepali flag: https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f3-1f1f5.png seems to be made up of triangles. Can you elaborate on how it's incorrect? 

Perhaps you're using an older version of Twemoji?

**Comment by Pratap2019** [comment]
yeah , this one is correct one , but why still now we are using wrong one i.e mobile devices,social medias etc. & how to update it.

**Comment by n8downs** [comment]
Got it. To update, you'll want to make sure your website uses `<script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>` or your `package.json` points to the latest version on `npm` (currently 12.1.3).
