### ISSUE TITLE
twemoji-parser 12.1.1 dependency

### ISSUE THREAD

**Issue by birarda** [twitter/twemoji#388]
yarn install for the 12.1.1 release fails on the Twemoji-parser 12.1.1 dependency

Possibly related, looks like an internal URL got committed as the `resolved` attribute when the dependency was updated.

https://github.com/twitter/twemoji/blob/670538f18e6b32b4dc16ef4e17c4301b2273f422/yarn.lock#L970

**Comment by birarda** [comment]
I'm guessing this is just some CDN propagation issue as you've just published both. It's not related to the internal resolved URL above since I can't do a simple `yarn install twemoji-parser@12.1.1`.

**Comment by n8downs** [comment]
Thanks for catching this! Fixed in https://github.com/twitter/twemoji/commit/b4385ddc160552b118169c76a1414cae907d9621
