### ISSUE TITLE
Jigsaw emoji too closely resembles the Autism Speaks logo

### ISSUE THREAD

**Issue by Quinnlyn** [twitter/twemoji#390]
The colour of this emoji almost perfectly matches the colour and shape of the logo used by controversial advocacy group "Autism Speaks". This is an organization that has been largely denounced and discredited by the greater autism and mental health communities. 

I'm not going to delve into their full history but there is a[ brief summary on Wikipedia ](https://en.wikipedia.org/wiki/Autism_Speaks#Controversies). They have a long and disgusting history of everything from electroshock torture to mental abuse to, up until recent years, anti-vaxx stances.

On every other platform this emoji is represented in a very different colour (orange for Android, green for iOS) but under Twemoji this is almost a 1:1 replica of the AS logo. Please consider changing the colour.

Edit: Looking into the version history for this emoji reveals that previous versions of jigsaw literally used to be the AS logo. Like literally a copy-paste. The current version is a revision but it needs to go further. Please change the colour.

**Comment by theautherside** [comment]
Can we please not just change the color, but replace it entirely to the rainbow infinity symbol that represents Neurodiversity? If you must have a puzzle piece it should a different shape and color so it does not in any way intend to represent the Autistic community, nor be used by other to represent us. We find this symbol deeply offensive and we are tired of others telling us to just calm down and sit down to be told who and what we are. Please listen.

**Comment by Crissov** [comment]
@theautherside The Jigsaw Puzzle Piece emoji should of course show a jigsaw puzzle piece. Personally, I donʼt care much about its shape, color or texture.

**Comment by jdecked** [comment]
The jigsaw/puzzle piece emoji is now green.
