### ISSUE TITLE
Don't change the frog emoji

### ISSUE THREAD

**Issue by kassindornelles** [twitter/twemoji#392]
Please, don't do it, it is super special for me and a lot of people and i know you guys are making lots of changes in the emojiset, just please keep the frog the same forever

**Comment by Joshua-Ashton** [comment]
**Example of correct behaviour:**
![frog](https://user-images.githubusercontent.com/21316711/69078204-42485a00-0a2f-11ea-9f29-6ebbc1d3b2c7.png)

**Comment by kassindornelles** [comment]
We even built frog emoji variants, we love frogs!

![image](https://user-images.githubusercontent.com/40970965/69078260-3ef4a480-0a16-11ea-88f2-a4b8274a02ef.png)

**Comment by BieHDC** [comment]
> We even built frog emoji variants, we love frogs!
> 
> ![image](https://user-images.githubusercontent.com/40970965/69078260-3ef4a480-0a16-11ea-88f2-a4b8274a02ef.png)

You should officially submit all the frogs here so the whole world can share the joy.

**Comment by Joshua-Ashton** [comment]
They are available here https://git.froggi.es/Riesi/frog_emojis

**Comment by rphsoftware** [comment]
Leave the frogs alone

**Comment by GloriousEggroll** [comment]
SAVETHEFROGS

**Comment by jdecked** [comment]
Keeping the frog emoji The Same, Forever™ is quite a tall order. It's the same for now. I can't promise that we'll never change it ever, but I hope any future versions will live up to the same fun aesthetic.

**Comment by kassindornelles** [comment]
Thank you Justine!
Much love from the Frog Family <3 🐸
