### ISSUE TITLE
Eyes emoji revert / revision

### ISSUE THREAD

**Issue by GlitchyPSIX** [twitter/twemoji#393]
The old eyes (:eyes:) emoji used to look very solid, compared to the newer version. Something about their appearance (especially the pupils) makes them look... off -- for lack of a better word -- and takes out some of the personality Twemoji had compared to other emoji sets such as Whatsapp's or Apple's. This has been pointed out by many users as soon as Discord updated their Twemoji pack, and some after Twitter did.

My personal thoughts on this... one could even make some sort of mixture between both eye designs, and do something like [this](https://imgur.com/a/pYk1OdK)
(I cannot contribute; I don't have AI, only Inkscape)

**Comment by gburgwardt** [comment]
Agreed, the new eyes suck

**Comment by Nekkowe** [comment]
Strongly agree, the new eyes look demonstrably worse and tend to make people uncomfortable.
The old ones were perfectly fine.

**Comment by jdecked** [comment]
Sorry, we have no plan to rework the new eyes emoji.

**Comment by Nekkowe** [comment]
Out of curiousity, why mess it up to begin with?

**Comment by jdecked** [comment]
This may be hard to believe but, to some people, this is an improvement — it's marginally more realistic, with an iris and light reflecting off it. I don't have context on why this specific change was made, but ever so often we do refresh the design of our emoji, for reasons that vary with the times.

Personally, I neither find the new version creepier, nor a substantial improvement.

**Comment by Nekkowe** [comment]
I see!
