### ISSUE TITLE
many neutral-gender emojis are missing

### ISSUE THREAD

**Issue by roipoussiere** [twitter/twemoji#394]
I extracted the list of all emoji that are part of emoji 12.1 (based [on this list](https://unicode.org/Public/emoji/12.1/emoji-test.txt)) but not on Twemoji.

It seems that all of them are the neutral-gender version of existing emoji in both genders.

For instance, there is:
- [man singer](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f468-200d-1f3a4.png) (`1f468-200d-1f3a4`)
- [woman singer](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f469-200d-1f3a4.png) (`1f469-200d-1f3a4`)
- ...but not singer (`1f9d1-200d-1f3a4`)

Do you have any plans to include them in a next release?

Complete list:
- `person: red hair`
- `person: light skin tone, red hair`
- `person: medium-light skin tone, red hair`
- `person: medium skin tone, red hair`
- `person: medium-dark skin tone, red hair`
- `person: dark skin tone, red hair`
- `person: curly hair`
- `person: light skin tone, curly hair`
- `person: medium-light skin tone, curly hair`
- `person: medium skin tone, curly hair`
- `person: medium-dark skin tone, curly hair`
- `person: dark skin tone, curly hair`
- `person: white hair`
- `person: light skin tone, white hair`
- `person: medium-light skin tone, white hair`
- `person: medium skin tone, white hair`
- `person: medium-dark skin tone, white hair`
- `person: dark skin tone, white hair`
- `person: bald`
- `person: light skin tone, bald`
- `person: medium-light skin tone, bald`
- `person: medium skin tone, bald`
- `person: medium-dark skin tone, bald`
- `person: dark skin tone, bald`
- `health worker`
- `health worker: light skin tone`
- `health worker: medium-light skin tone`
- `health worker: medium skin tone`
- `health worker: medium-dark skin tone`
- `health worker: dark skin tone`
- `student`
- `student: light skin tone`
- `student: medium-light skin tone`
- `student: medium skin tone`
- `student: medium-dark skin tone`
- `student: dark skin tone`
- `teacher`
- `teacher: light skin tone`
- `teacher: medium-light skin tone`
- `teacher: medium skin tone`
- `teacher: medium-dark skin tone`
- `teacher: dark skin tone`
- `judge`
- `judge: light skin tone`
- `judge: medium-light skin tone`
- `judge: medium skin tone`
- `judge: medium-dark skin tone`
- `judge: dark skin tone`
- `farmer`
- `farmer: light skin tone`
- `farmer: medium-light skin tone`
- `farmer: medium skin tone`
- `farmer: medium-dark skin tone`
- `farmer: dark skin tone`
- `cook`
- `cook: light skin tone`
- `cook: medium-light skin tone`
- `cook: medium skin tone`
- `cook: medium-dark skin tone`
- `cook: dark skin tone`
- `mechanic`
- `mechanic: light skin tone`
- `mechanic: medium-light skin tone`
- `mechanic: medium skin tone`
- `mechanic: medium-dark skin tone`
- `mechanic: dark skin tone`
- `factory worker`
- `factory worker: light skin tone`
- `factory worker: medium-light skin tone`
- `factory worker: medium skin tone`
- `factory worker: medium-dark skin tone`
- `factory worker: dark skin tone`
- `office worker`
- `office worker: light skin tone`
- `office worker: medium-light skin tone`
- `office worker: medium skin tone`
- `office worker: medium-dark skin tone`
- `office worker: dark skin tone`
- `scientist`
- `scientist: light skin tone`
- `scientist: medium-light skin tone`
- `scientist: medium skin tone`
- `scientist: medium-dark skin tone`
- `scientist: dark skin tone`
- `technologist`
- `technologist: light skin tone`
- `technologist: medium-light skin tone`
- `technologist: medium skin tone`
- `technologist: medium-dark skin tone`
- `technologist: dark skin tone`
- `singer`
- `singer: light skin tone`
- `singer: medium-light skin tone`
- `singer: medium skin tone`
- `singer: medium-dark skin tone`
- `singer: dark skin tone`
- `artist`
- `artist: light skin tone`
- `artist: medium-light skin tone`
- `artist: medium skin tone`
- `artist: medium-dark skin tone`
- `artist: dark skin tone`
- `pilot`
- `pilot: light skin tone`
- `pilot: medium-light skin tone`
- `pilot: medium skin tone`
- `pilot: medium-dark skin tone`
- `pilot: dark skin tone`
- `astronaut`
- `astronaut: light skin tone`
- `astronaut: medium-light skin tone`
- `astronaut: medium skin tone`
- `astronaut: medium-dark skin tone`
- `astronaut: dark skin tone`
- `firefighter`
- `firefighter: light skin tone`
- `firefighter: medium-light skin tone`
- `firefighter: medium skin tone`
- `firefighter: medium-dark skin tone`
- `firefighter: dark skin tone`
- `person with probing cane`
- `person with probing cane: light skin tone`
- `person with probing cane: medium-light skin tone`
- `person with probing cane: medium skin tone`
- `person with probing cane: medium-dark skin tone`
- `person with probing cane: dark skin tone`
- `person in motorized wheelchair`
- `person in motorized wheelchair: light skin tone`
- `person in motorized wheelchair: medium-light skin tone`
- `person in motorized wheelchair: medium skin tone`
- `person in motorized wheelchair: medium-dark skin tone`
- `person in motorized wheelchair: dark skin tone`
- `person in manual wheelchair`
- `person in manual wheelchair: light skin tone`
- `person in manual wheelchair: medium-light skin tone`
- `person in manual wheelchair: medium skin tone`
- `person in manual wheelchair: medium-dark skin tone`
- `person in manual wheelchair: dark skin tone`

**Comment by n8downs** [comment]
Yep, they're coming soon.

**Comment by roipoussiere** [comment]
Ok, thank you!
