### ISSUE TITLE
Why some twemojis are not part of the Unicode's emoji list?

### ISSUE THREAD

**Issue by roipoussiere** [twitter/twemoji#395]
These twemojis are not listed in emoji 12.1 (based on [this list](https://unicode.org/Public/emoji/12.1/emoji-test.txt)).

Why? Twemoji is not supposed to follow official emoji list from Unicode?

- [1f1ff](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ff.png)
- [1f574-1f3fb-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fb-200d-2642-fe0f.png)
- [1f574-1f3fd-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fd-200d-2640-fe0f.png)
- [26f7-1f3fe](https://github.com/twitter/twemoji/blob/master/assets/72x72/26f7-1f3fe.png)
- [1f1f5](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f5.png)
- [1f1ea](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ea.png)
- [1f1ef](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ef.png)
- [1f1e6](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1e6.png)
- [1f1fd](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1fd.png)
- [1f935-1f3fc-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fc-200d-2640-fe0f.png)
- [1f1ec](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ec.png)
- [1f935-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-200d-2640-fe0f.png)
- [1f935-1f3fc-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fc-200d-2642-fe0f.png)
- [1f935-1f3fd-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fd-200d-2642-fe0f.png)
- [1f1e8](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1e8.png)
- [1f935-1f3fe-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fe-200d-2640-fe0f.png)
- [26a7](https://github.com/twitter/twemoji/blob/master/assets/72x72/26a7.png)
- [1f574-fe0f-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-fe0f-200d-2640-fe0f.png)
- [1f574-1f3fc-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fc-200d-2640-fe0f.png)
- [1f1eb](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1eb.png)
- [1f935-1f3fd-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fd-200d-2640-fe0f.png)
- [1f1f9](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f9.png)
- [e50a](https://github.com/twitter/twemoji/blob/master/assets/72x72/e50a.png)
- [1f935-1f3fb-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fb-200d-2640-fe0f.png)
- [1f1f2](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f2.png)
- [1f935-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-200d-2642-fe0f.png)
- [1f1ed](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ed.png)
- [1f3f3-fe0f-200d-26a7-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f3f3-fe0f-200d-26a7-fe0f.png)
- [1f935-1f3fe-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fe-200d-2642-fe0f.png)
- [1f574-fe0f-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-fe0f-200d-2642-fe0f.png)
- [1f1f6](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f6.png)
- [1f574-1f3ff-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3ff-200d-2640-fe0f.png)
- [1f1fe](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1fe.png)
- [1f1f7](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f7.png)
- [1f935-1f3ff-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3ff-200d-2640-fe0f.png)
- [1f574-1f3fd-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fd-200d-2642-fe0f.png)
- [1f935-1f3fb-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3fb-200d-2642-fe0f.png)
- [1f574-1f3ff-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3ff-200d-2642-fe0f.png)
- [1f1f8](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f8.png)
- [1f1f0](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f0.png)
- [1f1fc](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1fc.png)
- [26f7-1f3fb](https://github.com/twitter/twemoji/blob/master/assets/72x72/26f7-1f3fb.png)
- [1f1e9](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1e9.png)
- [1f1fb](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1fb.png)
- [1f1f4](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f4.png)
- [1f1f1](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f1.png)
- [1f574-1f3fb-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fb-200d-2640-fe0f.png)
- [26f7-1f3fc](https://github.com/twitter/twemoji/blob/master/assets/72x72/26f7-1f3fc.png)
- [1f1f3](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1f3.png)
- [1f574-1f3fc-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fc-200d-2642-fe0f.png)
- [1f935-1f3ff-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f935-1f3ff-200d-2642-fe0f.png)
- [1f574-1f3fe-200d-2640-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fe-200d-2640-fe0f.png)
- [1f1e7](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1e7.png)
- [1f1ee](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1ee.png)
- [26f7-1f3fd](https://github.com/twitter/twemoji/blob/master/assets/72x72/26f7-1f3fd.png)
- [26f7-1f3ff](https://github.com/twitter/twemoji/blob/master/assets/72x72/26f7-1f3ff.png)
- [1f1fa](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f1fa.png)
- [1f574-1f3fe-200d-2642-fe0f](https://github.com/twitter/twemoji/blob/master/assets/72x72/1f574-1f3fe-200d-2642-fe0f.png)

**Comment by anarchodin** [comment]
Presumably this explains at least some of them:

> This includes the emoji components that need emoji presentation (skin tone and hair) when isolated, but omits the components that need not have an emoji presentation when isolated.

**Comment by Kenyon-J** [comment]
There are many emojis that have an ISO code but are not included in RGI (Recommended for General Interchange), it's not a requirement to follow this list to the book and emojis can be added and removed dependant on usage requirements, the inclusion of emoji letters such as Z and J should be non trivial
