### ISSUE TITLE
This emoji 🧑🏾‍💻 can't display correctly on version 12.1.4

### ISSUE THREAD

**Issue by Mrooze-zeng** [twitter/twemoji#396]
I enter this emoji 🧑🏾‍💻 with iPhone keyboard, but it displays like as follow:
![🧑🏾‍💻](https://user-images.githubusercontent.com/22336049/70219225-64f0a780-177f-11ea-8907-6fc7340720d7.jpg)
and on the console, the message shows as follow:
![🧑🏾‍💻2](https://user-images.githubusercontent.com/22336049/70219276-82be0c80-177f-11ea-8acc-e53eed137490.jpg)

It seems this emoji 🧑🏾‍💻 can't be matched by the RegExp. Can anybody help me with it?

**Comment by makepanic** [comment]
According to emojipedia this is currently only supported by apple, see https://emojipedia.org/technologist/

**Comment by Mrooze-zeng** [comment]
@makepanic Is there any way to display this emoji directly?

**Comment by n8downs** [comment]
We'll have support for the gender neutral occupations (including this one) coming soon.

**Comment by bhaggs** [comment]
This now renders correctly with the v12.1.5 release.
