### ISSUE TITLE
The emoji "flag_gb" should be renamed to "flag_uk".

### ISSUE THREAD

**Issue by aerophobes** [twitter/twemoji#398]
The emoji flag_gb contains the flag of Northern Ireland, which is not in Great Britain.
The flag this emoji has should rather be named to "flag_uk" which is the correct name for it.

**Comment by Crissov** [comment]
<http://en.wikipedia.org/wiki/ISO_3166-2:GB>

**Comment by nektro** [comment]
http://unicode.org/Public/emoji/13.0/emoji-test.txt
`1F1EC 1F1E7              ; fully-qualified     # 🇬🇧 E0.6 flag: United Kingdom`

**Comment by nektro** [comment]
`1F3F4 E0067 E0062 E0065 E006E E0067 E007F  ; fully-qualified     # 🏴󠁧󠁢󠁥󠁮󠁧󠁿 E5.0 flag: England
1F3F4 E0067 E0062 E0073 E0063 E0074 E007F  ; fully-qualified     # 🏴󠁧󠁢󠁳󠁣󠁴󠁿 E5.0 flag: Scotland
1F3F4 E0067 E0062 E0077 E006C E0073 E007F  ; fully-qualified     # 🏴󠁧󠁢󠁷󠁬󠁳󠁿 E5.0 flag: Wales`
