### ISSUE TITLE
Request: Add support for cultural/languages communities flags

### ISSUE THREAD

**Issue by jmontane** [twitter/twemoji#40]
Hi,

currently only country flags are supported by Twitter. I mean only ISO 3166 registrered codes are supported using Unicode Regional Indicator Symbols (RIS). There are very active online communities without an own independent country and some support for their flags should be done.

For example, you can take Welsh, Scottish and Catalan communities. These 3 communities are very active and they achieve an own TLD (.cymru, .scot and .cat). Other communites, like Basque and Gallician have own TLD too (.eus and .gal).

As a remark, some "ISO 3166 country" flags collection, like famfam [1] add few "extra" flags for these communities.

I think flags for these communities should be supported by Twitter. An easy way is extending Unicode Regional Indicators Symbols. For instance, if a cultural/language TLD is typed with Unicode RIS, then show the flag for these culture/language:

🇸🇨🇴🇹 --> it shows Scottish flag
🇨🇾🇲🇷🇺 --> it shows a Welsh flag
🇧🇿🇭 --> it shows a Breton flag
🇨🇦🇹 --> it shows Catalan flag
🇪🇺🇸 --> it shows a Basque flag
🇬🇦🇱 --> it shows a Gallician flag

Thanks,

[1] http://www.famfamfam.com/archive/flag-icons-released/

**Comment by WebReflection** [comment]
is this mentioned in/part of the Unicode standard?

**Comment by jmontane** [comment]
Unicode standard only talks about pair of RIS [1] (i.e. ISO 3166 country codes) :(

May be Twitter can propose an extension of TR 51 [1] to RIS strings (2 or more characters) for cultural TLDs

[1] http://www.unicode.org/reports/tr51/tr51-1.html#Flags

**Comment by WebReflection** [comment]
I might try to ask about this in the unicode ML but I'd say it's out of twemoji scope to promote new features to standards ... it's already not so easy to respect current one closely, if we start accepting any sort of request/variant as twemoji bug you can imagine how this repository would look like, I am sure you understand what I am saying :)

Let's see what's the outcome from the ML.

**Comment by jmontane** [comment]
Yes, I understand it, but its a vicious circle (chicken and egg situation).

Manufacturers don't implemented such feature because its isn't in Unicode standard. And Unicode doesn't describe it because manufacturers don't implement it.

So we (users) request to manufacturers (Twitter in this case) with the hope standard will be improved, :)

Thanks for your help.

**Comment by WebReflection** [comment]
my only concern is that once this goes in, everyone could claim its own community flag, one per domain. What do you think would be a good filter to avoid such situation?

**Comment by jmontane** [comment]
Unicode doesn't set which country flags are shown as emojis. It's a manufacturer choice which 2 letter country codes has an emoji! Unicode only provides an standard encoding (RIS). So, a manufacturer can choice implement only 10 country flags, and an other one implements all ISO 3166 list.

So, with cultural/languages TLD the same approach can be done. IANA provides approved domain list, some of them are for cultural/language communities. Manufacturers can choice implement emojis for all, few or none of these domains.

**Comment by WebReflection** [comment]
I'd like to underline interoperability, plus the effort/tim required from the designer that eventually will implement extra flags, plus the fat this project follows a standard, it does not promote new.

So, again, I might try to ask in Unicode M: the current status about this, but I am not the only one involved here so I am not sure if that will happen any time soon.

**Comment by jmontane** [comment]
I understand it, and I thank you for your collaboration and help.

Flags are always an issue, yes. But they are something important for users, :)

**Comment by WebReflection** [comment]
from the Unicode ML
> This does not work. The "Unicode RIS" are defined to be used in pairs, with semantics according to corresponding ISO 3166 alpha2 codes. In your examples, each successive pair will encode a flag.
>
> If you want to represent every flag of every locality, you first have to figure out how to catalog and label them. You are mentioning provinces, one level down from nation states; I guess there are thousands of them. In much of Europe, every little village has its own flag and coat of arms. Where do you want the text encoding and fonts to stop?

Which matches somehow my first concern. I think this feature-request/issue should be discussed first in Unicode ML for the simple reason the standard needs to be championed and it should have reusable rules for all cases. This proposal, as it is, is not portable/compatible with its own goal.

I am going to close this for now, feel free to add more if necessary.
Thanks for the hint in any case, appreciated.
