### ISSUE TITLE
BEAN EMOJI

### ISSUE THREAD

**Issue by beanemojidiscord** [twitter/twemoji#409]
omg coronavirus will eat me if i dont get bean emoji pls help discord add it right now or i will eat bacon egg sandwich

![beanemoji](https://user-images.githubusercontent.com/62062082/76419205-04da5480-63b1-11ea-9c65-8e4a2c413097.png)

here is crude drawing of bean hope u like it and see the use of it in discord

**Comment by TNThacker2015** [comment]
What is this? Bean emojis aren't part of the official unicode standard.

**Comment by IamRifki** [comment]
Can someone close this troll issue?

**Comment by Crissov** [comment]
Bean has been proposed thrice and has finally been added to the list of shelved emojis that might be added solutions at the discretion of the Unicode Consortium, which might be never.
https://unicode.org/emoji/emoji-requests.html

**Comment by jdecked** [comment]
As lovely a bean drawing as that is, there's no bean emoji in the Unicode standard, so closing this.
