### ISSUE TITLE
Support 13.0

### ISSUE THREAD

**Issue by tkrunning** [twitter/twemoji#410]
Hi, will Twemoji add support for 13.0 soon? Currently a lot of the emojis on my site are broken since I use a Jekyll plugin that already updated the links according to the new standard (I assume this is the issue at least).

E.g. the Emoji plugin I use tries to load https://twemoji.maxcdn.com/v/latest/svg/1f3db-fe0f.svg for :classical_building:, but Twemoji only has https://twemoji.maxcdn.com/v/latest/svg/1f3db.svg, and so on.

**Comment by joostvdh-concapps** [comment]
Would be nice to have 13.0 support soon, but your example is unrelated. It's actually an 0.7 emoji.

1f3db-fe0f is the same emoji as 1f3db, however only the latter exists as an image in Twemoji. This is true for a lot of images, so you probably need to fix the plugin for that.

**Comment by jdecked** [comment]
Thanks for stopping in with the appropriate answer @joostvdh-concapps. We've got 13.0 support now, though! 😄 Closing.
