### ISSUE TITLE
Portugal flag incorrect

### ISSUE THREAD

**Issue by HVEVB** [twitter/twemoji#414]
The Portugal flag is incorrect, the top right line is messed up

https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f1f5-1f1f9.svg

**Comment by jdecked** [comment]
We're working on fixing this, but PRs welcome if you can do it quicker. Thanks for reporting.

**Comment by HVEVB** [comment]
I don't know how to do it unfortunately

**Comment by MyriaCore** [comment]
@HVEVB AFAIK, changing the artwork yourself and submitting a PR should be sufficient. So:
1. Fork this repo
2. Make a new branch in your fork specifically for this issue, name it something like `portugal-flag-fix`
3. Open up `assets/svg/1f1f5-1f1f9.svg` with inkscape or adobe illustrator, or any program capable of editing svg images
4. Correct the error. It looks like you could just make the top-right line a bit longer. 
5. Save it, and render a 72x72 png version into `assets/72x72/1f1f5-1f1f9.png`. 
6. Profit!

**Comment by HVEVB** [comment]
I tried opening it up in vectr, but it really didn't like that. Hence why I said I didn't know how to do it. PRs themselves I do know how to do 😃

I'll try the programs suggested tomorrow, thanks

**Comment by conorhennessy** [comment]
I see some comments were made over the weekend about this! 
I don't mean to steal the task from @HVEVB but over the weekend, in fact, I fiddled with this and fixed it. I'll make a pull request now. 😄 🇵🇹 

 @HVEVB I can show you how to do it too and/or how to make a PR, if you wish, so you know how to contribute in the future? 🚀

**Comment by HVEVB** [comment]
I'm happy you fixed it 😉 I think I can figure out how to do it though, but thanks for the offer. I'll close the issue when the PR is merged

**Comment by jdecked** [comment]
This has been fixed in [v13.0.2](https://github.com/twitter/twemoji/releases/tag/v13.0.2).

**Comment by desrosj** [comment]
I was looking into exactly what had changed in the Emoji for v13.0.2 and noticed the SVG in the original report links to the primary branch, which now shows the corrected Emoji.

I just wanted to add a link to a previous version of the flag for anyone looking to see what the original issue was: https://raw.githubusercontent.com/twitter/twemoji/v12.1.6/assets/svg/1f1f5-1f1f9.svg.
