### ISSUE TITLE
Convert :heart: to ❤️

### ISSUE THREAD

**Issue by sparkaccounts** [twitter/twemoji#417]
I'm trying to implement this to my chat site, but I have no idea how, I'm thinking that when the message is sent it will display `:heart:` as ❤️ and other emojis.

**Comment by WebReflection** [comment]
it feels like you're missing an emoji picker (listed in the README) ... emoticons are not part of any unicode standard, one site could go `:heart:` while another one could go `<3` ... it's up to you parse those text either on the fly, or afterword, by crawling text nodes and replacing your "_shortcut_" with any emoji you like.
