### ISSUE TITLE
error while updating a video 

### ISSUE THREAD

**Issue by i-waves** [twitter/twemoji#418]
I get the below error exception when I try to update a video 

Error updating user video metadata.
Code: BadRequest
Message: {"invalid_parameters":[{"field":"privacy.download","error_code":2204,"error":"You have provided an invalid parameter. Please contact developer of this application.","developer_message":"The parameters passed to this API endpoint didn't pass Vimeo's validation. Please check the invalid_parameters list for more information."}],"error":"You have provided an invalid parameter. Please contact developer of this application.","link":null,"developer_message":"The parameters passed to this API endpoint didn't pass Vimeo's validation. Please check the invalid_parameters list for more information.","error_code":2204}

==============
I use the below code and my package is basic 

 await Client.UpdateVideoMetadataAsync((long)uploadRequest.ClipId, new VideoUpdateMetadata()
                            {
                                Privacy = VimeoDotNet.Enums.VideoPrivacyEnum.Anybody,
                                EmbedPrivacy = VimeoDotNet.Enums.VideoEmbedPrivacyEnum.Whitelist,
                                AllowDownloadVideo = false,
                                AllowAddToAlbumChannelGroup = false,
                                ReviewLinkEnabled = false,
                                Comments = VimeoDotNet.Enums.VideoCommentsEnum.Nobody,
                                Name = VideoTitle.Trim(),
                                Description = VideoDescription.Trim()
                            });

**Comment by HVEVB** [comment]
How is this related to Twemoji?

**Comment by jdecked** [comment]
Seems like you've filed this issue to the wrong GitHub project.
