### ISSUE TITLE
List of Supported Emoji

### ISSUE THREAD

**Issue by nunoperalta** [twitter/twemoji#424]
Do you provide (or can this be a suggestion of) a list of supported Emojis?

Ideally, organized by the following categories:

Smileys & People
Animals & Nature
Food & Drink
Activity & Sport
Travel & Places
Objects
Symbols
Flags

The only list I could find is this:

https://emojipedia.org/twitter/

I parsed all the HTML into code points, and had to do some manual organization, since this list isn't 100% organized (but at least is ~80%).

Would definitely be nice to have some JSON in the Git repository which I could just use to populate the list of Emoji on my site :)

From that Emojipedia list, I noticed it has the following emoji in the list:
265f - https://emojipedia.org/chess-pawn/

But when I do twemoji.parse(), it does not seem to parse into an image (just shows the default Windows 10 emoji).

**Comment by MyriaCore** [comment]
AFAIK, twemoji officially supports Unicode's Emoji v13 set of emojis. A more complete listing emojis in Emoji v13 are available on unicode.org, particularly in 2 lists:
- [Normal Emojis](https://unicode.org/emoji/charts/full-emoji-list.html)
- [Modifier-based emojis](https://unicode.org/emoji/charts/full-emoji-modifiers.html) (like the skin tone variants, gendered variants, etc). 

These lists seem to be reasonably scrapable, and conform to the categories you want. Here's some scraping advice to get you started:
- Table rows with an actual emoji in them will always have a `<td class="code">` child (which is the cell that has the unicode codepoint for the emoji). 
- Table rows that hold the header for your categories will always have a `<th class="bighead">` child (which is the actual table header).
- There are occasionally table rows that don't have useful info to the scraper, like [the row just above this emoji](https://unicode.org/emoji/charts/full-emoji-list.html#1f9d1_200d_1f9b2), which just re-displays the column labels for human-readable convenience., or like [this weird sub-section header](https://unicode.org/emoji/charts/full-emoji-list.html#body-parts). You'll probably want to make sure these don't get scooped up and treated as valid data.
