### ISSUE TITLE
Package source files when publishing to NPM

### ISSUE THREAD

**Issue by ranisalt** [twitter/twemoji#431]
Hi, I want to use the source of the icons for a tool, however, the NPM package does not contain the sources, only the final script. I guess you probably did this to avoid shipping a lot of files with the package, but that's an issue my bundler would deal with. Please include the SVG files with the package, or at least provide a separate package with the sources.

Thanks! Great job.

**Comment by Menci** [comment]
You can use https://www.npmjs.com/package/@discordapp/twemoji, which forked this repo and added the SVG files back.

**Comment by jdecked** [comment]
Thanks for chiming in with an alternative @Menci; closing this since we don't plan to bundle the SVG files with the package.
