### ISSUE TITLE
209 New Emoji Flags

### ISSUE THREAD

**Issue by shield-9** [twitter/twemoji#44]
209 new flags are added to Unicode as a new emoji. And Android Lollipop supports them.
Why don't you support them?

For reference: http://blog.emojipedia.org/209-new-emoji-flags-available-today

**Comment by WebReflection** [comment]
the TL;DR answer would be time ... designers time. But yes, these should be relatively "easy" to implement, thanks for the heads-up.

**Comment by kkirsche** [comment]
Is there any interest in having flags added as pull requests even if not all 209 flags are implemented in a single PR or would you need them all to accept any?

**Comment by WebReflection** [comment]
no idea, I need some designer jumping in for this

**Comment by kkirsche** [comment]
I mean, this isn't hard and I can certainly design the flag icons easily for this. I just want to make sure it would be something of interest / that would be accepted before putting in the obvious time commitment to start adding these

**Comment by WebReflection** [comment]
I understand, and all I can say is that if you PR some designer will eventually review it and either accept them or discard them. I'll try to put @caniszczyk in the loop ;-)

**Comment by kkirsche** [comment]
Ah oh. Sorry, I must have misread the first one. Thanks for your time on this :+1:

**Comment by kkirsche** [comment]
Just wanted to follow up on this. Thanks!

**Comment by kkirsche** [comment]
Following up on this again

**Comment by kkirsche** [comment]
Follow up on this again.

**Comment by wp9015362** [comment]
> @shield-9 wrote:
> 
> For reference: http://blog.emojipedia.org/209-new-emoji-flags-available-today

Another set has received some new additional flags now, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Regards

**Comment by rodrigopolo** [comment]
I have created a library which depends on SVGs from this library and I have upgraded the library to support the latest unicode emojis that are already available on iOS8.3 but I can't find many new emojis on this library.

Here is the project:
https://github.com/rodrigopolo/minEmoji

I'm currently using all PNGs I found on the Apple font in this versions:
http://rodrigopolo.github.io/minEmoji/jMinEmoji2/demo.html
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

So, anyone know when new pictures will be available?

Thanks!

**Comment by WebReflection** [comment]
3 identical posts ... please do not use opened bugs to promote your library. I am going to remove all of your 3 posts. Eventually feel free to ask a question in one place, or open a new bug. Thank you

**Comment by rodrigopolo** [comment]
@WebReflection I'm not promoting anything, I just increasing the probabilities of getting an answer, I was about to open a request (bug) asking for this new emojis but then I found there were 3 bug reports that essentially ask for the same thing (I'll consider merging them if you ask me), so, I'm not earning money nor "internet points", I'm not trolling or doing something bad to some one, just looking for some SVGs to do what exactly people need. I'll share the URL again NOT to promote but to get anyone interested into seeing that it is a real working library:
https://github.com/rodrigopolo/minEmoji

**Comment by kkirsche** [comment]
I gotta agree with @rodrigopolo here @WebReflection — not like this has exactly been getting responses from Collabs and admins even after asking. If you guys won't answer / help we gotta look elsewhere

**Comment by rodrigopolo** [comment]
Thanks @kkirsche, BTW do you know who exactly created the SVGs found in this library? I have read all over the repo without finding the credit of that specific person or team.

**Comment by WebReflection** [comment]
@kkirsche if you repeatdly copy and paste the same thing everywhere there are no higher chances to get any answer, it's rather annoying. There is now a specific ticket and that's all it's needed.

Once again I'm not the designer, I'm an external collaborator that takes care of the JS part, the RegExp, and few other bits ... everything but assets. I don't have these answers, that's why I keep waiting same as you.

@rodrigopolo the SVG is created at runtime from AI files. The procedure is automated. There won't be ever any sprite because it'd be too heavy for no gain. Stats clearly show people use only few common emoji, providing a sprite with all of them is an unnecessary amount of (paid in some case) bandwidth nobody should waste. It's good there are alternatives though, but having that huge SVG with PNG images in it makes little if no sense at all to me but again, here the responsible for SVG is called [Inkscape](https://inkscape.org/en/).

**Comment by rodrigopolo** [comment]
@WebReflection Thanks, I use both approaches, separately imgs/svgs and sprites in the latest code I released and I told the exactly same thing you have stated:

https://github.com/rodrigopolo/minEmoji/tree/master/jMinEmoji2

I have an option for loading each SVG separately and that is exactly why I'm looking for this new SVGs, thanks again.

**Comment by rmccue** [comment]
Looks like these are available on Twitter: https://abs.twimg.com/emoji/v1/72x72/1f1e6-1f1fa.png

Any plans to bring those across to twemoji? :)

**Comment by bhaggs** [comment]
Yup, we'll be bringing over the full set once we complete them, still in progress at this time.

**Comment by jerrygrey** [comment]
Can't wait :smile:

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.
