### ISSUE TITLE
fully supporting Mahjong Tiles Unicode block?

### ISSUE THREAD

**Issue by roytam1** [twitter/twemoji#442]
I wonder if there is a plan to support all code points in U+1F000..U+1F02F, not only U+1F004?

**Comment by Crissov** [comment]
Microsoft has colorful glyphs for the whole block, but they are not _recommended for general interchange_ as emojis by Unicode, so other vendors are avoiding to add them. In my not so humble opinion, all playing cards and chess pieces should also be available as emojis.

**Comment by Liggliluff** [comment]
If Twemoji starts supporting them, and they get some more use on Twitter, Discord and other platforms using Twemoji, we might see a change in other vendors starting to support them?

**Comment by Crissov** [comment]
We definitely would. Unfortunately, all vendors are now waiting for Unicode’s recommendations first before shipping emoji glyphs. 

The most recent exception was the Transgender Flag which was a steigend sequences under discussion, but not yet recommended, when vendors like Facebook and Whatsapp already started supporting it.

**Comment by jdecked** [comment]
For now we're sticking to the emoji marked as Recommended for General Interchange. We don't currently have a plan to deviate from that except for a handful of important exceptions (such as the Transgender Flag). Maybe that will change in the future, but I doubt it.
