### ISSUE TITLE
How to render it in my web pages?

### ISSUE THREAD

**Issue by kafinsalim** [twitter/twemoji#443]
I don't get the readme, I use an emoji picker library on my web but when I search for new version 13 emoji, the emoji picker doesn't have that.
My goal is to have an emoji picker that has new version 13 emoji on my web like those https://blog.emojipedia.org/117-new-emojis-in-final-list-for-2020/. Could twemoji help that?

**Comment by jdecked** [comment]
Hello @kafinsalim, Twemoji could help with the version 13 emoji, but note that we do not provide an emoji picker. All we provide is the emoji. Depending on how you are building your website, perhaps we have a community project that suits your needs, such as [Vue Twemoji Picker](https://github.com/kevinfaguiar/vue-twemoji-picker).
