### ISSUE TITLE
Some emojis NOT vertically middle aligned

### ISSUE THREAD

**Issue by Menci** [twitter/twemoji#445]
Such as the fish: https://cdn.jsdelivr.net/npm/@discordapp/twemoji@13.0.1/dist/svg/1f41f.svg

![](https://cdn.jsdelivr.net/npm/@discordapp/twemoji@13.0.1/dist/svg/1f41f.svg)

There's a lot white space on the top.

**Comment by AbyssStudios** [comment]
Maybe because the fish is underwater? But yes, I do think we should fix it. Could you give me a list of all of the emojis that need to be fixed? I could make a pull request with all of those.￼

**Comment by Menci** [comment]
Currently I only found this one.

**Comment by jdecked** [comment]
For the fish emoji, this is intentional.
