### ISSUE TITLE
Are parsed Strings fully escaped?

### ISSUE THREAD

**Issue by TRiBotWillB** [twitter/twemoji#446]
I'm adding a basic chat to my site, I need to ensure that if a user enters a script tag that XSS will be prevented. Usually I would escape this myself but can't because of the images, does the parse function escape all other input?

Thanks

**Comment by TRiBotWillB** [comment]
In face I have just noticed that the user can input an image of their own, any way around this?

**Comment by WebReflection** [comment]
you need to escape your own content, it's not this library responsibility to do that, this library searches for emojis and replace these with images. You can escape your input, inject it as HTML after escaping, and use this library to target the node/container/document to replace emoji only after via its DOM tree parser, which doesn't handle strings.

However, you can also pass an already escaped string to this library before injecting the content, so you are the one in charge of avoiding XSS, although XSS via scripts are not even possible anymore, as `innerHTML` doesn't evaluate scripts, but random images with `onload` or `onerror` events are, indeed, a possible attack vector, so escape first, then use twemoji.

Escaping in twemoji will result in double escaping for already escaped content, and server side usually *always* escape content that is meant to be injected, so watch out your server side too.

Closing this as I don't think there's anything to do in here, but I hope I've answered.
