### ISSUE TITLE
Cat face emojis have slightly different eye, mouth, and teeth coloration from equivalent generic face emojis

### ISSUE THREAD

**Issue by ncrecc** [twitter/twemoji#449]
![image](https://user-images.githubusercontent.com/11216597/99915551-60940600-2cd2-11eb-9381-bf6fc42663a0.png)
Normal cat emoji included for reference.

Cat eye/mouth is solid black, generic eye/mouth is dark brown. Teeth on cat faces are also a very light gray (F5F8FA) rather than solid white. All other colors that represent the same facial features are identical - skin/fur color, tears on crying faces, blank pupils and hands on screaming face, hearts on heart-eyed face. The cat faces are already different in proportions and mouth color from the generic cat emoji, so changing their colors to match the generic faces shouldn't be too big a deal.

Rough mockup of cat faces with colors changed to match:
![image](https://user-images.githubusercontent.com/11216597/99915727-59212c80-2cd3-11eb-97f4-72eea3f7275b.png)

**Comment by davidlwpblo** [comment]
> ![image](https://user-images.githubusercontent.com/11216597/99915551-60940600-2cd2-11eb-9381-bf6fc42663a0.png)
> Normal cat emoji included for reference.
> 
> Cat eye/mouth is solid black, generic eye/mouth is dark brown. Teeth on cat faces are also a very light gray (F5F8FA) rather than solid white. All other colors that represent the same facial features are identical - skin/fur color, tears on crying faces, blank pupils and hands on screaming face, hearts on heart-eyed face. The cat faces are already different in proportions and mouth color from the generic cat emoji, so changing their colors to match the generic faces shouldn't be too big a deal.
> 
> Rough mockup of cat faces with colors changed to match:
> ![image](https://user-images.githubusercontent.com/11216597/99915727-59212c80-2cd3-11eb-97f4-72eea3f7275b.png)

The reason why I haven't replied is because this conversation kind of feel familiar from someone I know or associated with and I don't know

**Comment by jdecked** [comment]
This is intentional.
