### ISSUE TITLE
Links generated by parse method don't work with not default size

### ISSUE THREAD

**Issue by iShaVas** [twitter/twemoji#450]
**Describe the bug**
If size is not 72x72, links return 404

**To Reproduce**
1. try to parse text with emojis: `twemoji.parse(content)`
2. It will return correct link like [https://twemoji.maxcdn.com/v/13.0.1/72x72/1f914.png](https://twemoji.maxcdn.com/v/13.0.1/72x72/1f914.png)
3. now set twemoji size: `twemoji.size = '16x16';`
4. try to parse text with emojis: `twemoji.parse(content)`
5. It will return incorrect link like [https://twemoji.maxcdn.com/v/13.0.1/16x16/1f914.png](https://twemoji.maxcdn.com/v/13.0.1/16x16/1f914.png)

**Comment by WebReflection** [comment]
size should be a number, not a string
https://github.com/twitter/twemoji/blob/master/scripts/build.js#L553

**Comment by iShaVas** [comment]
> size should be a number, not a string
> https://github.com/twitter/twemoji/blob/master/scripts/build.js#L553

I also tried to set `twemoji.size = '16';` and use `twemoji.parse(content, {size: 16})`

**Comment by WebReflection** [comment]
actually, a string should work too, I stand corrected:
https://github.com/twitter/twemoji/blob/master/scripts/build.js#L509-L521

have you tried this instead?
```js
twemoji.parse(content, {size: '36x36'})
```

also bear in mind I am not sure the CDN provides assets for all sizes

**Comment by WebReflection** [comment]
actually, reading your steps, everything works as expected, [the size](https://github.com/twitter/twemoji#size) is meant to address the folder, not the image size, fo rthe image size, you need to use CSS as explained in the README
https://github.com/twitter/twemoji#tips

closing this as the behavior is expected
