### ISSUE TITLE
Unable to download high resolution pngs

### ISSUE THREAD

**Issue by kokanek** [twitter/twemoji#451]
**Is your feature request related to a problem? Please describe.**
I have cloned the repo and have also tried to build the repo to generate the twemoji. But its just generating small 72x72 size emojis. Any way to create larger 512x512 pngs?

**Describe the solution you'd like**
Need a way to generate higher resolution twemojis.

**Describe alternatives you've considered**
have tried by changing the default resolution in script. Does not seem to work.

**Additional context**
Please let me know if any online resource is available which might let me download all the twemojis in high quality format. That would suffice too!

**Comment by WebReflection** [comment]
there are svg assets here, which scale up to any resolution ... why isn't that an option?

**Comment by jdecked** [comment]
The only PNGs we provide are 72x72 PNGs. For custom sizes, consider using the SVG assets, or generating PNGs of your desired size from these SVG assets.
