### ISSUE TITLE
Attribution question regarding print to pdf web pages

### ISSUE THREAD

**Issue by leighmcculloch** [twitter/twemoji#456]
Hi! The readme of this project is very helpful regarding how to appropriately attribute twemoji within things like web pages where it is noted that it is acceptable to include mention in the HTML or source code where a developer can publicly see the attribution but a user does not see it. How should attribution be made for HTML pages that are also printed to PDF. Does attribution need to be made in such a way that when printed to PDF the PDF contains the attribution on the page?

**Comment by moonjae** [comment]
sdfsdfsdf

**Comment by jdecked** [comment]
Hey @leighmcculloch, if you haven't already figured this out, perhaps the [Creative Commons wiki](https://wiki.creativecommons.org/Best_practices_for_attribution) could help you here.

**Comment by davidlwpblo** [comment]
> Hi! The readme of this project is very helpful regarding how to appropriately attribute twemoji within things like web pages where it is noted that it is acceptable to include mention in the HTML or source code where a developer can publicly see the attribution but a user does not see it. How should attribution be made for HTML pages that are also printed to PDF. Does attribution need to be made in such a way that when printed to PDF the PDF contains the attribution on the page?



> Hi! The readme of this project is very helpful regarding how to appropriately attribute twemoji within things like web pages where it is noted that it is acceptable to include mention in the HTML or source code where a developer can publicly see the attribution but a user does not see it. How should attribution be made for HTML pages that are also printed to PDF. Does attribution need to be made in such a way that when printed to PDF the PDF contains the attribution on the page?

Thank you
