### ISSUE TITLE
Optional inclusion of emoticons/ascii emojis when converting to image

### ISSUE THREAD

**Issue by pederjohnsen** [twitter/twemoji#458]
Are there any plans to add an option to also include emoticons/ascii emoji when converting to to images?
For the time being I'll be adding a small script to do this outside of tweemoji, but think it could be a nice addition to the tweemoji lib

**Comment by jdecked** [comment]
Not at the moment, and probably not in the future either. Our focus is providing support for emoji defined in the Unicode standard, which regrettably doesn't include any ASCII equivalents.

**Comment by pederjohnsen** [comment]
Fair enough :)
