### ISSUE TITLE
Release installable emoji font

### ISSUE THREAD

**Issue by darkRaspberry** [twitter/twemoji#461]
**Is your feature request related to a problem? Please describe.**
I want to use this emoji as font. so that i can render it in any way like terminal or vscode.

**Describe the solution you'd like**
Build .ttf files or the similar which facilitate installations

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by Crissov** [comment]
SBIX, COLR, CBDT, SVG or a combination thereof?

**Comment by darkRaspberry** [comment]
i guess glyph.
> SBIX, COLR, CBDT,
Sorry i don' t understand these three.

I want anything which is a install-able font file like--.tff or .otf
Which can be install system-wide like windows or linux. so that it can be rendered everywhere on the os

**Comment by Crissov** [comment]
There are four color font variants included in the OpenType format now. 

For the SVG variant, the readme already links to <https://github.com/eosrei/twemoji-color-font>.

**Comment by darkRaspberry** [comment]
nice i got the ttf from  https://github.com/mozilla/twemoji-colr .
You can close this issue. Thanks

**Comment by AndroidDeveloperLB** [comment]
Any news about this? 
I use the one of Mozilla, but it hasn't been updated for years, and it also has issues [with digits](https://github.com/mozilla/twemoji-colr/issues/56)...

How can I get the latest, yet small version of this font, that handles only emojis?
