### ISSUE TITLE
Thai flag proportions are incorrect

### ISSUE THREAD

**Issue by Paul012** [twitter/twemoji#463]
The proportions of the Thai flag ([1f1f9-1f1ed](https://github.com/twitter/twemoji/blob/master/assets/svg/1f1f9-1f1ed.svg)) are incorrect. The height of the stripes should be in a 1:1:2:1:1 ratio, not 2:2:5:2:2 as currently done.

**Comment by ChiefMikeK** [comment]
Please refer to [File:Flag of Thailand.svg - Wikipedia](https://commons.wikimedia.org/wiki/File:Flag_of_Thailand.svg)
![Thailand-flag](https://user-images.githubusercontent.com/20070053/109394725-5a8c7180-7920-11eb-8867-c0857ec75e0a.png)  
:neckbeard:

**Comment by jdecked** [comment]
This has been fixed in [v13.0.2](https://github.com/twitter/twemoji/releases/tag/v13.0.2).
