### ISSUE TITLE
Add this to Gem Plugin

### ISSUE THREAD

**Issue by Vyshnav2255** [twitter/twemoji#470]
**Is your feature request related to a problem? Please describe.**
It will be easier to implement this in Jekyll if it is a plugin.

**Describe the solution you'd like**
Converting Twemoji into a jekyll plugin.

**Describe alternatives you've considered**

**Additional context**

**Comment by jdecked** [comment]
Twemoji intends to serve many different use cases. Jekyll is but one use case. We won't be turning this into a Jekyll plugin ourselves, but feel free to fork and create your own Twemoji Jekyll plugin. We'll be happy to link to it in the README.
