### ISSUE TITLE
Unicode 8.0 Support

### ISSUE THREAD

**Issue by pento** [twitter/twemoji#48]
With Apple announcing imminent support for Unicode 8.0 emoji, it seems like we'll need support for it sooner than when the Unicode 8.0 spec is due to be finalised.

Do you folks have any plans for implementing this, or how to tackle the various parts of it? Are there places where the wider community can assist?

**Comment by wp9015362** [comment]
> @pento wrote:
> 
> With Apple announcing imminent support for Unicode 8.0 emoji

The update is out now, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Regards

**Comment by WebReflection** [comment]
Talking about JS logic, the biggest change to consider is _diversity_

I need to implement a smart way to both catch all possible _diversity_ aware emoji and transform them as single image.

The API should be ideally backward compatible, no changes to the current logic, skin-tone related char eventually passed around instead of the variant one to keep it simple.

The initial idea was also to eventually style directly SVG images but this does not seem practical so as soon as I have assets _diversity_ aware I'll be more than happy to find some spare time and implement this on top.

All generators and RegExp aggregators logic will be affected, and same thing might happen for flags, beside the fact that for these no skin-tone or variant char would be passed around.

This was just a heads up from my side, but again I won't work on it until I know there are/will be assets.

**Comment by pento** [comment]
I've been playing around with generating the diversity variations from the SVG files - it's not too tricky so far, though I expect there'll need to be a bunch of variations. For example:

![Diverse Santas](https://cloud.githubusercontent.com/assets/352291/7064195/facfc650-deef-11e4-8021-5b4bf36a60f4.png)

Apart from the colours needing some tweaking, clearly the eyes in black Santa need to be changed, too.

**Comment by WebReflection** [comment]
@pento twemoji assets sources are AI files, SVG are automatically generated. Please do not waste too much time on SVG only, unless you think is beneficial for quick comparison, 'cause we are not going to modify SVG at runtime via JS, we need assets to reflect already different skins

**Comment by pento** [comment]
Yeah, I've written it as a function in `svg.sh`. I'm generating from SVG, because that's easier to deal with than generating from AI.

```sh
skintone() {
  local f
  local key
  local tonecode
  local tone
  local content

  local tonecodes=(1f3fb 1f3fc 1f3fd 1f3fe 1f3ff)
  local tones=(ffe0c4 e2b98f dfa675 d79e84 5b0000)

  local normal=(1f385 1f466);

  for f in "${normal[@]}"; do
    for key in "${!tonecodes[@]}"; do
      tonecode="${tonecodes[$key]}"
      tone="${tones[$key]}"

      content=$(
        cat "svg/$f.svg" |
        sed "s/#d79e84/#$tone/g"
      )

      echo "svg/$f-$tonecode.svg"
      echo "$content" >"svg/$f-$tonecode.svg"
    done
  done
}
```

**Comment by WebReflection** [comment]
interesting. How would you automate this procedure in order to bring all tones to every tone-code aware emoji?

**Comment by pento** [comment]
`normal` would be an array of all of the emoji which currently have #d79e84 skin tone. There'd be a similar array for emoji with the yellow skin tone. I'm not sure that there's a way to make it less unwieldy than that - at some point, we need to maintain a list of the emoji that have tone modifiers.

There are at least two exceptions I haven't figured out the best way to handle, yet:
* When the skin tone change doesn't fit with other colours in the emoji (ie, black santa)
* The handful of emoji with different default skin tones (purple and red, in particular)

The great advantage of Twemoji is that this approach works - all of the images are flat, so we don't need to worry about handling shadows.

This would generate all of the variations for SVG. It doesn't help for PNG, sadly. I'm wondering if it's possible to do this against the AI files, instead.

**Comment by WebReflection** [comment]
> at some point, we need to maintain a list of the emoji that have tone modifiers.

all generators parse directly from Unicode .org files in order to reflect standards as much as possible. I really wish we don't have to maintain manually a thing ;-)

About your concerns, that is why I think we should have ad-hoc assets (AI) so that we are sure the emoji will be a good looking one.

**Comment by pento** [comment]
Good points. It'll probably end up being just as much (or more) effort to maintain the tone generator, as it would be to create individual assets.

**Comment by wp9015362** [comment]
> @pento wrote:
> 
> I've been playing around with generating the diversity variations from the SVG files

Please note that the latest Draft Unicode Technical Report 51:

http://www.unicode.org/reports/tr51/

says this:

> When a human emoji is not immediately followed by a emoji modifier character,
> it should use a generic, non-realistic skin tone—such as (RGB #FFCC22),
> one of the colors typically used for the smiley faces.

Apple and Google already have begun doing this, as their default "humans" are now yellow, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
http://blog.emojipedia.org/android-50-emoji-changelog

So IMHO the default Twemoji humans should also be yellow.

Regards

**Comment by wp9015362** [comment]
Hello,

if you will modify/add the skin colors as part of the skin tone modifier feature, it would be nice if you could also take a look at the following issues:

https://github.com/twitter/twemoji/issues/71
https://github.com/twitter/twemoji/issues/72

and change those colors as well.

Regards

**Comment by pento** [comment]
Hey @WebReflection, sorry to pester, have you had any updates from your contacts within Twitter on the state of Unicode 8 emoji?

**Comment by WebReflection** [comment]
nope ¯\_(ツ)_/¯

**Comment by wp9015362** [comment]
The Apple Emoji set soon will feature Unicode 8.0 Emojis, see:

http://blog.emojipedia.org/ios-9-1-includes-new-emojis/

Regards

**Comment by caniszczyk** [comment]
Just to give an update, this is something we're working on within Twitter.

Look for updates in the near future within twemoji!

**Comment by jerrygrey** [comment]
@caniszczyk That's great to hear. Don't forget @pento's point about the eye colour for black skin tones.

**Comment by rodrigopolo** [comment]
Great news!

**Comment by kurisubrooks** [comment]
iOS 9.1 is now out with over 150 new Unicode 8.0 emoji.

**Comment by rodrigopolo** [comment]
@kurisubrooks Indeed, I had the beta some time ago which help me create this list and update my own emoji library:
http://rodrigopolo.com/files/emojilist/
https://github.com/rodrigopolo/minEmoji

**Comment by AISHWARYA677** [comment]
great!

**Comment by nickradford** [comment]
@caniszczyk Any update on this? Sorry to pester, just anxious for Unicode 8 support :smile:

**Comment by samantha-cruz** [comment]
Hi, when will the new emoji assets be added to this repo? Thanks.

**Comment by kurisubrooks** [comment]
Strange to see Twitter open-source a project, then completely abandon it. That's not how open-sourcing something works, Twitter.

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.
