### ISSUE TITLE
Use the Twitter account

### ISSUE THREAD

**Issue by Crissov** [twitter/twemoji#480]
[`@Twemoji`](https://twitter.com/twemoji?s=21) exists at Twitter, but it’s not used at all. I find this kind of embarrassing. 

Whoever has access to that account, can you use it at least to tweet release notifications and document changes? (Don’t rely on Emojipedia to do that.)

**Comment by BossFriend** [comment]
how is it embarrassing?

**Comment by Crissov** [comment]
A Twitter project not using Twitter?!

**Comment by katacarbix** [comment]
default avatar too, i wonder if it's even theirs or if someone else just snagged the name. either way, it would be nice to see an official account with updates!

**Comment by jdecked** [comment]
Pretty sure [`@Twemoji`](https://twitter.com/Twemoji) isn't run/owned by Twitter. We Tweet about Twemoji from [`@TwitterDesign`](https://twitter.com/TwitterDesign) (not _all_ releases, but sometimes also soliciting feedback on emoji designs).
