### ISSUE TITLE
Support Emoji 13.1 please

### ISSUE THREAD

**Issue by txtsd** [twitter/twemoji#485]
**Is your feature request related to a problem? Please describe.**
Unicode 13.0 has [Emoji 13.1 which dropped in 2021](https://blog.emojipedia.org/217-new-emojis-in-final-list-for-2021/).

**Describe the solution you'd like**
I'd like these emoji now included in Twemoji.

**Describe alternatives you've considered**
![](https://i.imgur.com/wl1vesr.png)

**Comment by jdecked** [comment]
We're working on it! Blocked by an internal team because some of these new emoji set a new record for being chonky (in bytes). But I'm definitely sending them this meme for encouragement. 😆

**Comment by Mancerrss** [comment]
Is it true that Twitter is now moving on from flat, easily modifiable, open source, vector [emojis to a more rasterized, glossy and expressive style for Twemoj](https://blog.emojipedia.org/new-glossy-twemoji-designs-appear-in-fleets/)i in the future?

![image](https://user-images.githubusercontent.com/20938829/115986332-442e2980-a5e2-11eb-8dfa-d3b4f0e8cc80.png)

How soon could we expect this update? And what will it mean to existing uses and open source design community of this emoji set? Will each emojis from the set will still be openly available to be modified by the open source community? (Please do)

**Comment by txtsd** [comment]
OH NO

**Comment by Crissov** [comment]
Twitter could put new emoji designs under a different license, but they cannot restrict the one used now for existing graphics. If they choose to follow this path and not develop the current set further, the community could of course fork it and extend it, especially for future additions published by Unicode. However, putting on my [Emojitwo](https://github.com/Emojitwo/) maintainer hat, I can tell you that it’s not that easy to keep an open source image set up to date.

**Comment by jdecked** [comment]
> Is it true that Twitter is now moving on from flat, easily modifiable, open source, vector [emojis to a more rasterized, glossy and expressive style for Twemoj](https://blog.emojipedia.org/new-glossy-twemoji-designs-appear-in-fleets/)i in the future?
> 
> ![image](https://user-images.githubusercontent.com/20938829/115986332-442e2980-a5e2-11eb-8dfa-d3b4f0e8cc80.png)
> 
> How soon could we expect this update? And what will it mean to existing uses and open source design community of this emoji set? Will each emojis from the set will still be openly available to be modified by the open source community? (Please do)

The short answer is that I don't know.

The slightly longer answer is that I see the value of us continuing to maintain the vectorized set and will continue to push for this wherever possible. What's already here right now isn't going to disappear in the future, like @Crissov said. FWIW, I don't want vectorized Twemoji to stop being maintained either, but I'm far from the only one involved in this decision.

**Comment by jdecked** [comment]
After much pain in writing the release notes by hand, [Twemoji 13.1 is now available](https://github.com/twitter/twemoji/releases/tag/v13.1.0). Cross your fingers I haven't broken Twitter in the process. 😂
