### ISSUE TITLE
Script for Generating PNGs

### ISSUE THREAD

**Issue by pento** [twitter/twemoji#49]
While `svg.sh` exists for generating SVGs, there doesn't seem to be an equivalent `png.sh` for generating the PNGs.

Would someone mind adding this to the repo, please? :-)

**Comment by WebReflection** [comment]
assets are provided by designers, svg was a simple to have exception. Any specific reason you need that? The CDN will be updated per each asset, you don't need to export any of them.

**Comment by pento** [comment]
Ah, I assumed they were generated from the source AI files.

No particular need, I was pondering how to face emojis with Unicode 8.0's new skin tone feature (#48), and was wondering if they could be automatically generated.

**Comment by WebReflection** [comment]
skin tone requires some extra work for the regexp and logic, it is not just a matter of assets. I will probably start investigation / estimation this month as soon as I've a bit of extra time, stay tuned
