### ISSUE TITLE
`index.d.ts` is not published with NPM package

### ISSUE THREAD

**Issue by peterblazejewicz** [twitter/twemoji#490]
**Describe the bug**

The `index.d.ts` is not part of NPM distribution and it not listed in the `package.json`.
For this reason is serves no purpose at the moment I'm afraid.

Added here: #399

```bash
npm pack twemoji
npm notice
npm notice package: twemoji@13.1.0
npm notice === Tarball Contents ===
npm notice 0      package
npm notice 1.1kB  LICENSE
npm notice 18.5kB LICENSE-GRAPHICS
npm notice 11.4kB README.md
npm notice 0      dist
npm notice 1.1kB  package.json
npm notice 33.0kB dist/twemoji.amd.js
npm notice 17.0kB dist/twemoji.esm.js
npm notice 32.0kB dist/twemoji.js
npm notice 17.0kB dist/twemoji.min.js
npm notice 32.1kB dist/twemoji.npm.js
npm notice === Tarball Details ===
npm notice name:          twemoji
npm notice version:       13.1.0
npm notice filename:      twemoji-13.1.0.tgz
npm notice package size:  32.7 kB
npm notice unpacked size: 163.3 kB
npm notice shasum:        65bb71e966dae56f0d42c30176f04cbdae109913
npm notice integrity:     sha512-e3fZRl2S9UQQd[...]rJraOXrWw/4Ew==
npm notice total files:   11
npm notice
twemoji-13.1.0.tgz
```

Thanks!

/cc @goooseman

**Comment by goooseman** [comment]
@peterblazejewicz Hi! You are completely right, I did not mention, that the project uses package.json/files and that the file is blacklisted from the package distribution.
Created #491 to resolve this issue.

**Comment by jdecked** [comment]
Hey @goooseman @peterblazejewicz, should these types live in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead? Would that be where you expect to find them given that this isn't a TS project? I don't use TS, but [the TS publishing docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) seem to indicate that we shouldn't publish the types with this package but submit them to DefinitelyTyped:
>If your types are generated by your source code, publish the types with your source code. [...] Otherwise, we recommend submitting the types to DefinitelyTyped, which will publish them to the `@types` organization on npm.

**Comment by goooseman** [comment]
From my personal experience supporting the type definitions is much easier when done from the original repository. 

I support some of the type definitions in the [DefinetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), but it usually takes too much time to update an existing type definition there.

**Comment by goooseman** [comment]
And from the consumer perspective providing those definitions with the package itself is much more convenient

**Comment by peterblazejewicz** [comment]
@jdecked thx for asking for opinion. @goooseman knows this project better, so pleasetake his advice.
I'd only say, nowadays, `.d.ts` are serving native JavaScript, same way as in `TS` only era. So project gets all the same benefits, like when being actually written in TS, say in VSCode or other IDEs. There are pros and cons of hosting your own types within project, so you folks should give it a review (imo the TS handbook is just an best 80%-working techy advise, cannot be taken literally).
