### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Maheswar3** [twitter/twemoji#502]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Pukimaa** [comment]
Someone close that please

**Comment by QuickWrite** [comment]
Was this a mistake or why is this issue here?
I think this issue should be closed.
