### ISSUE TITLE
Feature Request: Space Emoji

### ISSUE THREAD

**Issue by Pukimaa** [twitter/twemoji#506]
**Is your feature request related to a problem? Please describe.**
I am always frustrated if I search up for Space and there are just Meteors, Stars etc.

**Describe the solution you'd like**
I wanna have a Space Emoji maybe it can be squared with a dark background and some stars etc. in the foreground
![Space](https://user-images.githubusercontent.com/58347116/126760349-273c521a-326e-476c-9e1d-a2b977d6e181.png)

**Describe alternatives you've considered**
A Galaxy Emoji would also be very nice and might be easier to understand
![Galaxy](https://user-images.githubusercontent.com/58347116/126760482-b3802756-d7d4-4356-8a36-165d937b1f2c.png)

**Comment by Crissov** [comment]
Here is not the right place, please consider [Emojination](http://www.emojination.org) or [Unicode](http://unicode.org/emoji/proposals.html) directly. For what it’s worth, there already is [🌌 Milky Way](https://emojipedia.org/milky-way/).
