### ISSUE TITLE
Image compression breaks gifs.

### ISSUE THREAD

**Issue by dconnolly** [twitter/twemoji#51]
If you send a gif as an attachment and it is under the resize limit, it renders as expected in the view, animated. If it is too large, it is compressed and no longer animates. This sucks mostly because in the attachment preview, it is still animating, misleading the user as to the end behavior. I don't know if there is a way to compress gifs within a web runtime without this behavior, but as a user I would prefer the image preview before send reflect the changed behavior of the image (that it will no longer animate).

Small gif (364KB), animates after send:
![ron-swanson-at-desk-giggling](https://cloud.githubusercontent.com/assets/552961/6600840/586ce80c-c7e8-11e4-88f1-08032a2087e8.gif)

Larger gif (465KB), does not animate after send:
![ron-swanson-cats-are-pointless](https://cloud.githubusercontent.com/assets/552961/6600886/900c5fa4-c7e8-11e4-8fae-52bab9166223.gif)

**Comment by dconnolly** [comment]
Wrong repo!

**Comment by WebReflection** [comment]
welcome to github ![whbscbu](http://i1.kym-cdn.com/entries/icons/original/000/001/248/cannot_be_unseen.jpg)

**Comment by dconnolly** [comment]
:+1:
