### ISSUE TITLE
Add support for Emoji 14.0

### ISSUE THREAD

**Issue by a-felix** [twitter/twemoji#515]
**Is your feature request related to a problem? Please describe.**
Unicode 14.0, released yesterday, contains [Emoji 14.0](https://www.unicode.org/emoji/charts-14.0/emoji-released.html). For obvious reasons, the new emoji have not been included in Twemoji so far.

**Describe the solution you'd like**
I would like it if these emoji were added to Twemoji.

**Describe alternatives you've considered**
Complain about not being able to put a disco ball in the middle of a sentence.

**Comment by KTamas** [comment]
iOS 15.4 beta already has them https://twitter.com/Emojipedia/status/1486794653110210565

**Comment by a-felix** [comment]
Thanks!
![discombobulate](https://user-images.githubusercontent.com/15919379/158523567-ab1fc20d-4537-49b9-a146-d58af48c2e8e.png)

**Comment by stof** [comment]
Looks like there is now a 14.0.0 in the repo, but no corresponding github release

**Comment by rodrigograca31** [comment]
> Looks like there is now a 14.0.0 in the repo, but no corresponding github release

yeah, Im also waiting for a github release please. but it seems we can just used 14.0.1 already

```html
<script src="https://twemoji.maxcdn.com/v/14.0.1/twemoji.min.js" integrity="sha384-9XmaIHs67kvwAL3GE7nu7tddcROD/RBKYbYZcPd8KsVPdrA3U1574EW2PLtdTxDN" crossorigin="anonymous"></script>
```

**Comment by jdecked** [comment]
at last there is now a github release too ([v14.0.0](https://github.com/twitter/twemoji/releases/tag/v14.0.0)). closing this. thanks for the laughs as usual @a-felix
