### ISSUE TITLE
Appropiate credit in discord bot

### ISSUE THREAD

**Issue by ziomek64** [twitter/twemoji#523]
Hi,
I'm making a Discord bot. What is appropiate place to give credit? In each message that bot sends which will contain such graphic, or can I put that information on the website? - Probably message? How about information in a help command that we have instead of each message?

How do I properly write that so it's fine? In shortest way possible. I mean "copyright by" etc. Wanna make it correct, legit and short at the same time

I'm thinking about using them and modyfing some of them.

**Comment by MJ535-dev** [comment]
Twemoji's graphics are licensed under Creative Commons 4.0 International. Therefore, it is optimal to put this at the bottom:

Twemoji © 2022 is licensed under CC BY 4.0. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/

But because you said you wanted it short, maybe this:

Twemoji is licensed under CC BY 4.0. Use !credit for more detail.

Does that work? I don't actually work at Twitter/Twemoji but I am experienced in licensing.

**Comment by ziomek64** [comment]
Where should I put it? Only website works fine? or any message that will contain this emoji? I'm making a discord bot if you've read it.

@MJ535-dev Thanks for helping me, nobody responded in so much time

**Comment by MJ535-dev** [comment]
I think the website works fine. In the readme it says,

However, we consider the guide a bit onerous and as a project, will accept a mention in a project README or an 'About' section or footer on a website. In mobile applications, a common place would be in the Settings/About section (for example, see the mobile Twitter application Settings->About->Legal section). We would consider a mention in the HTML/JS source sufficient also.

So yes I think putting in the about or the footer is ok :)

**Comment by ziomek64** [comment]
@MJ535-dev Were exactly do you have that line about website? I've read about this license on the internet and couldn't find info

**Comment by MJ535-dev** [comment]
it's in the README

**Comment by ziomek64** [comment]
@MJ535-dev will i still need to mention in the app itself that the info is on the website or I don't have to?

**Comment by MJ535-dev** [comment]
Sorry for a late response but I'll try my best to explain without knowing your exact use case:

Discord bots usually don't require this credit embedded into messages unless the whole message is literally just an emoji. If so, I'd probably just include `Emojis from Twemoji` at the bottom of a message and that's it.

On the website, it would be best to include credit. I've seen some that just put it in the legal section and some that have a footer that says `Emojis made with <3 by Twemoji`. It honestly depends on what you want. I don't think you would have to mention in the Discord bot that info is on the website.

Also, the amazing part of the CC-BY-4.0 is that you are allowed to remix and change anything you want, and the only restriction is that you have to say that the original emojis were by the Twemoji Team. So no, it doesn't require different credit but it might be best to say `Emojis based on Twemoji` or something similar.

If you could clarify what it is you're doing specifically, that would be nice so I can have a better sense of what specifically you are doing.

**Comment by azuryceo** [comment]
I don't quite understand the point of this. After all, **Discord already uses Twemoji**. So why don't you just use emojis? Discord.js even has a guide for this: https://discordjs.guide/popular-topics/reactions.html#unicode-emojis

Therefore, you can simply send the emojis and Discord will convert them to Twitter's classic emojis.

**Comment by MJ535-dev** [comment]
@azuryceo The OP wants to modify the emojis

**Comment by ziomek64** [comment]
@MJ535-dev some will be modified, some not.

**Comment by MJ535-dev** [comment]
@ziomek64 Can you clarify what it is you're doing?

**Comment by azuryceo** [comment]
Oh well, then go ahead.

**Comment by azuryceo** [comment]
> @azuryceo The OP wants to modify the emojis

Oh well, then go ahead.

**Comment by ziomek64** [comment]
@MJ535-dev The way i modify them or use case scenario?

**Comment by MJ535-dev** [comment]
use case scenario

**Comment by ziomek64** [comment]
This is just one use case, it's a help command. I want modify these emojis to the shade of green that my bot uses. 
![image](https://user-images.githubusercontent.com/84880432/147884576-3a8e67e4-cf2a-44f2-b03d-1a33326fa8ab.png)

**Comment by azuryceo** [comment]
I don't see any modified ones.

**Comment by ziomek64** [comment]
@azuryceo I want to do it XD but wanna do credit first lmao

**Comment by ziomek64** [comment]
Read the message again

**Comment by MJ535-dev** [comment]
Oh yeah you probably don't need to include credit in the actual message then. Still good to have it in the website though

**Comment by azuryceo** [comment]
If you got a website already, create a subpage and add all the credits there, if not, just create a command in your bot e.g. `/credits`?

**Comment by ziomek64** [comment]
@azuryceo yeah I wanted to know how to credit and where to do that in the first post. I will do website subpage

**Comment by azuryceo** [comment]
Sounds good to me, I've got a whole page for all the open-source projects i use in mine:
https://azury.dev/acknowledgements

**Comment by azuryceo** [comment]
Just don't hide the page, e.g. link it in your footer and you're good to go!

**Comment by ziomek64** [comment]
Can i also use them as custom emoji for my server? (Besides the bot)  with the same credit?

**Comment by ziomek64** [comment]
@azuryceo Yeah, sure

**Comment by azuryceo** [comment]
I'm not a lawyer, but yeah!

I guess you have some "server rules" or something like that? Put a simple link there and you're done!

**Comment by azuryceo** [comment]
Just keep it readable and simple! 😉
