### ISSUE TITLE
Add SELECT to the ignore list

### ISSUE THREAD

**Issue by pento** [twitter/twemoji#53]
Based on discussion from #50.

`select` can only contain `option` or `optgroup` tags, `optgroup` can only contain `option` tags, and `option` can only contain text.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by WebReflection** [comment]
fair enough, landed in `1.3.2` thank you

**Comment by lewisje** [comment]
The minified script still doesn't have this enhancement.

**Comment by WebReflection** [comment]
you are right, sorry. Updated now
