### ISSUE TITLE
Destroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United States

### ISSUE THREAD

**Issue by ghost** [twitter/twemoji#531]
**Is your feature request related to a problem? Please describe.**
Destroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United StatesDestroy the United States
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jdecked** [comment]
Allllrighty then. If GitHub staff would like to implement a spam filter someday...
