### ISSUE TITLE
factor out creating new Image in the loop in parseNode

### ISSUE THREAD

**Issue by lewisje** [twitter/twemoji#54]
It might be faster to declare a variable (right between `shouldntBeParsed` and `fromCharCode` around line 510 in twemoji-generator.js) that contains the data common to all of the emoji images, (it looks like what they have in common is the `onerror` property and the `draggable=false` attribute, but apparently `cloneNode` does not clone event handlers) and then call `cloneNode` on that variable within the `parseNode` function, around line 643.

In the end, it would look a bit like this...
```javascript
/* list of variable declarations */
        // nodes with type 1 which should **not** be parsed
        shouldntBeParsed = /IFRAME|NOFRAMES|NOSCRIPT|SCRIPT|SELECT|STYLE|TEXTAREA/,

        // call the constructor just once, for performance reasons
        emojiImg = new Image(),

        // just a private shortcut
        fromCharCode = String.fromCharCode;

      emojiImg.setAttribute('draggable', 'false');

      return twemoji;

/* more code, now we're inside the while loop in the parseNode function */
              if (src) {
                img = emojiImg.cloneNode();
                img.onerror = twemoji.onerror;
                img.className = options.className;
                img.alt = alt;
                img.src = src;
                modified = true;
                fragment.appendChild(img);
              }
/* on to the end of the file */
```

I believe this will be faster, at the cost of keeping an extra Image node perpetually in memory.

**Comment by WebReflection** [comment]
cloneNode is historically ful of quirks + I don't see benchmarks. What kind of real-world problme are you trying to solve here? Can I see a page where your change perform that better to risk the usage of a historically problematic method? Thanks

**Comment by lewisje** [comment]
I just got the idea from comparing the Google Chrome extensions Twemojify (which uses this script) and Chromoji (which uses a different image-replacement method that partially relies on a dummy Image node), not from actual benchmarks; maybe I should fork this, make the change I requested, and see how it goes, but from what you just posted, cloneNode might not be such a good idea for a general-purpose API, even though it's probably fine in a Chrome extension.

**Comment by WebReflection** [comment]
yes, it'd be working fine on Chrome and modern browsers. This library is compatible with all of them but it's also compatible with very old browsers and all their "lovely" quirks. If you find such performance win though please let me know.
