### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by alexeymolchan** [twitter/twemoji#545]
Hi,  methods ```replace```, ```test``` and ```onerror``` are missing in type definitions and docs. They were defined in [@types/twemoji](https://www.npmjs.com/package/@types/twemoji) for version 12.1.2 but this package is deprecated for current version.

twemoji version: 14.0.2

**Comment by jdecked** [comment]
PRs welcome.

**Comment by alexeymolchan** [comment]
@jdecked https://github.com/twitter/twemoji/pull/546

**Comment by alexeymolchan** [comment]
@jdecked Hi, any plans to release a new version with updated types ?

**Comment by bernardop-flw** [comment]
@jdecked Hi, is there any plans for the next release including this update?
