### ISSUE TITLE
How to find the name from code

### ISSUE THREAD

**Issue by shinokada** [twitter/twemoji#548]
**Is your feature request related to a problem? Please describe.**
When I see names in the [svg dir](https://github.com/twitter/twemoji/tree/master/assets/svg), it is impossible to find emoji names from file names.
Is there any list to associate file names and file names?

**Describe the solution you'd like**
A list of emojis and file names.

| file name | Emoji|
|---|--|
| 1f004 |  ![image](https://user-images.githubusercontent.com/147320/171160655-eff8381c-4869-464a-b5db-6b85dac22a59.png) |

**Describe alternatives you've considered**

Web app to find emoji from file name.

**Comment by Miepee** [comment]
You can use https://emojipedia.org/ for that.

**Comment by shinokada** [comment]
Thanks.

**Comment by Miepee** [comment]
https://emojipedia.org/cherries/
Scroll down to the bottom where the codepoint is located
![image](https://user-images.githubusercontent.com/38186597/171339605-b90e37ad-7018-4ff3-9618-2e82ba9506fe.png)
The twitter svg's aren't prefixed with `U` and are all lowercase, so the cherries emoji svg is `1f352.svg`.

If you're looking at emojis that have multiple codepoints, like `👨‍🍳` (U+1F468, U+200D, U+1F373), then they'll be seperated by hyphens. So `1f468-200d-1f373.svg`

**Comment by shinokada** [comment]
Thanks.

**Comment by lluia** [comment]
Is there not an easier way to find emojis by name? Seems a bit hilarious we need to be scouting the `svg` dir by codepoints 😅

**Comment by Miepee** [comment]
Issue with names is, that names are very ambiguous. The same emoji can have multiple names, and it would take too much effort to maintain a list of that for this repo probably.
Codepoints are much clearer in that regard.
