### ISSUE TITLE
More native New Zealand emojis

### ISSUE THREAD

**Issue by XdGoldenTigerOfficial** [twitter/twemoji#549]
A lot of emoji systems/frameworks have missed out on adding NZ emojis to their emoji list.
I mainly just see 1 NZ emoji, and that is the NZ flag.

It would be amazing if you guys included more emojis for us. Like the Kiwi bird, and other native animals/birds like the Kea, Kākāpō, Takahe, etc...

Yes, I know New Zealand is a small country, But we still deserve to be known to all companies that create this type of stuff. I feel like we are missing out on a ton of stuff.

**Comment by Crissov** [comment]
https://unicode.org/emoji/proposals.html
