### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by shinokada** [twitter/twemoji#550]
I'm sorry for using But report issue. I couldn't find the appropriate channel.

I created [this repo](https://github.com/shinokada/svelte-twitter-emoji/tree/main/src/lib) for Svelte community using SVG code such as [this](https://github.com/twitter/twemoji/blame/master/assets/svg/1f004.svg).

Because I'm using SVG code, I added MIT license at the moment.
You have two licenses, MIT and CC-BY-4.0 licenses.
I'm not 100% user which license I should use?

Please let me know.

Thank you for your awesome work.

**Comment by jdecked** [comment]
Hey! Usually our lawyers get upset if I tell you how to credit Twemoji beyond which of the licenses Twemoji is covered by, so here I'm going to say that Twemoji's code is covered by the MIT license and all graphics are covered by CC-BY-4.0. SVGs are graphics :) Hope that helps despite the vagueness!

**Comment by shinokada** [comment]
@jdecked Thanks. I added an attribution with a link and changed the repo to CC-BY-4.0 too.
