### ISSUE TITLE
is this real?

### ISSUE THREAD

**Issue by stingalleman** [twitter/twemoji#565]
is this the new version of twemoji? if yes, what the actual flippity fuck fuck?

![FeLEMkFUUAAMOJK](https://user-images.githubusercontent.com/13184132/193684969-ca41470a-336c-4dfd-aebd-a2abb1a20096.jpeg)

**Comment by jdecked** [comment]
It is! Our designers are very happy about it. Worry not: this version won't be coming to the open source version of Twemoji, and we'll continue to maintain the vector version for the open source community.

**Comment by pointydev** [comment]
> we'll continue to maintain the vector version

Will this include new emojis in later specs?

**Comment by jdecked** [comment]
> > we'll continue to maintain the vector version
> 
> Will this include new emojis in later specs?

Yes.

**Comment by stingalleman** [comment]
okay cool we approve 👍🏻
