### ISSUE TITLE
Flag doesn't display; instead, a blue circle with letter is shown

### ISSUE THREAD

**Issue by Nikhil22** [twitter/twemoji#589]
**Describe the bug**
When I try to display an Emoji via a Unicode like 1F1FB (Vietnam), the country flag does not show, instead a blue circle with the letter V is shown. SVG.
**To Reproduce**
1. Just go to https://cdn.jsdelivr.net/gh/twitter/twemoji@v14.0.2/assets/svg/1f1fb.svg

**Expected behavior**
Instead of the blue circle with V inside, I expect the Vietnam flag here. And same for all other countries.

**Screenshots**
[
<img width="72" alt="Screenshot 2023-02-07 at 10 08 54" src="https://user-images.githubusercontent.com/10525104/217122555-62daa5f5-098c-4f77-8a7e-a3f6f4a7f258.png">
](url)
**Environment**
OS Version: 13.2 (Ventura)
Chrome Version: 109.0.5414.119

Both are latest versions at the time of this writing.

**Additional context**

**Comment by jdecked** [comment]
Alas, 1F1FB in Unicode is in fact "regional indicator symbol letter V" – not the flag of Vietnam. You are looking for 1F1FB-1F1F3, which works as expected: https://cdn.jsdelivr.net/gh/twitter/twemoji@v14.0.2/assets/svg/1f1fb-1f1f3.svg

**Comment by Nikhil22** [comment]
You are correct, thank you.
