### ISSUE TITLE
SLIGHTLY FROWNING FACE and SLIGHTLY SMILING FACE not implemented

### ISSUE THREAD

**Issue by iseulde** [twitter/twemoji#59]
See http://unicode.org/charts/PDF/U1F600.pdf.

**Comment by waldyrious** [comment]
PR #67 has added the .ai assets for slightly smiling face and slightly frowning face. Now only the SVG and png versions are needed for this issue to be solved. Does anyone know what are the steps required to do that? /cc @jasmussen who authored that PR, and @WebReflection who merged it.

**Comment by wp9015362** [comment]
@waldyrious :

The SVGs are already available..., see:

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f641.svg
https://github.com/twitter/twemoji/blob/gh-pages/svg/1f642.svg

And there's already a discussion regarding the PNG export in:

https://github.com/twitter/twemoji/issues/60

Regards

**Comment by waldyrious** [comment]
Thanks for the info. I did search in the svg folder bot somehow didn't find the files there. I've commented in #60 and will keep an eye on it. It seems there isn't anything fundamentally hard keeping this from moving forward.

**Comment by bhaggs** [comment]
This has been fixed as part of v2.
