### ISSUE TITLE
![sweating-nervous](https://user-images.githubusercontent.com/2575182/211350030-249c6b1f-a347-4ade-bd40-1ed83629f09f.gif)

### ISSUE THREAD

**Issue by Elain8837** [twitter/twemoji#630]
![sweating-nervous](https://user-images.githubusercontent.com/2575182/211350030-249c6b1f-a347-4ade-bd40-1ed83629f09f.gif)

_Originally posted by @Xstoudi in https://github.com/twitter/twemoji/issues/580#issuecomment-1375842716_

**Comment by Xstoudi** [comment]
Excuse me wtf?
