### ISSUE TITLE
CDN links to maxcdn.com are broken

### ISSUE THREAD

**Issue by chriscdn** [twitter/twemoji#636]
**Describe the bug**

I'm using `twemoji.parse` to convert text with emojis into image links.  The image links are broken.

**To Reproduce**

Try opening any of the following URLs from the README:

- https://twemoji.maxcdn.com/v/latest/72x72/2764.png
- https://twemoji.maxcdn.com/svg/2764.svg

**Expected behavior**
The images or SVG should load.

**Comment by smashah** [comment]
https://twemoji.maxcdn.com/v/latest/twemoji.min.js forwards to https://www.stackpath.com/blog/

Did Elon not pay his maxcdn bill or something??

**Comment by SophiaAtkinson** [comment]
@smashah He can't pay for anything lol

**Comment by rsns-0** [comment]
Hi, a [fork](https://github.com/twitter/twemoji/issues/580) that is currently actively maintained by former Twitter developers may help. It uses jsDelivr instead of MaxCDN for CDN provider.
