### ISSUE TITLE
"Face savouring delicious food" Twemoji looks like as if it would be winking. Please remove wink and please widen the mouth so that the mouth has the same length on both sides.

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#70]
@WebReflection & @jasmussen :

The "face savouring delicious food" Twemoji::

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f60b.svg

looks like as if it would be winking.

The "savouring delicious food" description does not mention a wink.

And the mouth of the "face savouring delicious food" Twemoji is shorter on the left side than it is on the right side.

The "face savouring delicious food" Apple Emoji for example does not have a wink and it's mouth has the same length on both sides, see:

:yum:

So, could you please remove the wink from the "face savouring delicious food" Twemoji and widen it's mouth so that it's mouth has the same length on both sides.?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
PS:

The "face savouring delicious food" Emoji in the Unicode PDF document which is mentioned over there:

https://github.com/twitter/twemoji/issues/59

also does not have a wink and the mouth has the same length on both sides.

Regards

**Comment by bhaggs** [comment]
This has been addressed in v2.
