### ISSUE TITLE
"Boar" Twemoji looks like a normal pig due to light color. It should have darker (more brown) color.

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#71]
Hello,

the "boar" Twemoji:

![Image](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/72x72/1f417.png)

looks like a normal pig due to it's light color.

Please change it's color to a darker (more brown) color so that it actually looks like a boar.

Regards

**Comment by jmdarts007** [comment]
like and thanks
