### ISSUE TITLE
PNGs differ in size and position compared to SVGs

### ISSUE THREAD

**Issue by wp9015362** [twitter/twemoji#75]
Hello,

I just did the following:

I openened the SVG Twemoji preview page at 300% zoom in one tab of Mozilla Firefox 37.0.1:

http://twitter.github.io/twemoji/preview-svg.html

Then I openened the PNG Twemoji preview page at 300% zoom in another tab of Mozilla Firefox 37.0.1:

http://twitter.github.io/twemoji/preview.html

And I made sure that they both show the same content at the same time (i.e. both are at the same scroll position each time).

Then I switched between both tabs and immediately noticed the following:

* The PNGs differ in size from the SVGs
* The PNGs sometimes differ in position from the SVGs

And I am ***not*** talking about the [face Twemojis](https://github.com/twitter/twemoji/issues/60).

I am talking about all the other Twemojis.

By the way, I also noticed that the 72x72 PNGs lack a lot of definition compared to the SVGs, they are much more blurry when being scaled up (zoom @ 300%). So it couldn't hurt to have the PNGs also available in some higher resolutions than 72x72 I'd say.

Regards

**Comment by WebReflection** [comment]
those are just for demo purpose + yes, you've discovered vector VS raster ... SVG will always be better, I put higher resolution for PNG for which purpose? So that if you zoom 600% is blurry?

This is a non issue to me, we've got better things to fix or do here

**Comment by wp9015362** [comment]
> @WebReflection wrote:
> 
> I put higher resolution for PNG for which purpose? So that if you zoom 600% is blurry?

> This is a non issue to me, we've got better things to fix or do here

Another purpose for higher resolution PNGs, other than zooming into a webpage at 600%..., would probably be displaying Emojis on high PPI displays, like they are commonly found in mobile devices these days (i.e. for them not to appear tiny).

Regards

**Comment by WebReflection** [comment]
Yes, the 72 by 72 resolution is for that purpose indeed. Best of all parts though, assets are open source too!!!! If you need your ad-hoc resolution you grab them and you export them any resolution you like!

Meanwhile, nobody in the real world had this problem, and when such capable devices are recognized, you simply use SVG and forget about resolution completely: how cool is the future?

This is a non existent real world issue and as such, will stay closed.

**Comment by Saketme** [comment]
Seconded. We even have Android libraries for directly displaying SVGs in our application!
