### ISSUE TITLE
'bower install' returns incorrect packages

### ISSUE THREAD

**Issue by markni** [twitter/twemoji#76]
Currently if you run 

`bower install twemoji`

it returns an almost empty 1.4.0 version (contains a single line README file and bower.json), which is the [master branch](https://github.com/twitter/twemoji/tree/master). 

and run 

`bower install twemoji#1.3.2`

it returns a 200MB package with everything included in this repo, development assets are not ignored at all.

**Comment by WebReflection** [comment]
IIRC the whole download was meant since the beginning ... I am not sure why version `1.4.0` wouldn't just work though. Will try to figure it out, but when it will, it will probably bring you everything, assets included.

**Comment by Kikobeats** [comment]
```
$ bower install twemoji
bower twemoji#*                 cached git://github.com/twitter/twemoji.git#1.4.0
bower twemoji#*               validate 1.4.0 against git://github.com/twitter/twemoji.git#*
bower twemoji#*                    new version for git://github.com/twitter/twemoji.git#*
bower twemoji#*                resolve git://github.com/twitter/twemoji.git#*
bower twemoji#*               download https://github.com/twitter/twemoji/archive/v1.4.1.tar.gz
```

and never ends :(

**Comment by WebReflection** [comment]
tried now with `v2.0.5` and I cannot reproduce this.
