### ISSUE TITLE
Parsing emojis from input

### ISSUE THREAD

**Issue by jbardnz** [twitter/twemoji#80]
Hey

So I am trying to parse emojis from an input box, I have setup a codepen demo here to demonstrate my issue: http://codepen.io/anon/pen/yNYzXx

If I type the text "I \u2764\uFE0F emoji!" into the input box and click go I expect the same result on both lines instead the input text isn't parsed but the variable is.

**Comment by WebReflection** [comment]
So there are at least two issues here:

  1. you are using a library, when you think there's a bug to file please be sure you test without third parts or it becomes less obvious what might be the problem
  2. you need to write `I ❤️ emoji!` there, not the equivalent JavaScript string.

If you copy the output into the input, or you type directly in there an emoji through your mobile phone keyboard with its emoji, you will see the right thing like I do.

![screenshot from 2015-05-06 06-24-29](https://cloud.githubusercontent.com/assets/85749/7487909/f840e364-f3b8-11e4-9755-8f54aa89b574.png)

If you type in there the unicode character representation of course you'll see exactly that thing and nothing else.
