### ISSUE TITLE
New SVGs

### ISSUE THREAD

**Issue by rodrigopolo** [twitter/twemoji#81]
Thanks to @WebReflection I decided to add yet another issue asking for an enhancement (the same thing that has been requested 3 more times); As anyone on the internet knows there are new emojis implemented by Apple and currently in use... not in the future but since April 8, 2015.

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

I created a library that replaces unicode emoji into html (span sprites, imgs and svgs) and I use twemoji SVGs which I believe are the best option out there considering bandwidth and display quality (HiDPI/Retina screens) but I have found many SVGs are not yet created for the new emoji set implemented by Apple in iOS 8.3.

Here is the complete list of emojis found in AppleColorEmoji.ttf:
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html

(@WebReflection I include the link to my own library so you can see an ordered list of all available emojis, NOT to promote a free/libre/gratis/open source library)

So, I'm looking for some one interested in creating this SVGs to share with him/her this list of "missing emojis" and to assist in any way.

Thanks a lot your your kindly attention to the matter and I hope this enhancement request (new issue) doesn't violate any rules nor hurt anyone feelings, I'm just looking for some SVGs and to contribute back to the internet.

**Comment by WebReflection** [comment]
as already mentioned, SVGs are created from AI out of an automated procedure. Until somebody at Twitter or over the Internet will decide to open AI and help with missing/modern emoji, there won't be any SVG. And same goes for PNGs ... no AI, no emoji, that's how this repo work.

I keep this open hoping someone else from Twitter will answer as well.

**Comment by rodrigopolo** [comment]
@WebReflection Thanks, here is the list of the available emojis found in iOS 8.3, also a list of unused twemoji emojis:

http://rodrigopolo.com/files/emojilist/

**Comment by rodrigopolo** [comment]
@WebReflection FYI I forked the repo and added some new emojis, I'll add more later...

Commit (36 emojis)
https://github.com/rodrigopolo/twemoji/commit/98782896def7c998bd424b56b9ae9235119bfaae

Files:
https://github.com/rodrigopolo/twemoji/tree/gh-pages/svg

List with updated changes:
http://rodrigopolo.com/files/emojilist/

Files added and updated:
```
1f466-1f3fb.svg
1f466-1f3fc.svg
1f466-1f3fd.svg
1f466-1f3fe.svg
1f466-1f3ff.svg
1f466.svg
1f467-1f3fb.svg
1f467-1f3fc.svg
1f467-1f3fd.svg
1f467-1f3fe.svg
1f467-1f3ff.svg
1f467.svg
1f468-1f3fb.svg
1f468-1f3fc.svg
1f468-1f3fd.svg
1f468-1f3fe.svg
1f468-1f3ff.svg
1f468.svg
1f469-1f3fb.svg
1f469-1f3fc.svg
1f469-1f3fd.svg
1f469-1f3fe.svg
1f469-1f3ff.svg
1f469.svg
1f476-1f3fb.svg
1f476-1f3fc.svg
1f476-1f3fd.svg
1f476-1f3fe.svg
1f476-1f3ff.svg
1f476.svg
1f64c-1f3fb.svg
1f64c-1f3fc.svg
1f64c-1f3fd.svg
1f64c-1f3fe.svg
1f64c-1f3ff.svg
1f64c.svg
```

**Comment by rodrigopolo** [comment]
And another 121 emojis added/edited, most of them are about the pale skin tone modifier:

https://github.com/rodrigopolo/twemoji/commit/5a01c535f26daaf672ee03dee7e25867e68ffaf6

```
1f485.svg
1f485-1f3ff.svg
1f485-1f3fb.svg
1f485-1f3fc.svg
1f485-1f3fd.svg
1f485-1f3fe.svg
1f44b.svg
1f44b-1f3ff.svg
1f44b-1f3fb.svg
1f44b-1f3fc.svg
1f44b-1f3fd.svg
1f44b-1f3fe.svg
1f450.svg
1f450-1f3ff.svg
1f450-1f3fb.svg
1f450-1f3fc.svg
1f450-1f3fd.svg
1f450-1f3fe.svg
1f64f.svg
1f64f-1f3fb.svg
1f64f-1f3fc.svg
1f64f-1f3fd.svg
1f64f-1f3fe.svg
1f64f-1f3ff.svg
1f4aa.svg
1f4aa-1f3ff.svg
1f4aa-1f3fb.svg
1f4aa-1f3fc.svg
1f4aa-1f3fd.svg
1f4aa-1f3fe.svg
270b-1f3fb.svg
270b-1f3fc.svg
270b-1f3fd.svg
270b-1f3fe.svg
270b-1f3ff.svg
270b.svg
270a.svg
270a-1f3ff.svg
270a-1f3fb.svg
270a-1f3fc.svg
270a-1f3fd.svg
270a-1f3fe.svg
1f44a.svg
1f44ax.svg
1f44a-1f3ff.svg
1f44a-1f3fb.svg
1f44a-1f3fc.svg
1f44a-1f3fd.svg
1f44a-1f3fe.svg
270c.svg
270c-1f3fb.svg
270c-1f3fc.svg
270c-1f3fd.svg
270c-1f3fe.svg
270c-1f3ff.svg
1f44c-1f3fb.svg
1f44c-1f3fc.svg
1f44c-1f3fd.svg
1f44c-1f3fe.svg
1f44c-1f3ff.svg
1f44c.svg
1f449-1f3fb.svg
1f449-1f3fc.svg
1f449-1f3fd.svg
1f449-1f3fe.svg
1f449-1f3ff.svg
1f449.svg
1f448-1f3fb.svg
1f448-1f3fc.svg
1f448-1f3fd.svg
1f448-1f3fe.svg
1f448-1f3ff.svg
1f448.svg
1f447-1f3fb.svg
1f447-1f3fc.svg
1f447-1f3fd.svg
1f447-1f3fe.svg
1f447-1f3ff.svg
1f447.svg
1f446.svg
1f446-1f3fb.svg
1f446-1f3fc.svg
1f446-1f3fd.svg
1f446-1f3fe.svg
1f446-1f3ff.svg
261d.svg
261d-1f3fb.svg
261d-1f3fc.svg
261d-1f3fd.svg
261d-1f3fe.svg
261d-1f3ff.svg
1f44e.svg
1f44e-1f3fb.svg
1f44e-1f3fc.svg
1f44e-1f3fd.svg
1f44e-1f3fe.svg
1f44e-1f3ff.svg
1f44d.svg
1f44d-1f3ff.svg
1f44d-1f3fb.svg
1f44d-1f3fc.svg
1f44d-1f3fd.svg
1f44d-1f3fe.svg
1f443.svg
1f443-1f3ff.svg
1f443-1f3fb.svg
1f443-1f3fc.svg
1f443-1f3fd.svg
1f443-1f3fe.svg
1f442.svg
1f442-1f3fb.svg
1f442-1f3fc.svg
1f442-1f3fd.svg
1f442-1f3fe.svg
1f442-1f3ff.svg
1f44f.svg
1f44f-1f3ff.svg
1f44f-1f3fb.svg
1f44f-1f3fc.svg
1f44f-1f3fd.svg
1f44f-1f3fe.svg
```

**Comment by rodrigopolo** [comment]
@WebReflection Hi, I created all emojis than can be created just by changing the colors, and I modified all emojis to match iOS 8.3 "neutral" colors, I also added my country flag, 350 emojis added/updated in total, can be downloaded from the fork I made:
https://github.com/rodrigopolo/twemoji/tree/gh-pages/svg

The complete list where you can see the new emojis and the ones missing:
http://rodrigopolo.com/files/emojilist/

Whats left to have the complete iOS 8.3 emoji set found in the iOS keyboard:
* 14 family combinations
* 4 same sex couple (hearts / kisses)
* 32 flags that appear in iOS 8.3 keyboard

Emojis that doesn't appear on the iOS 8.3 keyboard but are available on the Apple emoji font:
* 6 "Vulcan salute" hand (1 neutral 5 color)
* 171 flags.

So, 95% completed if we don't consider adding the flags and the vulcan salute, 83% if not... I'm quite sure Twitter has already created most country flags for the World Cup.

**Comment by rodrigopolo** [comment]
FYI I have updated the emoji list to see which emojis are missing from the Unicode 8.0 and iOS 9.1
http://rodrigopolo.com/files/emojilist/

Emoji One have 72.5% of all emojis
twemoji have 52.57% of all emojis
twemoji with my contribution could have 70.32% of all emojis, and I think it could go higher if it borrows some of the flags and extra assets from Emoji One.

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.
