### ISSUE TITLE
Add `svg` to the list of excluded nodes

### ISSUE THREAD

**Issue by azaozz** [twitter/twemoji#82]
When there are inline SVGs in the HTML, the nodes inside them are part of the DOM and are parsed by twemoji.parse(). This is undesirable, the SVG would break if a character is replaced, and slows things down.

**Comment by azaozz** [comment]
Can make a PR if needed but the change to `shouldntBeParsed` is really simple. Only thing to keep in mind is that `node.nodeName` for SVG is lower case.

**Comment by WebReflection** [comment]
I think I understand the issue, but could you please provide a very basic use case to test against so I'm sure I'm improving the right thing? Thank You!

**Comment by azaozz** [comment]
Sure, here's a basic fiddle: https://jsfiddle.net/aobsL2rg/

It includes the current twemoji.js with a small addition in `grabAllTextNodes()` to show the nodes.

**Comment by WebReflection** [comment]
I've pushed a version that checks for nodeName not to be lowercase within the `shouldntBeParsed` regExp which now is like the following:

```js
shouldntBeParsed = /IFRAME|NOFRAMES|NOSCRIPT|SCRIPT|SELECT|STYLE|TEXTAREA|[a-z]/
```

I've added a test and double checked on your test page too. It does its job, it feels also safe enough.

If you know of any browser so quirk that doesn't return lower case svg nodes, please let me know.

Best Regards

P.S. it might take a little while before it propagates

**Comment by azaozz** [comment]
"If you know of any browser so quirk that doesn't return lower case svg nodes..." IE7 returns upper case node names for SVGs. There may be other, even more "exotic" browsers too. Don't think it matters as none of them would render SVGs.

**Comment by WebReflection** [comment]
> Don't think it matters as none of them would render SVGs.

as long as excluding lower case cases doesn't compromise what works there already, I agree it doesn't matter ;-)
