### ISSUE TITLE
Consider shortening the character matching regexp

### ISSUE THREAD

**Issue by azaozz** [twitter/twemoji#83]
This might have come up before, but listing all possible emoji characters in `re` makes the regexp "too long" and slow. Currently this is especially visible in Chrome where it is much slower because the regexp (phisical) string length exceeds the length for optimization.

Example: https://jsfiddle.net/7vo8wteu/
Chromium bug: https://code.google.com/p/chromium/issues/detail?id=482998

In the comments on the above bug report there are couple of examples that reduce the string length of the regexp and will make it run a bit faster in all browsers (even after the Chrome bug fix).

**Comment by WebReflection** [comment]
AFAICT this is not a twemoji issue, rather a Chromium bug/issue.

**Comment by WebReflection** [comment]
just to be more explicit: no, there's no way the RegExp can be shorter without undesired side-effects, and this is a widely deployed and used, and compatible, RegExp/library so I rather let Chromium experts figure out a fix for this. Thanks for your understanding.
