### ISSUE TITLE
wrong background color on 1f51f 🔟 1F53C 🔼 and 1F53D 🔽

### ISSUE THREAD

**Issue by ck-on** [twitter/twemoji#91]
The background color on 🔟 (the encapsulated 10) is wrong and does not match 0-9

https://github.com/twitter/twemoji/blob/gh-pages/72x72/1f51f.png

compare to

https://abs.twimg.com/emoji/v1/72x72/1f51f.png

(same problem in all sizes)

Same problem with  1F53C 🔼  and 1F53D  🔽

**Comment by prdolmos** [comment]
I fixed this for the 10 keycap: https://github.com/twitter/twemoji/pull/89

I can easily do this for the arrows too. It'll take me a few days to find the time to do it.
