### ISSUE TITLE
The Pushpin metal end is thick

### ISSUE THREAD

**Issue by AlmightySosa** [twitter/twemoji#94]
As you can see below, the metal end to the pushpin is too thick to be like a normal pushpin like the other ones. All that is needed is a little erasing to make the pushpin thinner. This is 1f4cc.
<img width="484" alt="capture" src="https://cloud.githubusercontent.com/assets/13771666/9236954/a6f1c512-410d-11e5-9864-028f4d5e8d74.PNG">

**Comment by bhaggs** [comment]
We've modified this as part v2 to make the metal tip skinnier. You can see it on the preview page: http://twitter.github.io/twemoji/2/test/preview.html
