### ISSUE TITLE
emoji in href attribute

### ISSUE THREAD

**Issue by antpaw** [twitter/twemoji#96]
Hey, Emojis inside the `````<a href="lome\u1111">````` shouldn't be converted. Services like http://www.xn--vi8hiv.ws/ are using it.

**Comment by WebReflection** [comment]
can you provide an example? THe only way to have  problems is to parseString unsanitaized html text ... and you don't want to parseString unsanitaized html text ... https://github.com/twitter/twemoji#dom-parsing

If you use the DOM  parsing you can't have the problem because attributes are not even  considered.

Does this solve your problem?

**Comment by antpaw** [comment]
yes its with dom parsing https://jsfiddle.net/7835zwaw/1/

we want to display user input, the input can have emojis and it can have links, we are using markdown like lib to parse the link and twemoji to parse the emoji

**Comment by antpaw** [comment]
Oh i didn't know i can pass in a dom element to the parse function, so much magic ✨ :)

https://jsfiddle.net/7835zwaw/2/

**Comment by WebReflection** [comment]
that is **not** DOM parsing indeed, it's jquery and unsanitized HTML

Try this  instead.

```js
    twemoji.parse($('p')[0]);
    console.log(twemoji.parse($('p').html()));
```

Regards

**Comment by WebReflection** [comment]
Your second attempt is again  **wring** and vulnerable to security issues.

Try to imagine for an  instance that you don't need **at all** the `.html()` method of jQuery ... again, you **really** need to do just this:

```js
twemoji.parse($('p')[0]);
console.log(twemoji.parse($('p').html()));
```

and it's not about magic,  there are  only two overloads: string and DOM nodes, both documented in the README:
https://github.com/twitter/twemoji#twemojiparse--

> There are mainly two kind of parsing: string parsing and DOM parsing.
> ...
> Differently from string parsing, if the first argument is a HTMLElement generated image tags will replace emoji that are inside #text node only without compromising surrounding nodes or listeners, and avoiding completely the usage of innerHTML.
> ...
> If security is a major concern, this parsing can be considered the safest option

Best regards

**Comment by antpaw** [comment]
that's what i've tried in my first fiddle

https://jsfiddle.net/7835zwaw/3/
looks good in browser
fails in the console
we are using this library in node.js so there are no dom elements available, we can only pass in string

**Comment by WebReflection** [comment]
try this instead: https://github.com/tmpvar/jsdom
otherwise you are going to have hard time. twmoji does not, and won't not, handle unsanitized strings. It opens a whole new world of shenanigans in  terms of security.

I think you should really avoid that.

**Comment by WebReflection** [comment]
btw, funny you can use jQuery without having a DOM in nodejs

**Comment by antpaw** [comment]
okay thanks, i understand, our solution will be not parsing any emojis if the string contains a link.
btw, we can use jquery everywhere http://i.stack.imgur.com/ssRUr.gif

**Comment by WebReflection** [comment]
I don't know how convoluted could be your links, but if these are simple links without nested elements you can **at your own risk** try this:

```js
var emojified = contentWithLinks.replace(/(<a \S+?>)(\S+?)(<\/a>)/, function ($0, $1, $2,  $3) {
  return $1 + twemoji.parse($2) + $3;
});
```

it suffers any sort of problems if you have nodes inside the link + it might fail if the text is not sanitized and you have < or > in the wild as well ... + ... something else, it's your call.

**Comment by antpaw** [comment]
thanks
