### ISSUE TITLE
Emoji Request: Add robot-face (🤖)

### ISSUE THREAD

**Issue by webmaven** [twitter/twemoji#99]
Links:
* http://emojipedia.org/robot-face/
* https://twitter.com/search?q=%23%F0%9F%A4%96

**Comment by pento** [comment]
Twitter has the image on their CDN (along with some extra Unicode 8 emoji), but we're just waiting for them to merge it into this repo. Hopefully soon. :-)

https://abs.twimg.com/emoji/v1/72x72/1f916.png

**Comment by webmaven** [comment]
So, who at Twitter do we need to ping?

**Comment by samccone** [comment]
cc @fcanas :)

**Comment by wp9015362** [comment]
> @webmaven wrote:
> 
> So, who at Twitter do we need to ping?

Probably @bhaggs? See his comment over there:

https://github.com/twitter/twemoji/issues/44#issuecomment-150725919

Regards

**Comment by WebReflection** [comment]
[V2 has landed](https://github.com/twitter/twemoji#unicode-80-and-diversity) with 1661 covered emoji VS just 874 in previous version.

Easy way to update?
prefix `/twemoji.min.js` from MaxCDN via `2/twemoji.min.js` and you're good to go.

**Comment by webmaven** [comment]
:+1:
